/**
 * Build the tee-times + scores ticker data for the upcoming round.
 *
 * Combines DataGolf field-updates (per-round tee times) with in-play
 * (current score / position) for the players still in the field.
 *
 * Usage (after round 2, building the round-3 ticker):
 *   npx tsx scripts/build-ticker.ts --slug pga-championship-2026 --phase r2 --round 3
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const PROJECT_ROOT = new URL('..', import.meta.url).pathname;

function parseArgs(): { slug: string; phase: string; round: string } {
  const a = process.argv.slice(2);
  const o: Record<string, string> = {};
  for (let i = 0; i < a.length; i += 2) o[a[i].replace(/^--/, '')] = a[i + 1];
  for (const k of ['slug', 'phase', 'round']) {
    if (!o[k]) { console.error(`Missing --${k}`); process.exit(1); }
  }
  return o as { slug: string; phase: string; round: string };
}

/** "2026-05-16 13:20" -> "1:20 PM". */
function formatTime(dt: string): string {
  const m = dt.match(/(\d{2}):(\d{2})/);
  if (!m) return dt;
  let h = parseInt(m[1], 10);
  const ampm = h >= 12 ? 'PM' : 'AM';
  h = h % 12 || 12;
  return `${h}:${m[2]} ${ampm}`;
}

async function main() {
  const { slug, phase, round } = parseArgs();
  const roundNum = Number(round);

  const field = JSON.parse(
    await readFile(join(PROJECT_ROOT, 'data', 'raw', slug, phase, 'field-updates.json'), 'utf8')
  );
  const inplay = JSON.parse(
    await readFile(join(PROJECT_ROOT, 'data', 'raw', slug, phase, 'in-play.json'), 'utf8')
  );

  const scoreByName = new Map<string, { score: number | null; pos: string }>();
  for (const p of inplay.data ?? []) {
    scoreByName.set(p.player_name, {
      score: typeof p.current_score === 'number' ? p.current_score : null,
      pos: p.current_pos ?? '--',
    });
  }

  interface TickerEntry {
    player: string;
    teeTime: string;
    startHole: number;
    score: number | null;
    pos: string;
    sortKey: string;
  }

  const entries: TickerEntry[] = [];
  for (const p of field.field ?? []) {
    const tt = (p.teetimes ?? []).find(
      (t: { round_num: number }) => t.round_num === roundNum
    );
    if (!tt) continue; // missed the cut / not in this round
    const sc = scoreByName.get(p.player_name) ?? { score: null, pos: '--' };
    entries.push({
      player: p.player_name,
      teeTime: formatTime(tt.teetime),
      startHole: tt.start_hole,
      score: sc.score,
      pos: sc.pos,
      sortKey: tt.teetime,
    });
  }
  entries.sort((a, b) => a.sortKey.localeCompare(b.sortKey));
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const clean = entries.map(({ sortKey: _sortKey, ...e }) => e);

  const file = [
    `// Generated by scripts/build-ticker.ts on ${new Date().toISOString()}`,
    `// ${slug} — round ${roundNum} tee times + scores. ${clean.length} players. DO NOT EDIT BY HAND.`,
    ``,
    `export interface TickerEntry {`,
    `  player: string;`,
    `  teeTime: string;`,
    `  startHole: number;`,
    `  score: number | null;`,
    `  pos: string;`,
    `}`,
    ``,
    `export const tickerRound = ${roundNum};`,
    `export const tickerData: TickerEntry[] = ${JSON.stringify(clean, null, 2)};`,
    ``,
  ].join('\n');

  await writeFile(join(PROJECT_ROOT, 'src', 'data', 'ticker.ts'), file);
  console.log(`✅ Wrote src/data/ticker.ts — round ${roundNum}, ${clean.length} players.`);
}

main().catch((e) => { console.error('build-ticker failed:', e); process.exit(1); });
