/**
 * Convert a raw DataGolf matchup-odds pull into the frontend's
 * MatchupOddsEntry[] format.
 *
 * Usage:
 *   npx tsx scripts/build-matchups.ts --slug pga-championship-2026 --phase r1 \
 *     --market round_matchups --export r2MatchupOddsData --out pgaChampMatchups
 *
 * The frontend (MatchupsView / OddsTablePage) pairs these odds entries with the
 * player X Scores at render time to produce the actual picks/edges/tiers — so
 * this script only needs to emit the odds, not the picks.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

interface Args {
  slug: string;
  phase: string;
  market: string;
  export: string;
  out: string;
}

function parseArgs(): Args {
  const a = process.argv.slice(2);
  const o: Partial<Args> = { market: 'round_matchups' };
  for (let i = 0; i < a.length; i += 2) {
    const k = a[i].replace(/^--/, '') as keyof Args;
    o[k] = a[i + 1];
  }
  for (const k of ['slug', 'phase', 'export', 'out'] as const) {
    if (!o[k]) {
      console.error(`Missing --${k}`);
      process.exit(1);
    }
  }
  return o as Args;
}

interface RawMatchup {
  p1_player_name: string;
  p2_player_name: string;
  odds: Record<string, { p1: string; p2: string }>;
}

const PROJECT_ROOT = new URL('..', import.meta.url).pathname;

async function main() {
  const { slug, phase, market, export: exportName, out } = parseArgs();
  const rawPath = join(PROJECT_ROOT, 'data', 'raw', slug, phase, `matchups-${market}.json`);
  const raw = JSON.parse(await readFile(rawPath, 'utf8'));
  const list: RawMatchup[] = raw.match_list ?? [];

  const entries = list.map((m) => ({
    p1_player_name: m.p1_player_name,
    p2_player_name: m.p2_player_name,
    odds: m.odds,
  }));

  const header = [
    `import type { MatchupOddsEntry } from '../types';`,
    ``,
    `// Generated by scripts/build-matchups.ts on ${new Date().toISOString()}`,
    `// Event: ${slug}, phase: ${phase}, market: ${market}, round: ${raw.round_num ?? '?'}`,
    `// ${entries.length} matchups. DO NOT EDIT BY HAND.`,
    ``,
    `export const ${exportName}: MatchupOddsEntry[] = ${JSON.stringify(entries, null, 2)};`,
    ``,
  ].join('\n');

  const outPath = join(PROJECT_ROOT, 'src', 'data', `${out}.ts`);
  await writeFile(outPath, header);
  console.log(`✅ Wrote src/data/${out}.ts — ${entries.length} matchups (${market}, round ${raw.round_num}).`);
}

main().catch((e) => {
  console.error('build-matchups failed:', e);
  process.exit(1);
});
