/**
 * Build the DataGolf skill estimates file. Used as the baseline skill
 * input to BirdieX's Monte Carlo tournament simulator (combined with
 * each player's X Score for our model's tilt).
 *
 * Skill is measured in strokes-gained per round vs. field average. Higher
 * is better. Scheffler typically sits ~2.8; a fringe-of-cut player ~ -0.5.
 *
 * Usage:
 *   npx tsx scripts/build-skill-estimates.ts --slug cj-cup-byron-nelson-2026 \
 *     --phase pre --export skillEstimatesData --out cjCupSkillEstimates
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

interface Args {
  slug: string;
  phase: string;
  export: string;
  out: string;
}

function parseArgs(): Args {
  const a = process.argv.slice(2);
  const o: Record<string, string> = {};
  for (let i = 0; i < a.length; i += 2) o[a[i].replace(/^--/, '')] = a[i + 1];
  return o as unknown as Args;
}

const PROJECT_ROOT = new URL('..', import.meta.url).pathname;

interface DgRankingRow {
  dg_id: number;
  player_name: string;
  dg_skill_estimate: number;
  datagolf_rank?: number;
  owgr_rank?: number;
  country?: string;
  am?: number;
}

interface OutrightRow {
  player_name: string;
  dg_id: number;
  datagolf?: { baseline_history_fit?: string };
}

interface PreTournamentRow {
  dg_id: number;
  player_name: string;
  win: number;
  top_5: number;
  top_10: number;
  top_20: number;
  make_cut: number;
}

function americanToProb(odds: string | undefined): number | null {
  if (!odds) return null;
  const n = parseInt(odds, 10);
  if (!Number.isFinite(n) || n === 0) return null;
  return n < 0 ? Math.abs(n) / (Math.abs(n) + 100) : 100 / (n + 100);
}

async function main() {
  const args = parseArgs();
  const baseDir = join(PROJECT_ROOT, 'data', 'raw', args.slug, args.phase);

  const rankings = JSON.parse(await readFile(join(baseDir, 'dg-rankings.json'), 'utf8')) as {
    rankings: DgRankingRow[];
  };

  // Cross-reference with the current field (from outrights — every player in
  // the event appears there) so we only emit skill estimates for the actual
  // field. Plus pull DataGolf's published probabilities for the comparison view.
  const outrights = JSON.parse(await readFile(join(baseDir, 'outrights-win.json'), 'utf8')) as {
    odds: OutrightRow[];
  };
  const preTourney = JSON.parse(await readFile(join(baseDir, 'pre-tournament.json'), 'utf8')) as {
    baseline_history_fit: PreTournamentRow[];
  };

  const skillById = new Map<number, number>();
  for (const r of rankings.rankings) skillById.set(r.dg_id, r.dg_skill_estimate);

  const probsById = new Map<number, PreTournamentRow>();
  for (const r of preTourney.baseline_history_fit) probsById.set(r.dg_id, r);

  // Build one row per player in the field.
  const out = outrights.odds
    .map((o) => {
      const dgSkill = skillById.get(o.dg_id);
      const probs = probsById.get(o.dg_id);
      if (dgSkill == null) return null; // no skill estimate → skip
      return {
        dg_id: o.dg_id,
        player_name: o.player_name,
        dg_skill_estimate: +dgSkill.toFixed(4),
        dg_win_prob: probs?.win ?? null,
        dg_top5_prob: probs?.top_5 ?? null,
        dg_top10_prob: probs?.top_10 ?? null,
        dg_top20_prob: probs?.top_20 ?? null,
        dg_make_cut_prob: probs?.make_cut ?? null,
        dg_baseline_history_fit_odds: o.datagolf?.baseline_history_fit ?? null,
        dg_baseline_history_fit_prob: americanToProb(o.datagolf?.baseline_history_fit),
      };
    })
    .filter((r): r is NonNullable<typeof r> => r !== null);

  out.sort((a, b) => b.dg_skill_estimate - a.dg_skill_estimate);

  const file = [
    `// Generated by scripts/build-skill-estimates.ts on ${new Date().toISOString()}`,
    `// ${args.slug} / ${args.phase} — DataGolf skill estimates + projected probs for the simulator.`,
    `// ${out.length} players. DO NOT EDIT BY HAND.`,
    ``,
    `import type { PlayerSkillEstimate } from '../types';`,
    ``,
    `export const ${args.export}: PlayerSkillEstimate[] = ${JSON.stringify(out, null, 2)};`,
    ``,
  ].join('\n');

  await writeFile(join(PROJECT_ROOT, 'src', 'data', `${args.out}.ts`), file);
  console.log(`✅ Wrote src/data/${args.out}.ts (${out.length} players).`);
}

main().catch((e) => {
  console.error('build-skill-estimates failed:', e);
  process.exit(1);
});
