/**
 * Build the golfer headshot map.
 *
 * DataGolf has no player photos. ESPN's golf leaderboard feed lists the current
 * event's field with athlete IDs + headshot image URLs (ESPN CDN). This script
 * fetches that, name-matches ESPN players to our field, and writes a
 * { playerName -> headshotUrl } map. Unmatched players fall back to an
 * initials avatar in the UI.
 *
 * The map is CUMULATIVE: previously captured matches are read, the current
 * ESPN response is merged on top, and the union is written back. This solves
 * the post-cut problem (ESPN's leaderboard only returns weekend players from
 * R3 onwards, so a fresh-write would drop every cut player's headshot). It
 * also speeds up future events — returning players keep their URL from the
 * first time they were captured.
 *
 * Usage:
 *   npx tsx scripts/build-headshots.ts --players pgaChampR2Data --out headshots
 */
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const PROJECT_ROOT = new URL('..', import.meta.url).pathname;
const ESPN_LEADERBOARD = 'https://site.api.espn.com/apis/site/v2/sports/golf/leaderboard';

function parseArgs(): { players: string; out: string } {
  const a = process.argv.slice(2);
  const o: Record<string, string> = { players: 'pgaChampR2Data', out: 'headshots' };
  for (let i = 0; i < a.length; i += 2) o[a[i].replace(/^--/, '')] = a[i + 1];
  return o as { players: string; out: string };
}

/** Token-set key: lowercased, accent-stripped name tokens, sorted — order-agnostic. */
function nameKey(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z\s,]/g, '')
    .split(/[\s,]+/)
    .filter(Boolean)
    .sort()
    .join(' ');
}

async function main() {
  const { players, out } = parseArgs();

  // Our field.
  const mod = await import(
    pathToFileURL(join(PROJECT_ROOT, 'src', 'data', `${players}.ts`)).href
  );
  const ourPlayers: string[] = (mod.roundOnlyData as Array<{ player_name: string }>).map(
    (p) => p.player_name
  );

  // Load the existing headshot map (if it exists) — we MERGE rather than
  // overwrite so a post-cut ESPN response can't drop previously matched players.
  let existing: Record<string, string> = {};
  try {
    const existingMod = await import(
      pathToFileURL(join(PROJECT_ROOT, 'src', 'data', `${out}.ts`)).href
    );
    if (existingMod.headshots && typeof existingMod.headshots === 'object') {
      existing = { ...(existingMod.headshots as Record<string, string>) };
    }
  } catch {
    // First run — no existing file. Start fresh.
  }

  // ESPN field + headshots.
  const res = await fetch(ESPN_LEADERBOARD);
  if (!res.ok) throw new Error(`ESPN leaderboard fetch failed: ${res.status}`);
  const espn = await res.json();
  const competitors =
    espn?.events?.[0]?.competitions?.[0]?.competitors ?? [];

  const espnByKey = new Map<string, string>();
  for (const c of competitors) {
    const ath = c.athlete ?? {};
    const name: string | undefined = ath.displayName ?? ath.fullName;
    let url: string | undefined = ath.headshot?.href;
    if (!url && ath.id) url = `https://a.espncdn.com/i/headshots/golf/players/full/${ath.id}.png`;
    if (name && url) espnByKey.set(nameKey(name), url);
  }

  // Match our players against the current ESPN response.
  const freshlyMatched: Record<string, string> = {};
  for (const name of ourPlayers) {
    const url = espnByKey.get(nameKey(name));
    if (url) freshlyMatched[name] = url;
  }

  // Merge: existing first, fresh on top (fresh URLs override if ESPN changed them).
  const map: Record<string, string> = { ...existing, ...freshlyMatched };

  // Categorise for the log.
  const freshCount = Object.keys(freshlyMatched).length;
  const retainedFromPrior = ourPlayers.filter(
    (n) => !freshlyMatched[n] && existing[n],
  ).length;
  const stillMissing = ourPlayers.filter((n) => !map[n]);
  const inMapForField = ourPlayers.length - stillMissing.length;

  const file = [
    `// Generated by scripts/build-headshots.ts on ${new Date().toISOString()}`,
    `// Source: ESPN golf leaderboard, merged with prior matches.`,
    `// This event: ${inMapForField}/${ourPlayers.length} players covered`,
    `//   (${freshCount} fresh from ESPN this run, ${retainedFromPrior} retained from prior runs).`,
    `// Total players in cumulative map: ${Object.keys(map).length}.`,
    `// Players not in the map fall back to an initials avatar. DO NOT EDIT BY HAND.`,
    ``,
    `export const headshots: Record<string, string> = ${JSON.stringify(map, null, 2)};`,
    ``,
  ].join('\n');

  await writeFile(join(PROJECT_ROOT, 'src', 'data', `${out}.ts`), file);
  console.log(
    `✅ Wrote src/data/${out}.ts — ${inMapForField}/${ourPlayers.length} of this event's field covered ` +
      `(${freshCount} fresh + ${retainedFromPrior} retained). Map now has ${Object.keys(map).length} players.`,
  );
  if (stillMissing.length) {
    console.log(
      `   Still missing (initials fallback): ${stillMissing.slice(0, 20).join('; ')}${stillMissing.length > 20 ? ` … +${stillMissing.length - 20}` : ''}`,
    );
  }
}

main().catch((e) => {
  console.error('build-headshots failed:', e);
  process.exit(1);
});
