// Generated by scripts/build-outrights.ts on 2026-05-23T06:13:13.607Z
// cj-cup-byron-nelson-2026 / r2 — outright WINNER odds, 146 entries.
// Best odds computed across real sportsbooks (DataGolf excluded). DO NOT EDIT BY HAND.

import type { OutrightEntry } from '../types';

export const r3OutrightsData: OutrightEntry[] = [
  {
    "player_name": "Piercy, Scott",
    "dg_id": 7899,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Bezuidenhout, Christiaan",
    "dg_id": 18103,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Brennan, Michael",
    "dg_id": 29197,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Buchanan, Jackson",
    "dg_id": 32333,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Hardy, Nick",
    "dg_id": 19865,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Li, Haotong",
    "dg_id": 15310,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Howell, Mason",
    "dg_id": 33759,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Streb, Robert",
    "dg_id": 14852,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Springer, Hayden",
    "dg_id": 21995,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Young, Carson",
    "dg_id": 23656,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Chatfield, Davis",
    "dg_id": 30620,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Dunlap, Nick",
    "dg_id": 28270,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Goodwin, Noah",
    "dg_id": 24837,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Gordon, Will",
    "dg_id": 26660,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Skinns, David",
    "dg_id": 10873,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Thorbjornsen, Michael",
    "dg_id": 26649,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Peterson, Paul",
    "dg_id": 16341,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Kizzire, Patton",
    "dg_id": 13470,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Ventura, Kris",
    "dg_id": 15651,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Vilips, Karl",
    "dg_id": 24304,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Whaley, Vince",
    "dg_id": 25908,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Yu, Kevin",
    "dg_id": 17881,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Banerjee, Ronin",
    "dg_id": 30039402,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "McGreevy, Max",
    "dg_id": 23505,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Dumont De Chassart, Adrien",
    "dg_id": 22002,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Hodges, Lee",
    "dg_id": 25157,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Hossler, Beau",
    "dg_id": 15470,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Martin, Ben",
    "dg_id": 14007,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Nakajima, Keita",
    "dg_id": 21074,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Dou, Zecheng",
    "dg_id": 16757,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Phillips, Chandler",
    "dg_id": 27164,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Rozo, Marcelo",
    "dg_id": 16591,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Horschel, Billy",
    "dg_id": 11276,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Schmid, Matti",
    "dg_id": 20722,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Lee, K.H.",
    "dg_id": 13497,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Wise, Aaron",
    "dg_id": 22051,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Kanaya, Takumi",
    "dg_id": 19729,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Hahn, James",
    "dg_id": 11374,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Schenk, Adam",
    "dg_id": 19477,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Davis, Cam",
    "dg_id": 17786,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Wu, Dylan",
    "dg_id": 25002,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Laird, Martin",
    "dg_id": 9586,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Mouw, William",
    "dg_id": 29770,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Riley, Davis",
    "dg_id": 19872,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Kuchar, Matt",
    "dg_id": 6169,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Crowe, Trace",
    "dg_id": 27780,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Hadwin, Adam",
    "dg_id": 13965,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Montgomery, Taylor",
    "dg_id": 25442,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Kohles, Ben",
    "dg_id": 16395,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Sides, William",
    "dg_id": 30035052,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Vegas, Jhonattan",
    "dg_id": 13508,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Walker, Danny",
    "dg_id": 25003,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Blanchet, Chandler",
    "dg_id": 24956,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Dahmen, Joel",
    "dg_id": 14509,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Higgs, Harry",
    "dg_id": 14140,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Thompson, Davis",
    "dg_id": 27364,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Brehm, Ryan",
    "dg_id": 10423,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Sargent, Gordon",
    "dg_id": 30814,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Campos, Rafael",
    "dg_id": 12909,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Garnett, Brice",
    "dg_id": 11451,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Lamprecht, Christo",
    "dg_id": 24343,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Stout, Preston",
    "dg_id": 32089,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Cook, Austin",
    "dg_id": 18579,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Streelman, Kevin",
    "dg_id": 8480,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Norlander, Henrik",
    "dg_id": 11657,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Nyholm, Pontus",
    "dg_id": 25475,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Highsmith, Joe",
    "dg_id": 28469,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Gregory, Greg",
    "dg_id": 6243,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Huang, Alex",
    "dg_id": 30041533,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Headley, Adam",
    "dg_id": 10070198,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Petronzio, Nathan",
    "dg_id": 29915,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Tosti, Alejandro",
    "dg_id": 17032,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Roy, Kevin",
    "dg_id": 18424,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Stanger, Jimmy",
    "dg_id": 23048,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Palmer, Ryan",
    "dg_id": 7820,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Paul, Jeremy",
    "dg_id": 22087,
    "bestOdds": "",
    "bestBook": "",
    "dgOdds": null,
    "allBooks": {}
  },
  {
    "player_name": "Kim, Si Woo",
    "dg_id": 14609,
    "bestOdds": "-122",
    "bestBook": "draftkings",
    "dgOdds": "-122",
    "allBooks": {
      "bet365": "-137",
      "betmgm": "-143",
      "caesars": "-125",
      "draftkings": "-122",
      "fanduel": "-140",
      "pinnacle": "-132",
      "betonline": "-130",
      "bovada": "-135",
      "unibet": "-133",
      "betcris": "-130"
    }
  },
  {
    "player_name": "Scheffler, Scottie",
    "dg_id": 18417,
    "bestOdds": "+268",
    "bestBook": "pinnacle",
    "dgOdds": "+368",
    "allBooks": {
      "bet365": "+230",
      "betmgm": "+250",
      "caesars": "+245",
      "draftkings": "+240",
      "fanduel": "+240",
      "pinnacle": "+268",
      "betonline": "+250",
      "bovada": "+250",
      "unibet": "+225",
      "betcris": "+245"
    }
  },
  {
    "player_name": "Spieth, Jordan",
    "dg_id": 14636,
    "bestOdds": "+2261",
    "bestBook": "pinnacle",
    "dgOdds": "+3163",
    "allBooks": {
      "bet365": "+1800",
      "betmgm": "+2000",
      "caesars": "+1750",
      "draftkings": "+1900",
      "fanduel": "+2000",
      "pinnacle": "+2261",
      "betonline": "+1800",
      "bovada": "+2000",
      "unibet": "+1800",
      "betcris": "+2061"
    }
  },
  {
    "player_name": "Clark, Wyndham",
    "dg_id": 23604,
    "bestOdds": "+2500",
    "bestBook": "betonline",
    "dgOdds": "+2475",
    "allBooks": {
      "bet365": "+2200",
      "betmgm": "+2200",
      "caesars": "+2000",
      "draftkings": "+2050",
      "fanduel": "+2200",
      "pinnacle": "+2204",
      "betonline": "+2500",
      "bovada": "+2200",
      "unibet": "+2000",
      "betcris": "+2300"
    }
  },
  {
    "player_name": "Im, Sungjae",
    "dg_id": 17488,
    "bestOdds": "+2613",
    "bestBook": "betcris",
    "dgOdds": "+3484",
    "allBooks": {
      "bet365": "+2200",
      "betmgm": "+2200",
      "caesars": "+1900",
      "draftkings": "+2300",
      "fanduel": "+2200",
      "pinnacle": "+2455",
      "betonline": "+2500",
      "bovada": "+2200",
      "unibet": "+2000",
      "betcris": "+2613"
    }
  },
  {
    "player_name": "Mitchell, Keith",
    "dg_id": 17365,
    "bestOdds": "+4084",
    "bestBook": "pinnacle",
    "dgOdds": "+4427",
    "allBooks": {
      "bet365": "+3300",
      "betmgm": "+4000",
      "caesars": "+3000",
      "draftkings": "+3000",
      "fanduel": "+3300",
      "pinnacle": "+4084",
      "betonline": "+3500",
      "bovada": "+4000",
      "unibet": "+3300",
      "betcris": "+3752"
    }
  },
  {
    "player_name": "Finau, Tony",
    "dg_id": 11676,
    "bestOdds": "+7500",
    "bestBook": "bovada",
    "dgOdds": "+6092",
    "allBooks": {
      "bet365": "+7000",
      "betmgm": "+7000",
      "caesars": "+6000",
      "draftkings": "+6900",
      "fanduel": "+6500",
      "pinnacle": "+6235",
      "betonline": "+6000",
      "bovada": "+7500",
      "unibet": "+7000",
      "betcris": "+6552"
    }
  },
  {
    "player_name": "Koepka, Brooks",
    "dg_id": 16243,
    "bestOdds": "+8000",
    "bestBook": "betmgm",
    "dgOdds": "+14416",
    "allBooks": {
      "bet365": "+7500",
      "betmgm": "+8000",
      "caesars": "+8000",
      "draftkings": "+6700",
      "fanduel": "+8000",
      "pinnacle": "+7417",
      "betonline": "+8000",
      "bovada": "+7500",
      "unibet": "+7000",
      "betcris": "+6053"
    }
  },
  {
    "player_name": "Suber, Jackson",
    "dg_id": 29279,
    "bestOdds": "+9000",
    "bestBook": "betmgm",
    "dgOdds": "+7509",
    "allBooks": {
      "bet365": "+7000",
      "betmgm": "+9000",
      "caesars": "+6000",
      "draftkings": "+6300",
      "fanduel": "+6500",
      "pinnacle": "+6563",
      "betonline": "+7000",
      "bovada": "+8000",
      "unibet": "+6000",
      "betcris": "+6054"
    }
  },
  {
    "player_name": "Hirata, Kensei",
    "dg_id": 20954,
    "bestOdds": "+10500",
    "bestBook": "draftkings",
    "dgOdds": "+10286",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+10000",
      "caesars": "+8000",
      "draftkings": "+10500",
      "fanduel": "+8000",
      "pinnacle": "+9852",
      "betonline": "+8000",
      "bovada": "+9000",
      "unibet": "+9000",
      "betcris": "+8553"
    }
  },
  {
    "player_name": "Hoge, Tom",
    "dg_id": 15575,
    "bestOdds": "+12500",
    "bestBook": "bovada",
    "dgOdds": "+13160",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+11000",
      "caesars": "+9000",
      "draftkings": "+10500",
      "fanduel": "+10000",
      "pinnacle": "+11293",
      "betonline": "+11000",
      "bovada": "+12500",
      "unibet": "+9000",
      "betcris": "+10610"
    }
  },
  {
    "player_name": "Moore, Taylor",
    "dg_id": 21944,
    "bestOdds": "+12500",
    "bestBook": "bovada",
    "dgOdds": "+13493",
    "allBooks": {
      "bet365": "+11000",
      "betmgm": "+11000",
      "caesars": "+9000",
      "draftkings": "+11500",
      "fanduel": "+10000",
      "pinnacle": "+11468",
      "betonline": "+10000",
      "bovada": "+12500",
      "unibet": "+10000",
      "betcris": "+12058"
    }
  },
  {
    "player_name": "Jaeger, Stephan",
    "dg_id": 16394,
    "bestOdds": "+17000",
    "bestBook": "draftkings",
    "dgOdds": "+21764",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+15000",
      "caesars": "+15000",
      "draftkings": "+17000",
      "fanduel": "+12500",
      "pinnacle": "+15073",
      "betonline": "+15000",
      "bovada": "+15000",
      "unibet": "+10000",
      "betcris": "+12058"
    }
  },
  {
    "player_name": "Power, Seamus",
    "dg_id": 10104,
    "bestOdds": "+17500",
    "bestBook": "betmgm",
    "dgOdds": "+26059",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+17500",
      "caesars": "+15000",
      "draftkings": "+15500",
      "fanduel": "+15000",
      "pinnacle": "+17263",
      "bovada": "+17500",
      "unibet": "+12500",
      "betcris": "+15260"
    }
  },
  {
    "player_name": "Bauchou, Zach",
    "dg_id": 19846,
    "bestOdds": "+19500",
    "bestBook": "draftkings",
    "dgOdds": "+18236",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+17500",
      "caesars": "+15000",
      "draftkings": "+19500",
      "fanduel": "+15000",
      "pinnacle": "+13226",
      "betonline": "+15000",
      "bovada": "+17500",
      "unibet": "+15000",
      "betcris": "+15260"
    }
  },
  {
    "player_name": "Meissner, Mac",
    "dg_id": 28159,
    "bestOdds": "+22500",
    "bestBook": "betmgm",
    "dgOdds": "+24243",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+22500",
      "caesars": "+15000",
      "draftkings": "+16500",
      "fanduel": "+17500",
      "pinnacle": "+17928",
      "betonline": "+20000",
      "bovada": "+20000",
      "unibet": "+14000",
      "betcris": "+14259"
    }
  },
  {
    "player_name": "Coody, Pierceson",
    "dg_id": 28309,
    "bestOdds": "+25000",
    "bestBook": "bovada",
    "dgOdds": "+28854",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+22500",
      "caesars": "+22500",
      "draftkings": "+20000",
      "fanduel": "+17500",
      "pinnacle": "+19783",
      "bovada": "+25000",
      "unibet": "+20000",
      "betcris": "+15260"
    }
  },
  {
    "player_name": "Duncan, Tyler",
    "dg_id": 18187,
    "bestOdds": "+30000",
    "bestBook": "betmgm",
    "dgOdds": "+32082",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+30000",
      "caesars": "+22500",
      "draftkings": "+26000",
      "fanduel": "+22500",
      "pinnacle": "+22769",
      "bovada": "+25000",
      "unibet": "+18000",
      "betcris": "+18562"
    }
  },
  {
    "player_name": "Neergaard-Petersen, Rasmus",
    "dg_id": 23841,
    "bestOdds": "+30000",
    "bestBook": "bet365",
    "dgOdds": "+36308",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+30000",
      "caesars": "+27500",
      "draftkings": "+21000",
      "fanduel": "+22500",
      "pinnacle": "+24034",
      "bovada": "+30000",
      "unibet": "+22500",
      "betcris": "+20664"
    }
  },
  {
    "player_name": "Greyserman, Max",
    "dg_id": 23465,
    "bestOdds": "+35000",
    "bestBook": "betmgm",
    "dgOdds": "+33363",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+35000",
      "caesars": "+22500",
      "draftkings": "+29000",
      "fanduel": "+22500",
      "pinnacle": "+21969",
      "bovada": "+25000",
      "unibet": "+25000",
      "betcris": "+20564"
    }
  },
  {
    "player_name": "Kim, Chan",
    "dg_id": 15004,
    "bestOdds": "+50000",
    "bestBook": "bovada",
    "dgOdds": "+34562",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+35000",
      "caesars": "+30000",
      "draftkings": "+30000",
      "fanduel": "+22500",
      "pinnacle": "+27320",
      "bovada": "+50000",
      "unibet": "+32500",
      "betcris": "+21564"
    }
  },
  {
    "player_name": "Hoey, Rico",
    "dg_id": 23504,
    "bestOdds": "+50000",
    "bestBook": "fanduel",
    "dgOdds": "+50613",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+40000",
      "caesars": "+40000",
      "draftkings": "+32000",
      "fanduel": "+50000",
      "pinnacle": "+28939",
      "bovada": "+50000",
      "unibet": "+32500",
      "betcris": "+20564"
    }
  },
  {
    "player_name": "Rodgers, Patrick",
    "dg_id": 16283,
    "bestOdds": "+50000",
    "bestBook": "bet365",
    "dgOdds": "+77407",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+50000",
      "caesars": "+40000",
      "draftkings": "+45000",
      "fanduel": "+50000",
      "pinnacle": "+33873",
      "bovada": "+50000",
      "unibet": "+40000"
    }
  },
  {
    "player_name": "Kirk, Chris",
    "dg_id": 12423,
    "bestOdds": "+60000",
    "bestBook": "betmgm",
    "dgOdds": "+88657",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+47500",
      "fanduel": "+50000",
      "pinnacle": "+35381",
      "bovada": "+50000",
      "unibet": "+45000"
    }
  },
  {
    "player_name": "Brown, Blades",
    "dg_id": 32152,
    "bestOdds": "+70000",
    "bestBook": "draftkings",
    "dgOdds": "+127861",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+70000",
      "fanduel": "+50000",
      "bovada": "+50000",
      "unibet": "+45000"
    }
  },
  {
    "player_name": "Fisk, Steven",
    "dg_id": 26657,
    "bestOdds": "+75000",
    "bestBook": "fanduel",
    "dgOdds": "+75681",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+60000",
      "fanduel": "+75000",
      "pinnacle": "+37795",
      "bovada": "+60000",
      "unibet": "+55000"
    }
  },
  {
    "player_name": "Pendrith, Taylor",
    "dg_id": 17780,
    "bestOdds": "+75000",
    "bestBook": "fanduel",
    "dgOdds": "+79714",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+57500",
      "fanduel": "+75000",
      "bovada": "+50000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "Hubbard, Mark",
    "dg_id": 16333,
    "bestOdds": "+75000",
    "bestBook": "draftkings",
    "dgOdds": "+136452",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+75000",
      "fanduel": "+75000",
      "pinnacle": "+37019",
      "bovada": "+75000",
      "unibet": "+55000"
    }
  },
  {
    "player_name": "Ryder, Sam",
    "dg_id": 16715,
    "bestOdds": "+77500",
    "bestBook": "draftkings",
    "dgOdds": "+109489",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+77500",
      "fanduel": "+75000",
      "pinnacle": "+41630",
      "bovada": "+75000",
      "unibet": "+55000"
    }
  },
  {
    "player_name": "Clanton, Luke",
    "dg_id": 32330,
    "bestOdds": "+100000",
    "bestBook": "bovada",
    "dgOdds": "+83757",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+57500",
      "fanduel": "+75000",
      "pinnacle": "+37805",
      "bovada": "+100000",
      "unibet": "+55000"
    }
  },
  {
    "player_name": "Ewart, A.J.",
    "dg_id": 21883,
    "bestOdds": "+100000",
    "bestBook": "bet365",
    "dgOdds": "+109239",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+100000",
      "caesars": "+75000",
      "draftkings": "+97500",
      "fanduel": "+100000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "Grillo, Emiliano",
    "dg_id": 12808,
    "bestOdds": "+100000",
    "bestBook": "betmgm",
    "dgOdds": "+118419",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+100000",
      "caesars": "+47500",
      "draftkings": "+87500",
      "fanduel": "+75000",
      "bovada": "+50000",
      "unibet": "+45000"
    }
  },
  {
    "player_name": "Ramey, Chad",
    "dg_id": 19840,
    "bestOdds": "+100000",
    "bestBook": "bet365",
    "dgOdds": "+151607",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+100000",
      "caesars": "+50000",
      "draftkings": "+62500",
      "fanduel": "+100000",
      "pinnacle": "+39555",
      "bovada": "+75000",
      "unibet": "+55000"
    }
  },
  {
    "player_name": "Smith, Jordan",
    "dg_id": 18586,
    "bestOdds": "+100000",
    "bestBook": "bet365",
    "dgOdds": "+155340",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+100000",
      "caesars": "+75000",
      "draftkings": "+82500",
      "fanduel": "+100000",
      "bovada": "+75000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "Ghim, Doug",
    "dg_id": 24550,
    "bestOdds": "+100000",
    "bestBook": "betmgm",
    "dgOdds": "+158780",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+100000",
      "caesars": "+75000",
      "draftkings": "+90000",
      "fanduel": "+100000",
      "bovada": "+100000",
      "unibet": "+90000"
    }
  },
  {
    "player_name": "Van Rooyen, Erik",
    "dg_id": 17550,
    "bestOdds": "+100000",
    "bestBook": "betmgm",
    "dgOdds": "+217095",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+100000",
      "caesars": "+100000",
      "draftkings": "+100000",
      "fanduel": "+100000",
      "bovada": "+100000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "List, Luke",
    "dg_id": 7960,
    "bestOdds": "+110000",
    "bestBook": "draftkings",
    "dgOdds": "+147540",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+100000",
      "caesars": "+75000",
      "draftkings": "+110000",
      "fanduel": "+100000",
      "bovada": "+75000",
      "unibet": "+55000"
    }
  },
  {
    "player_name": "Fishburn, Patrick",
    "dg_id": 25094,
    "bestOdds": "+110000",
    "bestBook": "draftkings",
    "dgOdds": "+164784",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+100000",
      "caesars": "+100000",
      "draftkings": "+110000",
      "fanduel": "+100000",
      "bovada": "+100000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "Hisatsune, Ryo",
    "dg_id": 22760,
    "bestOdds": "+115000",
    "bestBook": "draftkings",
    "dgOdds": "+115563",
    "allBooks": {
      "bet365": "+75000",
      "caesars": "+100000",
      "draftkings": "+115000",
      "fanduel": "+100000",
      "bovada": "+75000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "Lebioda, Hank",
    "dg_id": 21943,
    "bestOdds": "+125000",
    "bestBook": "draftkings",
    "dgOdds": "+230669",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+100000",
      "caesars": "+75000",
      "draftkings": "+125000",
      "fanduel": "+100000",
      "bovada": "+75000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "Villegas, Camilo",
    "dg_id": 9171,
    "bestOdds": "+140000",
    "bestBook": "draftkings",
    "dgOdds": "+126083",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+100000",
      "caesars": "+125000",
      "draftkings": "+140000",
      "fanduel": "+100000",
      "bovada": "+100000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "Hojgaard, Rasmus",
    "dg_id": 23838,
    "bestOdds": "+150000",
    "bestBook": "bet365",
    "dgOdds": "+156763",
    "allBooks": {
      "bet365": "+150000",
      "caesars": "+75000",
      "draftkings": "+120000",
      "fanduel": "+100000",
      "bovada": "+100000",
      "unibet": "+90000"
    }
  },
  {
    "player_name": "Hughes, Mackenzie",
    "dg_id": 15556,
    "bestOdds": "+150000",
    "bestBook": "bet365",
    "dgOdds": "+183808",
    "allBooks": {
      "bet365": "+150000",
      "caesars": "+125000",
      "draftkings": "+135000",
      "fanduel": "+100000",
      "bovada": "+100000",
      "unibet": "+90000"
    }
  },
  {
    "player_name": "Parry, John",
    "dg_id": 13764,
    "bestOdds": "+150000",
    "bestBook": "bet365",
    "dgOdds": "+358109",
    "allBooks": {
      "bet365": "+150000",
      "caesars": "+125000",
      "draftkings": "+125000",
      "fanduel": "+100000",
      "bovada": "+150000",
      "unibet": "+90000"
    }
  },
  {
    "player_name": "Kim, Tom",
    "dg_id": 24766,
    "bestOdds": "+190000",
    "bestBook": "draftkings",
    "dgOdds": "+196783",
    "allBooks": {
      "bet365": "+100000",
      "caesars": "+100000",
      "draftkings": "+190000",
      "fanduel": "+100000",
      "bovada": "+100000",
      "unibet": "+70000"
    }
  },
  {
    "player_name": "Cole, Eric",
    "dg_id": 21756,
    "bestOdds": "+200000",
    "bestBook": "draftkings",
    "dgOdds": "+206086",
    "allBooks": {
      "bet365": "+100000",
      "caesars": "+75000",
      "draftkings": "+200000",
      "fanduel": "+100000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Noh, S.Y.",
    "dg_id": 11117,
    "bestOdds": "+250000",
    "bestBook": "bovada",
    "dgOdds": "+247323",
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+100000",
      "caesars": "+200000",
      "draftkings": "+145000",
      "fanduel": "+100000",
      "bovada": "+250000"
    }
  },
  {
    "player_name": "Griffin, Lanto",
    "dg_id": 15330,
    "bestOdds": "+275000",
    "bestBook": "draftkings",
    "dgOdds": "+417291",
    "allBooks": {
      "bet365": "+200000",
      "caesars": "+125000",
      "draftkings": "+275000",
      "fanduel": "+100000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Keefer, Johnny",
    "dg_id": 32457,
    "bestOdds": "+300000",
    "bestBook": "bovada",
    "dgOdds": "+675956",
    "allBooks": {
      "bet365": "+250000",
      "caesars": "+200000",
      "draftkings": "+250000",
      "fanduel": "+100000",
      "bovada": "+300000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "VanDerLaan, John",
    "dg_id": 25319,
    "bestOdds": "+325000",
    "bestBook": "draftkings",
    "dgOdds": "+521639",
    "allBooks": {
      "bet365": "+250000",
      "caesars": "+200000",
      "draftkings": "+325000",
      "fanduel": "+100000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Olesen, Thorbjorn",
    "dg_id": 13412,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+999900",
    "allBooks": {
      "bet365": "+250000",
      "caesars": "+250000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Eckroat, Austin",
    "dg_id": 26653,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+1999900",
    "allBooks": {
      "bet365": "+200000",
      "caesars": "+125000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Malnati, Peter",
    "dg_id": 14926,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+794602",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "bovada": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Silverman, Ben",
    "dg_id": 17381,
    "bestOdds": "+500000",
    "bestBook": "bovada",
    "dgOdds": "+1043378",
    "allBooks": {
      "bet365": "+250000",
      "caesars": "+125000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "bovada": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Svensson, Jesper",
    "dg_id": 26850,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+1131975",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+200000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Higgo, Garrick",
    "dg_id": 24342,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+1391204",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Bae, Yongjun",
    "dg_id": 25628,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+1548287",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Brown, Dan",
    "dg_id": 20766,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+1599900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Blair, Zac",
    "dg_id": 17639,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+1777678",
    "allBooks": {
      "bet365": "+500000",
      "draftkings": "+450000",
      "bovada": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Hoffman, Charley",
    "dg_id": 5768,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "bovada": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Merritt, Troy",
    "dg_id": 13367,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "bovada": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Svensson, Adam",
    "dg_id": 13997,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+500000",
      "draftkings": "+500000",
      "bovada": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Saddier, Adrien",
    "dg_id": 14792,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+6222122",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+42500",
      "draftkings": "+500000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Pavon, Matthieu",
    "dg_id": 19960,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+7999900",
    "allBooks": {
      "bet365": "+500000",
      "draftkings": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Willett, Danny",
    "dg_id": 12920,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+7999900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+100000",
      "draftkings": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Shipley, Neal",
    "dg_id": 32055,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+11999900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "bovada": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Kang, Jeffrey",
    "dg_id": 21889,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+11999900",
    "allBooks": {
      "bet365": "+500000",
      "draftkings": "+500000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Lower, Justin",
    "dg_id": 17723,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+11999900",
    "allBooks": {
      "bet365": "+500000",
      "draftkings": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Gomez, Fabian",
    "dg_id": 8571,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "draftkings": "+500000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Byrd, Jonathan",
    "dg_id": 6931,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "draftkings": "+500000",
      "unibet": "+100000"
    }
  }
];
