import type { MatchupOddsEntry } from '../types';

// Generated by scripts/build-matchups.ts on 2026-06-06T04:13:43.822Z
// Event: the-memorial-tournament-2026, phase: r2, market: round_matchups, round: 3
// 245 matchups (merged best-odds-ever-seen). DO NOT EDIT BY HAND.

export const r3MatchupOddsData: MatchupOddsEntry[] = [
  {
    "p1_player_name": "Aberg, Ludvig",
    "p2_player_name": "Bhatia, Akshay",
    "odds": {
      "datagolf": {
        "p1": "-158",
        "p2": "+158"
      },
      "pinnacle": {
        "p1": "-158",
        "p2": "+132"
      }
    }
  },
  {
    "p1_player_name": "Aberg, Ludvig",
    "p2_player_name": "Meissner, Mac",
    "odds": {
      "betcris": {
        "p1": "-184",
        "p2": "+146"
      },
      "datagolf": {
        "p1": "-166",
        "p2": "+166"
      }
    }
  },
  {
    "p1_player_name": "Bauchou, Zach",
    "p2_player_name": "Fisk, Steven",
    "odds": {
      "datagolf": {
        "p1": "-106",
        "p2": "+106"
      },
      "fanduel": {
        "p1": "-111",
        "p2": "-111"
      }
    }
  },
  {
    "p1_player_name": "Bauchou, Zach",
    "p2_player_name": "Moore, Taylor",
    "odds": {
      "betcris": {
        "p1": "-119",
        "p2": "-111"
      },
      "datagolf": {
        "p1": "-104",
        "p2": "+104"
      }
    }
  },
  {
    "p1_player_name": "Bauchou, Zach",
    "p2_player_name": "Smotherman, Austin",
    "odds": {
      "betonline": {
        "p1": "-125",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "-117",
        "p2": "+117"
      }
    }
  },
  {
    "p1_player_name": "Berger, Daniel",
    "p2_player_name": "Coody, Pierceson",
    "odds": {
      "betcris": {
        "p1": "-125",
        "p2": "-105"
      },
      "betonline": {
        "p1": "-130",
        "p2": "+109"
      },
      "datagolf": {
        "p1": "-112",
        "p2": "+112"
      }
    }
  },
  {
    "p1_player_name": "Bezuidenhout, Christiaan",
    "p2_player_name": "Thompson, Davis",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "betonline": {
        "p1": "-125",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "-117",
        "p2": "+117"
      },
      "bovada": {
        "p1": "-115",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Bhatia, Akshay",
    "p2_player_name": "Brennan, Michael",
    "odds": {
      "betcris": {
        "p1": "-147",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "-128",
        "p2": "+128"
      }
    }
  },
  {
    "p1_player_name": "Bhatia, Akshay",
    "p2_player_name": "Gotterup, Chris",
    "odds": {
      "betcris": {
        "p1": "+102",
        "p2": "-132"
      },
      "datagolf": {
        "p1": "+106",
        "p2": "-106"
      }
    }
  },
  {
    "p1_player_name": "Bhatia, Akshay",
    "p2_player_name": "Thorbjornsen, Michael",
    "odds": {
      "datagolf": {
        "p1": "-106",
        "p2": "+106"
      },
      "draftkings": {
        "p1": "-122",
        "p2": "-108"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Conners, Corey",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "+116",
        "p2": "+130"
      },
      "pointsbet": {
        "p1": "-115",
        "p2": "+115"
      },
      "betmgm": {
        "p1": "-118",
        "p2": "-105"
      },
      "betonline": {
        "p1": "-120",
        "p2": "+100"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      },
      "caesars": {
        "p1": "-135",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-120",
        "p2": "-105"
      },
      "unibet": {
        "p1": "-136",
        "p2": "+106"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Hisatsune, Ryo",
    "odds": {
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+112",
        "p2": "-112"
      },
      "draftkings": {
        "p1": "-118",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "bet365": {
        "p1": "+100",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "+102",
        "p2": "-102"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-128"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Lowry, Shane",
    "odds": {
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      },
      "draftkings": {
        "p1": "-114",
        "p2": "-115"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "MacIntyre, Robert",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "bovada": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+148",
        "p2": "-148"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "McCarty, Matt",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-106",
        "p2": "+106"
      },
      "bovada": {
        "p1": "-115",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "McNealy, Maverick",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+114",
        "p2": "+131"
      },
      "pointsbet": {
        "p1": "+100",
        "p2": "-105"
      },
      "betcris": {
        "p1": "-124",
        "p2": "-106"
      },
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "caesars": {
        "p1": "-105",
        "p2": "-125"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-122"
      },
      "fanduel": {
        "p1": "-110",
        "p2": "-120"
      },
      "pinnacle": {
        "p1": "-113",
        "p2": "-107"
      },
      "unibet": {
        "p1": "-122",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Putnam, Andrew",
    "odds": {
      "betcris": {
        "p1": "-120",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-105",
        "p2": "+105"
      },
      "unibet": {
        "p1": "-132",
        "p2": "+104"
      }
    }
  },
  {
    "p1_player_name": "Burns, Sam",
    "p2_player_name": "Bhatia, Akshay",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "+109",
        "p2": "+136"
      },
      "betmgm": {
        "p1": "-122",
        "p2": "+100"
      },
      "betonline": {
        "p1": "-128",
        "p2": "+107"
      },
      "bovada": {
        "p1": "-135",
        "p2": "+115"
      },
      "caesars": {
        "p1": "-135",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-125",
        "p2": "+100"
      },
      "pinnacle": {
        "p1": "-121",
        "p2": "+102"
      },
      "unibet": {
        "p1": "-129",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "Burns, Sam",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "datagolf": {
        "p1": "-111",
        "p2": "+111"
      },
      "draftkings": {
        "p1": "-128",
        "p2": "-104"
      }
    }
  },
  {
    "p1_player_name": "Burns, Sam",
    "p2_player_name": "Gerard, Ryan",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-114",
        "p2": "+114"
      }
    }
  },
  {
    "p1_player_name": "Campbell, Brian",
    "p2_player_name": "Coody, Pierceson",
    "odds": {
      "bet365": {
        "p1": "+137",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+198",
        "p2": "-133"
      },
      "pointsbet": {
        "p1": "+160",
        "p2": "-160"
      },
      "betmgm": {
        "p1": "+155",
        "p2": "-192"
      },
      "bovada": {
        "p1": "+145",
        "p2": "-175"
      },
      "caesars": {
        "p1": "+160",
        "p2": "-200"
      },
      "draftkings": {
        "p1": "+146",
        "p2": "-182"
      },
      "unibet": {
        "p1": "+155",
        "p2": "-195"
      }
    }
  },
  {
    "p1_player_name": "Cantlay, Patrick",
    "p2_player_name": "Cole, Eric",
    "odds": {
      "bet365": {
        "p1": "-130",
        "p2": "+145"
      },
      "datagolf": {
        "p1": "-108",
        "p2": "+163"
      },
      "pointsbet": {
        "p1": "-130",
        "p2": "+135"
      },
      "betcris": {
        "p1": "-165",
        "p2": "+131"
      },
      "caesars": {
        "p1": "-155",
        "p2": "+122"
      },
      "draftkings": {
        "p1": "-180",
        "p2": "+144"
      },
      "pinnacle": {
        "p1": "-151",
        "p2": "+123"
      },
      "unibet": {
        "p1": "-162",
        "p2": "+128"
      }
    }
  },
  {
    "p1_player_name": "Cantlay, Patrick",
    "p2_player_name": "Fitzpatrick, Matt",
    "odds": {
      "betcris": {
        "p1": "-112",
        "p2": "-118"
      },
      "datagolf": {
        "p1": "+115",
        "p2": "-115"
      }
    }
  },
  {
    "p1_player_name": "Cantlay, Patrick",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "datagolf": {
        "p1": "-103",
        "p2": "+103"
      },
      "draftkings": {
        "p1": "-126",
        "p2": "-104"
      }
    }
  },
  {
    "p1_player_name": "Cantlay, Patrick",
    "p2_player_name": "Schauffele, Xander",
    "odds": {
      "betonline": {
        "p1": "+100",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "+113",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Cauley, Bud",
    "p2_player_name": "Hisatsune, Ryo",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      }
    }
  },
  {
    "p1_player_name": "Cauley, Bud",
    "p2_player_name": "Kim, Michael",
    "odds": {
      "betonline": {
        "p1": "-132",
        "p2": "+110"
      },
      "datagolf": {
        "p1": "-114",
        "p2": "+114"
      }
    }
  },
  {
    "p1_player_name": "Cauley, Bud",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "betcris": {
        "p1": "+100",
        "p2": "-130"
      },
      "datagolf": {
        "p1": "+107",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Cauley, Bud",
    "p2_player_name": "Rodgers, Patrick",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "-112",
        "p2": "+164"
      },
      "pointsbet": {
        "p1": "-120",
        "p2": "+120"
      },
      "betcris": {
        "p1": "-152",
        "p2": "+121"
      },
      "betmgm": {
        "p1": "-143",
        "p2": "+115"
      },
      "caesars": {
        "p1": "-140",
        "p2": "+110"
      },
      "draftkings": {
        "p1": "-142",
        "p2": "+114"
      },
      "fanduel": {
        "p1": "-138",
        "p2": "+110"
      },
      "unibet": {
        "p1": "-162",
        "p2": "+128"
      }
    }
  },
  {
    "p1_player_name": "Cauley, Bud",
    "p2_player_name": "Yellamaraju, Sudarshan",
    "odds": {
      "betonline": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-112",
        "p2": "+112"
      }
    }
  },
  {
    "p1_player_name": "Cole, Eric",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-106",
        "p2": "+106"
      }
    }
  },
  {
    "p1_player_name": "Cole, Eric",
    "p2_player_name": "Higgo, Garrick",
    "odds": {
      "datagolf": {
        "p1": "-143",
        "p2": "+143"
      },
      "pinnacle": {
        "p1": "-148",
        "p2": "+127"
      }
    }
  },
  {
    "p1_player_name": "Cole, Eric",
    "p2_player_name": "Novak, Andrew",
    "odds": {
      "datagolf": {
        "p1": "-105",
        "p2": "+105"
      },
      "fanduel": {
        "p1": "-111",
        "p2": "-111"
      }
    }
  },
  {
    "p1_player_name": "Conners, Corey",
    "p2_player_name": "Meissner, Mac",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Day, Jason",
    "p2_player_name": "Spieth, Jordan",
    "odds": {
      "bet365": {
        "p1": "+145",
        "p2": "-130"
      },
      "datagolf": {
        "p1": "+167",
        "p2": "-113"
      },
      "pointsbet": {
        "p1": "+135",
        "p2": "-125"
      },
      "betmgm": {
        "p1": "+110",
        "p2": "-139"
      },
      "bovada": {
        "p1": "+125",
        "p2": "-150"
      },
      "caesars": {
        "p1": "+120",
        "p2": "-150"
      },
      "draftkings": {
        "p1": "+108",
        "p2": "-136"
      },
      "pinnacle": {
        "p1": "+127",
        "p2": "-152"
      },
      "unibet": {
        "p1": "+120",
        "p2": "-152"
      }
    }
  },
  {
    "p1_player_name": "Day, Jason",
    "p2_player_name": "Stevens, Sam",
    "odds": {
      "betcris": {
        "p1": "-115",
        "p2": "-115"
      },
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+103",
        "p2": "-103"
      }
    }
  },
  {
    "p1_player_name": "Eckroat, Austin",
    "p2_player_name": "Fisk, Steven",
    "odds": {
      "betcris": {
        "p1": "+100",
        "p2": "-130"
      },
      "datagolf": {
        "p1": "+104",
        "p2": "-104"
      }
    }
  },
  {
    "p1_player_name": "English, Harris",
    "p2_player_name": "Gotterup, Chris",
    "odds": {
      "betonline": {
        "p1": "+100",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "+109",
        "p2": "-109"
      }
    }
  },
  {
    "p1_player_name": "English, Harris",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "betcris": {
        "p1": "-101",
        "p2": "-129"
      },
      "datagolf": {
        "p1": "+122",
        "p2": "-122"
      }
    }
  },
  {
    "p1_player_name": "English, Harris",
    "p2_player_name": "MacIntyre, Robert",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+137",
        "p2": "+110"
      },
      "pointsbet": {
        "p1": "+105",
        "p2": "+100"
      },
      "betmgm": {
        "p1": "-105",
        "p2": "-118"
      },
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "bovada": {
        "p1": "+105",
        "p2": "-125"
      },
      "caesars": {
        "p1": "-110",
        "p2": "-120"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-122"
      },
      "unibet": {
        "p1": "-122",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "English, Harris",
    "p2_player_name": "McNealy, Maverick",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "bovada": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+103"
      }
    }
  },
  {
    "p1_player_name": "Finau, Tony",
    "p2_player_name": "Fitzpatrick, Alex",
    "odds": {
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+100",
        "p2": "-100"
      }
    }
  },
  {
    "p1_player_name": "Finau, Tony",
    "p2_player_name": "Hall, Harry",
    "odds": {
      "bet365": {
        "p1": "+125",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+121",
        "p2": "+122"
      },
      "pointsbet": {
        "p1": "-105",
        "p2": "+105"
      },
      "betcris": {
        "p1": "-128",
        "p2": "-102"
      },
      "caesars": {
        "p1": "-125",
        "p2": "-105"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-122"
      },
      "fanduel": {
        "p1": "-120",
        "p2": "-110"
      },
      "pinnacle": {
        "p1": "-110",
        "p2": "-110"
      },
      "unibet": {
        "p1": "-117",
        "p2": "-109"
      }
    }
  },
  {
    "p1_player_name": "Finau, Tony",
    "p2_player_name": "Pendrith, Taylor",
    "odds": {
      "caesars": {
        "p1": "-125",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-102",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "Fitzpatrick, Alex",
    "p2_player_name": "Bridgeman, Jacob",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "+115",
        "p2": "+129"
      },
      "pointsbet": {
        "p1": "-105",
        "p2": "+105"
      },
      "betmgm": {
        "p1": "-105",
        "p2": "-118"
      },
      "betonline": {
        "p1": "-118",
        "p2": "-102"
      },
      "bovada": {
        "p1": "-110",
        "p2": "-110"
      },
      "caesars": {
        "p1": "-125",
        "p2": "-105"
      },
      "draftkings": {
        "p1": "-115",
        "p2": "-108"
      },
      "unibet": {
        "p1": "-117",
        "p2": "-109"
      }
    }
  },
  {
    "p1_player_name": "Fitzpatrick, Alex",
    "p2_player_name": "Hall, Harry",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "-101",
        "p2": "+101"
      }
    }
  },
  {
    "p1_player_name": "Fitzpatrick, Matt",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-117",
        "p2": "+117"
      }
    }
  },
  {
    "p1_player_name": "Fitzpatrick, Matt",
    "p2_player_name": "Schauffele, Xander",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "-110",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Fitzpatrick, Matt",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-100",
        "p2": "+100"
      },
      "draftkings": {
        "p1": "-104",
        "p2": "-126"
      }
    }
  },
  {
    "p1_player_name": "Fleetwood, Tommy",
    "p2_player_name": "Burns, Sam",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "+109",
        "p2": "+133"
      },
      "pointsbet": {
        "p1": "-120",
        "p2": "+120"
      },
      "betcris": {
        "p1": "-139",
        "p2": "+109"
      },
      "betonline": {
        "p1": "-128",
        "p2": "+107"
      },
      "caesars": {
        "p1": "-140",
        "p2": "+110"
      },
      "draftkings": {
        "p1": "-134",
        "p2": "+108"
      },
      "fanduel": {
        "p1": "-138",
        "p2": "+110"
      },
      "pinnacle": {
        "p1": "-128",
        "p2": "+106"
      },
      "unibet": {
        "p1": "-129",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "Fleetwood, Tommy",
    "p2_player_name": "Cantlay, Patrick",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-101",
        "p2": "+101"
      },
      "draftkings": {
        "p1": "-114",
        "p2": "-115"
      }
    }
  },
  {
    "p1_player_name": "Fleetwood, Tommy",
    "p2_player_name": "Spaun, J.J.",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-102",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "Fleetwood, Tommy",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+129",
        "p2": "+114"
      },
      "betmgm": {
        "p1": "+110",
        "p2": "-139"
      },
      "betonline": {
        "p1": "+105",
        "p2": "-125"
      },
      "bovada": {
        "p1": "-105",
        "p2": "-115"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "+110",
        "p2": "-138"
      },
      "pinnacle": {
        "p1": "-106",
        "p2": "-112"
      },
      "unibet": {
        "p1": "-105",
        "p2": "-122"
      }
    }
  },
  {
    "p1_player_name": "Fowler, Rickie",
    "p2_player_name": "Lowry, Shane",
    "odds": {
      "betcris": {
        "p1": "+104",
        "p2": "-134"
      },
      "datagolf": {
        "p1": "+106",
        "p2": "-106"
      }
    }
  },
  {
    "p1_player_name": "Fox, Ryan",
    "p2_player_name": "Berger, Daniel",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "+149",
        "p2": "+100"
      },
      "pointsbet": {
        "p1": "+115",
        "p2": "-115"
      },
      "betmgm": {
        "p1": "+100",
        "p2": "-122"
      },
      "bovada": {
        "p1": "+100",
        "p2": "-120"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "+102",
        "p2": "-130"
      },
      "pinnacle": {
        "p1": "+103",
        "p2": "-123"
      },
      "unibet": {
        "p1": "+102",
        "p2": "-129"
      }
    }
  },
  {
    "p1_player_name": "Fox, Ryan",
    "p2_player_name": "English, Harris",
    "odds": {
      "bet365": {
        "p1": "+130",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "+166",
        "p2": "-112"
      },
      "pointsbet": {
        "p1": "+125",
        "p2": "-125"
      },
      "betcris": {
        "p1": "+131",
        "p2": "-164"
      },
      "betmgm": {
        "p1": "+125",
        "p2": "-159"
      },
      "caesars": {
        "p1": "+115",
        "p2": "-145"
      },
      "draftkings": {
        "p1": "+128",
        "p2": "-160"
      },
      "fanduel": {
        "p1": "+110",
        "p2": "-138"
      },
      "unibet": {
        "p1": "+128",
        "p2": "-162"
      }
    }
  },
  {
    "p1_player_name": "Fox, Ryan",
    "p2_player_name": "Hisatsune, Ryo",
    "odds": {
      "betonline": {
        "p1": "+121",
        "p2": "-145"
      },
      "datagolf": {
        "p1": "+142",
        "p2": "-142"
      }
    }
  },
  {
    "p1_player_name": "Garnett, Brice",
    "p2_player_name": "Brennan, Michael",
    "odds": {
      "datagolf": {
        "p1": "+118",
        "p2": "-118"
      },
      "unibet": {
        "p1": "+130",
        "p2": "-167"
      }
    }
  },
  {
    "p1_player_name": "Garnett, Brice",
    "p2_player_name": "Ewart, A.J.",
    "odds": {
      "bet365": {
        "p1": "+115",
        "p2": "-135"
      },
      "betcris": {
        "p1": "-109",
        "p2": "-119"
      },
      "datagolf": {
        "p1": "+104",
        "p2": "-104"
      },
      "pinnacle": {
        "p1": "-103",
        "p2": "-112"
      },
      "bovada": {
        "p1": "+115",
        "p2": "-135"
      }
    }
  },
  {
    "p1_player_name": "Ghim, Doug",
    "p2_player_name": "Meissner, Mac",
    "odds": {
      "betcris": {
        "p1": "-115",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+107",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Glover, Lucas",
    "p2_player_name": "Hoge, Tom",
    "odds": {
      "betcris": {
        "p1": "-127",
        "p2": "-103"
      },
      "datagolf": {
        "p1": "-105",
        "p2": "+105"
      }
    }
  },
  {
    "p1_player_name": "Glover, Lucas",
    "p2_player_name": "McCarty, Matt",
    "odds": {
      "bet365": {
        "p1": "+115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "+134",
        "p2": "+112"
      },
      "pointsbet": {
        "p1": "+120",
        "p2": "-115"
      },
      "betmgm": {
        "p1": "+100",
        "p2": "-125"
      },
      "bovada": {
        "p1": "+105",
        "p2": "-125"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "+100",
        "p2": "-125"
      }
    }
  },
  {
    "p1_player_name": "Glover, Lucas",
    "p2_player_name": "Meissner, Mac",
    "odds": {
      "bet365": {
        "p1": "+145",
        "p2": "-134"
      },
      "datagolf": {
        "p1": "+170",
        "p2": "-113"
      },
      "pointsbet": {
        "p1": "+150",
        "p2": "-140"
      },
      "betmgm": {
        "p1": "+130",
        "p2": "-161"
      },
      "caesars": {
        "p1": "+135",
        "p2": "-175"
      },
      "fanduel": {
        "p1": "+125",
        "p2": "-163"
      },
      "unibet": {
        "p1": "+128",
        "p2": "-162"
      }
    }
  },
  {
    "p1_player_name": "Glover, Lucas",
    "p2_player_name": "Snedeker, Brandt",
    "odds": {
      "betcris": {
        "p1": "-124",
        "p2": "-103"
      },
      "datagolf": {
        "p1": "+102",
        "p2": "-102"
      }
    }
  },
  {
    "p1_player_name": "Griffin, Ben",
    "p2_player_name": "Thompson, Davis",
    "odds": {
      "betcris": {
        "p1": "-133",
        "p2": "+103"
      },
      "datagolf": {
        "p1": "-125",
        "p2": "+125"
      }
    }
  },
  {
    "p1_player_name": "Grillo, Emiliano",
    "p2_player_name": "Moore, Taylor",
    "odds": {
      "betonline": {
        "p1": "-102",
        "p2": "-118"
      },
      "datagolf": {
        "p1": "+107",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Grillo, Emiliano",
    "p2_player_name": "Poston, J.T.",
    "odds": {
      "betcris": {
        "p1": "+101",
        "p2": "-131"
      },
      "datagolf": {
        "p1": "+118",
        "p2": "-118"
      }
    }
  },
  {
    "p1_player_name": "Hall, Harry",
    "p2_player_name": "Bridgeman, Jacob",
    "odds": {
      "betcris": {
        "p1": "-127",
        "p2": "-103"
      },
      "datagolf": {
        "p1": "-110",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Gerard, Ryan",
    "odds": {
      "betcris": {
        "p1": "-130",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-109",
        "p2": "+109"
      },
      "draftkings": {
        "p1": "-116",
        "p2": "-114"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "bet365": {
        "p1": "+160",
        "p2": "-143"
      },
      "datagolf": {
        "p1": "+158",
        "p2": "-105"
      },
      "pointsbet": {
        "p1": "+135",
        "p2": "-135"
      },
      "betmgm": {
        "p1": "+140",
        "p2": "-175"
      },
      "bovada": {
        "p1": "+130",
        "p2": "-155"
      },
      "caesars": {
        "p1": "+127",
        "p2": "-165"
      },
      "draftkings": {
        "p1": "+128",
        "p2": "-160"
      },
      "unibet": {
        "p1": "+128",
        "p2": "-162"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Hall, Harry",
    "odds": {
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+106",
        "p2": "-106"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Reitan, Kristoffer",
    "odds": {
      "betcris": {
        "p1": "-126",
        "p2": "-104"
      },
      "datagolf": {
        "p1": "-111",
        "p2": "+111"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Smith, Jordan",
    "odds": {
      "datagolf": {
        "p1": "-123",
        "p2": "+123"
      },
      "pinnacle": {
        "p1": "-131",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Thorbjornsen, Michael",
    "odds": {
      "betonline": {
        "p1": "-122",
        "p2": "+109"
      },
      "datagolf": {
        "p1": "-115",
        "p2": "+115"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "-125"
      },
      "betonline": {
        "p1": "+109",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+108",
        "p2": "-105"
      },
      "bovada": {
        "p1": "+105",
        "p2": "-125"
      },
      "draftkings": {
        "p1": "-110",
        "p2": "-118"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Cantlay, Patrick",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-125",
        "p2": "+125"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Echavarria, Nico",
    "odds": {
      "bet365": {
        "p1": "-143",
        "p2": "+160"
      },
      "datagolf": {
        "p1": "-167",
        "p2": "+252"
      },
      "pointsbet": {
        "p1": "-220",
        "p2": "+200"
      },
      "betmgm": {
        "p1": "-250",
        "p2": "+195"
      },
      "caesars": {
        "p1": "-260",
        "p2": "+200"
      },
      "draftkings": {
        "p1": "-255",
        "p2": "+200"
      },
      "fanduel": {
        "p1": "-250",
        "p2": "+188"
      },
      "unibet": {
        "p1": "-265",
        "p2": "+205"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Fitzpatrick, Matt",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "+113",
        "p2": "+134"
      },
      "pointsbet": {
        "p1": "-105",
        "p2": "+110"
      },
      "betmgm": {
        "p1": "-111",
        "p2": "-111"
      },
      "betonline": {
        "p1": "-115",
        "p2": "-105"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      },
      "caesars": {
        "p1": "-125",
        "p2": "-105"
      },
      "draftkings": {
        "p1": "-110",
        "p2": "-114"
      },
      "pinnacle": {
        "p1": "-118",
        "p2": "+100"
      },
      "unibet": {
        "p1": "-129",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Kim, Si Woo",
    "odds": {
      "betcris": {
        "p1": "-125",
        "p2": "-105"
      },
      "betonline": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-106",
        "p2": "+106"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Scheffler, Scottie",
    "odds": {
      "betcris": {
        "p1": "+150",
        "p2": "-190"
      },
      "datagolf": {
        "p1": "+160",
        "p2": "-160"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Smalley, Alex",
    "odds": {
      "betcris": {
        "p1": "-145",
        "p2": "+115"
      },
      "datagolf": {
        "p1": "-129",
        "p2": "+129"
      },
      "unibet": {
        "p1": "-143",
        "p2": "+112"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "bet365": {
        "p1": "+100",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "-101",
        "p2": "+101"
      }
    }
  },
  {
    "p1_player_name": "Higgo, Garrick",
    "p2_player_name": "Castillo, Ricky",
    "odds": {
      "betcris": {
        "p1": "-108",
        "p2": "-122"
      },
      "datagolf": {
        "p1": "+123",
        "p2": "-123"
      }
    }
  },
  {
    "p1_player_name": "Hisatsune, Ryo",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "betcris": {
        "p1": "+118",
        "p2": "-148"
      },
      "datagolf": {
        "p1": "+139",
        "p2": "-139"
      }
    }
  },
  {
    "p1_player_name": "Hisatsune, Ryo",
    "p2_player_name": "Meissner, Mac",
    "odds": {
      "datagolf": {
        "p1": "-112",
        "p2": "+112"
      },
      "pinnacle": {
        "p1": "-117",
        "p2": "-101"
      },
      "unibet": {
        "p1": "-120",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Hisatsune, Ryo",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "bet365": {
        "p1": "+175",
        "p2": "-160"
      },
      "datagolf": {
        "p1": "+184",
        "p2": "-123"
      },
      "pointsbet": {
        "p1": "+155",
        "p2": "-160"
      },
      "betcris": {
        "p1": "+118",
        "p2": "-148"
      },
      "betmgm": {
        "p1": "+160",
        "p2": "-200"
      },
      "caesars": {
        "p1": "+150",
        "p2": "-190"
      },
      "draftkings": {
        "p1": "+160",
        "p2": "-200"
      },
      "fanduel": {
        "p1": "+150",
        "p2": "-188"
      },
      "unibet": {
        "p1": "+140",
        "p2": "-180"
      }
    }
  },
  {
    "p1_player_name": "Hodges, Lee",
    "p2_player_name": "McCarty, Matt",
    "odds": {
      "betcris": {
        "p1": "-102",
        "p2": "-125"
      },
      "betonline": {
        "p1": "+107",
        "p2": "-128"
      },
      "datagolf": {
        "p1": "+127",
        "p2": "-127"
      },
      "unibet": {
        "p1": "+112",
        "p2": "-143"
      }
    }
  },
  {
    "p1_player_name": "Hoey, Rico",
    "p2_player_name": "Fisk, Steven",
    "odds": {
      "betonline": {
        "p1": "-105",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-100",
        "p2": "+100"
      }
    }
  },
  {
    "p1_player_name": "Hoge, Tom",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "bet365": {
        "p1": "+200",
        "p2": "-180"
      },
      "datagolf": {
        "p1": "+274",
        "p2": "-184"
      },
      "pointsbet": {
        "p1": "+210",
        "p2": "-230"
      },
      "betmgm": {
        "p1": "+240",
        "p2": "-312"
      },
      "caesars": {
        "p1": "+210",
        "p2": "-280"
      },
      "draftkings": {
        "p1": "+235",
        "p2": "-295"
      },
      "fanduel": {
        "p1": "+200",
        "p2": "-300"
      },
      "unibet": {
        "p1": "+210",
        "p2": "-278"
      }
    }
  },
  {
    "p1_player_name": "Hoge, Tom",
    "p2_player_name": "Cole, Eric",
    "odds": {
      "betcris": {
        "p1": "-108",
        "p2": "-119"
      },
      "datagolf": {
        "p1": "+124",
        "p2": "-124"
      },
      "unibet": {
        "p1": "+104",
        "p2": "-132"
      }
    }
  },
  {
    "p1_player_name": "Hoge, Tom",
    "p2_player_name": "Higgo, Garrick",
    "odds": {
      "betonline": {
        "p1": "-130",
        "p2": "+115"
      },
      "datagolf": {
        "p1": "-115",
        "p2": "+115"
      }
    }
  },
  {
    "p1_player_name": "Hoge, Tom",
    "p2_player_name": "Yu, Kevin",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-109",
        "p2": "+109"
      },
      "bovada": {
        "p1": "-115",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Homa, Max",
    "p2_player_name": "McGreevy, Max",
    "odds": {
      "betcris": {
        "p1": "-109",
        "p2": "-121"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Homa, Max",
    "p2_player_name": "Theegala, Sahith",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+115",
        "p2": "-115"
      },
      "bovada": {
        "p1": "-115",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Horschel, Billy",
    "p2_player_name": "Clanton, Luke",
    "odds": {
      "betcris": {
        "p1": "-146",
        "p2": "+121"
      },
      "datagolf": {
        "p1": "-124",
        "p2": "+124"
      }
    }
  },
  {
    "p1_player_name": "Horschel, Billy",
    "p2_player_name": "Fox, Ryan",
    "odds": {
      "betcris": {
        "p1": "+102",
        "p2": "-132"
      },
      "betonline": {
        "p1": "+110",
        "p2": "-131"
      },
      "datagolf": {
        "p1": "+116",
        "p2": "-116"
      }
    }
  },
  {
    "p1_player_name": "Horschel, Billy",
    "p2_player_name": "Stevens, Sam",
    "odds": {
      "bet365": {
        "p1": "+150",
        "p2": "-143"
      },
      "datagolf": {
        "p1": "+167",
        "p2": "-112"
      },
      "pointsbet": {
        "p1": "+120",
        "p2": "-115"
      },
      "betmgm": {
        "p1": "+115",
        "p2": "-143"
      },
      "bovada": {
        "p1": "+115",
        "p2": "-140"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "+110",
        "p2": "-140"
      },
      "unibet": {
        "p1": "+102",
        "p2": "-129"
      }
    }
  },
  {
    "p1_player_name": "Hubbard, Mark",
    "p2_player_name": "Gerard, Ryan",
    "odds": {
      "bet365": {
        "p1": "+162",
        "p2": "-150"
      },
      "datagolf": {
        "p1": "+202",
        "p2": "-136"
      },
      "caesars": {
        "p1": "+150",
        "p2": "-190"
      },
      "unibet": {
        "p1": "+150",
        "p2": "-186"
      }
    }
  },
  {
    "p1_player_name": "Hubbard, Mark",
    "p2_player_name": "Hoey, Rico",
    "odds": {
      "betcris": {
        "p1": "-109",
        "p2": "-121"
      },
      "datagolf": {
        "p1": "+110",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Hubbard, Mark",
    "p2_player_name": "Homa, Max",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+106",
        "p2": "-106"
      }
    }
  },
  {
    "p1_player_name": "Hubbard, Mark",
    "p2_player_name": "Van Rooyen, Erik",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-138",
        "p2": "+138"
      },
      "bovada": {
        "p1": "-130",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Hughes, Mackenzie",
    "p2_player_name": "Brennan, Michael",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+106",
        "p2": "-106"
      },
      "bovada": {
        "p1": "+105",
        "p2": "-125"
      }
    }
  },
  {
    "p1_player_name": "Hughes, Mackenzie",
    "p2_player_name": "Ewart, A.J.",
    "odds": {
      "betonline": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-110",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Hughes, Mackenzie",
    "p2_player_name": "Ghim, Doug",
    "odds": {
      "datagolf": {
        "p1": "+129",
        "p2": "-129"
      },
      "draftkings": {
        "p1": "-106",
        "p2": "-124"
      },
      "pinnacle": {
        "p1": "+117",
        "p2": "-140"
      }
    }
  },
  {
    "p1_player_name": "Im, Sungjae",
    "p2_player_name": "Novak, Andrew",
    "odds": {
      "betcris": {
        "p1": "-114",
        "p2": "-116"
      },
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Im, Sungjae",
    "p2_player_name": "Theegala, Sahith",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+103"
      }
    }
  },
  {
    "p1_player_name": "Kim, Michael",
    "p2_player_name": "Echavarria, Nico",
    "odds": {
      "betonline": {
        "p1": "-130",
        "p2": "+109"
      },
      "datagolf": {
        "p1": "-129",
        "p2": "+129"
      }
    }
  },
  {
    "p1_player_name": "Kim, Michael",
    "p2_player_name": "Gotterup, Chris",
    "odds": {
      "bet365": {
        "p1": "+140",
        "p2": "-130"
      },
      "datagolf": {
        "p1": "+135",
        "p2": "+109"
      },
      "pointsbet": {
        "p1": "+135",
        "p2": "-135"
      },
      "betcris": {
        "p1": "-102",
        "p2": "-128"
      },
      "betmgm": {
        "p1": "+115",
        "p2": "-143"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "+114",
        "p2": "-144"
      },
      "fanduel": {
        "p1": "+100",
        "p2": "-125"
      },
      "unibet": {
        "p1": "+102",
        "p2": "-129"
      }
    }
  },
  {
    "p1_player_name": "Kim, Michael",
    "p2_player_name": "Hoey, Rico",
    "odds": {
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      },
      "fanduel": {
        "p1": "-111",
        "p2": "-111"
      }
    }
  },
  {
    "p1_player_name": "Kim, Michael",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "bet365": {
        "p1": "+137",
        "p2": "-130"
      },
      "datagolf": {
        "p1": "+143",
        "p2": "+103"
      },
      "betmgm": {
        "p1": "+125",
        "p2": "-154"
      },
      "bovada": {
        "p1": "+125",
        "p2": "-150"
      },
      "caesars": {
        "p1": "+127",
        "p2": "-165"
      },
      "draftkings": {
        "p1": "+125",
        "p2": "-156"
      },
      "unibet": {
        "p1": "+120",
        "p2": "-152"
      }
    }
  },
  {
    "p1_player_name": "Kim, Michael",
    "p2_player_name": "McGreevy, Max",
    "odds": {
      "betonline": {
        "p1": "+100",
        "p2": "-118"
      },
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      }
    }
  },
  {
    "p1_player_name": "Kim, Michael",
    "p2_player_name": "Theegala, Sahith",
    "odds": {
      "betcris": {
        "p1": "-110",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "+110",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Kim, Si Woo",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+114",
        "p2": "-114"
      }
    }
  },
  {
    "p1_player_name": "Kim, Si Woo",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "betonline": {
        "p1": "-160",
        "p2": "+133"
      },
      "datagolf": {
        "p1": "-133",
        "p2": "+133"
      }
    }
  },
  {
    "p1_player_name": "Kim, Si Woo",
    "p2_player_name": "MacIntyre, Robert",
    "odds": {
      "betcris": {
        "p1": "-182",
        "p2": "+144"
      },
      "datagolf": {
        "p1": "-145",
        "p2": "+145"
      }
    }
  },
  {
    "p1_player_name": "Kim, Si Woo",
    "p2_player_name": "McCarthy, Denny",
    "odds": {
      "bet365": {
        "p1": "-160",
        "p2": "+180"
      },
      "datagolf": {
        "p1": "-153",
        "p2": "+230"
      },
      "pointsbet": {
        "p1": "-175",
        "p2": "+175"
      },
      "betmgm": {
        "p1": "-200",
        "p2": "+160"
      },
      "caesars": {
        "p1": "-210",
        "p2": "+165"
      },
      "draftkings": {
        "p1": "-215",
        "p2": "+170"
      },
      "fanduel": {
        "p1": "-200",
        "p2": "+162"
      },
      "unibet": {
        "p1": "-230",
        "p2": "+175"
      }
    }
  },
  {
    "p1_player_name": "Kim, Si Woo",
    "p2_player_name": "Theegala, Sahith",
    "odds": {
      "bet365": {
        "p1": "-150",
        "p2": "+160"
      },
      "datagolf": {
        "p1": "-139",
        "p2": "+207"
      },
      "pointsbet": {
        "p1": "-150",
        "p2": "+155"
      },
      "betmgm": {
        "p1": "-175",
        "p2": "+140"
      },
      "bovada": {
        "p1": "-170",
        "p2": "+140"
      },
      "caesars": {
        "p1": "-190",
        "p2": "+150"
      },
      "draftkings": {
        "p1": "-174",
        "p2": "+140"
      },
      "pinnacle": {
        "p1": "-199",
        "p2": "+162"
      },
      "unibet": {
        "p1": "-180",
        "p2": "+140"
      }
    }
  },
  {
    "p1_player_name": "Kim, Tom",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "datagolf": {
        "p1": "+132",
        "p2": "-132"
      },
      "unibet": {
        "p1": "+112",
        "p2": "-143"
      }
    }
  },
  {
    "p1_player_name": "Kim, Tom",
    "p2_player_name": "Thompson, Davis",
    "odds": {
      "datagolf": {
        "p1": "+106",
        "p2": "-106"
      },
      "draftkings": {
        "p1": "-112",
        "p2": "-118"
      }
    }
  },
  {
    "p1_player_name": "Kuchar, Matt",
    "p2_player_name": "Cauley, Bud",
    "odds": {
      "bet365": {
        "p1": "+137",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+168",
        "p2": "-112"
      },
      "betmgm": {
        "p1": "+115",
        "p2": "-143"
      },
      "bovada": {
        "p1": "+115",
        "p2": "-135"
      },
      "caesars": {
        "p1": "+110",
        "p2": "-140"
      },
      "draftkings": {
        "p1": "+116",
        "p2": "-146"
      },
      "unibet": {
        "p1": "+116",
        "p2": "-148"
      }
    }
  },
  {
    "p1_player_name": "Kuchar, Matt",
    "p2_player_name": "Dahmen, Joel",
    "odds": {
      "betcris": {
        "p1": "-132",
        "p2": "+102"
      },
      "betonline": {
        "p1": "-130",
        "p2": "+109"
      },
      "datagolf": {
        "p1": "-114",
        "p2": "+114"
      }
    }
  },
  {
    "p1_player_name": "Kuchar, Matt",
    "p2_player_name": "Kim, Michael",
    "odds": {
      "betcris": {
        "p1": "+114",
        "p2": "-144"
      },
      "datagolf": {
        "p1": "+124",
        "p2": "-124"
      }
    }
  },
  {
    "p1_player_name": "Kuchar, Matt",
    "p2_player_name": "Taylor, Nick",
    "odds": {
      "bet365": {
        "p1": "+150",
        "p2": "-130"
      },
      "datagolf": {
        "p1": "+157",
        "p2": "-104"
      },
      "pointsbet": {
        "p1": "+140",
        "p2": "-135"
      },
      "betcris": {
        "p1": "+121",
        "p2": "-152"
      },
      "betmgm": {
        "p1": "+130",
        "p2": "-161"
      },
      "caesars": {
        "p1": "+127",
        "p2": "-165"
      },
      "draftkings": {
        "p1": "+130",
        "p2": "-162"
      },
      "fanduel": {
        "p1": "+125",
        "p2": "-150"
      },
      "unibet": {
        "p1": "+120",
        "p2": "-152"
      }
    }
  },
  {
    "p1_player_name": "Lee, Min Woo",
    "p2_player_name": "Meissner, Mac",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+130"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+151"
      },
      "pointsbet": {
        "p1": "-120",
        "p2": "+125"
      },
      "betmgm": {
        "p1": "-143",
        "p2": "+115"
      },
      "bovada": {
        "p1": "-130",
        "p2": "+110"
      },
      "caesars": {
        "p1": "-140",
        "p2": "+110"
      },
      "draftkings": {
        "p1": "-148",
        "p2": "+118"
      },
      "unibet": {
        "p1": "-139",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Lee, Min Woo",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "betcris": {
        "p1": "-125",
        "p2": "-104"
      },
      "bovada": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-110",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Lowry, Shane",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "betonline": {
        "p1": "-125",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "-101",
        "p2": "+108"
      },
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Lowry, Shane",
    "p2_player_name": "Im, Sungjae",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "+108",
        "p2": "+138"
      },
      "pointsbet": {
        "p1": "-115",
        "p2": "+120"
      },
      "betmgm": {
        "p1": "-130",
        "p2": "+105"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      },
      "caesars": {
        "p1": "-135",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-132",
        "p2": "+105"
      },
      "pinnacle": {
        "p1": "-132",
        "p2": "+110"
      },
      "unibet": {
        "p1": "-148",
        "p2": "+116"
      }
    }
  },
  {
    "p1_player_name": "Lowry, Shane",
    "p2_player_name": "Pendrith, Taylor",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "+125"
      },
      "datagolf": {
        "p1": "+103",
        "p2": "+144"
      },
      "pointsbet": {
        "p1": "-115",
        "p2": "+120"
      },
      "betcris": {
        "p1": "-135",
        "p2": "+105"
      },
      "caesars": {
        "p1": "-135",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-134",
        "p2": "+106"
      },
      "fanduel": {
        "p1": "-138",
        "p2": "+110"
      },
      "pinnacle": {
        "p1": "-133",
        "p2": "+110"
      },
      "unibet": {
        "p1": "-139",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Lowry, Shane",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+108",
        "p2": "-108"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-128"
      }
    }
  },
  {
    "p1_player_name": "MacIntyre, Robert",
    "p2_player_name": "Thompson, Davis",
    "odds": {
      "datagolf": {
        "p1": "-109",
        "p2": "+109"
      },
      "pinnacle": {
        "p1": "-122",
        "p2": "+111"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Gotterup, Chris",
    "odds": {
      "datagolf": {
        "p1": "-113",
        "p2": "+113"
      },
      "draftkings": {
        "p1": "-118",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Henley, Russell",
    "odds": {
      "datagolf": {
        "p1": "+128",
        "p2": "-128"
      },
      "draftkings": {
        "p1": "+104",
        "p2": "-136"
      },
      "pinnacle": {
        "p1": "+115",
        "p2": "-137"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Lowry, Shane",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-118",
        "p2": "+118"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Novak, Andrew",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+130"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+153"
      },
      "pointsbet": {
        "p1": "-130",
        "p2": "+135"
      },
      "betmgm": {
        "p1": "-167",
        "p2": "+135"
      },
      "bovada": {
        "p1": "-150",
        "p2": "+125"
      },
      "caesars": {
        "p1": "-155",
        "p2": "+122"
      },
      "draftkings": {
        "p1": "-164",
        "p2": "+132"
      },
      "pinnacle": {
        "p1": "-143",
        "p2": "+120"
      },
      "unibet": {
        "p1": "-162",
        "p2": "+128"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Scheffler, Scottie",
    "odds": {
      "bet365": {
        "p1": "+210",
        "p2": "-190"
      },
      "datagolf": {
        "p1": "+226",
        "p2": "-153"
      },
      "pointsbet": {
        "p1": "+210",
        "p2": "-220"
      },
      "betmgm": {
        "p1": "+195",
        "p2": "-250"
      },
      "caesars": {
        "p1": "+210",
        "p2": "-280"
      },
      "draftkings": {
        "p1": "+194",
        "p2": "-245"
      },
      "fanduel": {
        "p1": "+200",
        "p2": "-250"
      },
      "pinnacle": {
        "p1": "+165",
        "p2": "-208"
      },
      "unibet": {
        "p1": "+175",
        "p2": "-230"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Smalley, Alex",
    "odds": {
      "betonline": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-100",
        "p2": "+100"
      },
      "fanduel": {
        "p1": "-120",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Spaun, J.J.",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "betcris": {
        "p1": "-110",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+112",
        "p2": "-106"
      },
      "unibet": {
        "p1": "-114",
        "p2": "-114"
      },
      "bovada": {
        "p1": "-110",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "McCarthy, Denny",
    "p2_player_name": "Echavarria, Nico",
    "odds": {
      "betcris": {
        "p1": "-130",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-106",
        "p2": "+106"
      }
    }
  },
  {
    "p1_player_name": "McCarthy, Denny",
    "p2_player_name": "Fitzpatrick, Alex",
    "odds": {
      "betcris": {
        "p1": "+106",
        "p2": "-136"
      },
      "datagolf": {
        "p1": "+125",
        "p2": "-125"
      }
    }
  },
  {
    "p1_player_name": "McCarthy, Denny",
    "p2_player_name": "Hall, Harry",
    "odds": {
      "bet365": {
        "p1": "+115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "+151",
        "p2": "-101"
      },
      "pointsbet": {
        "p1": "+125",
        "p2": "-120"
      },
      "betmgm": {
        "p1": "+105",
        "p2": "-130"
      },
      "bovada": {
        "p1": "-105",
        "p2": "-115"
      },
      "caesars": {
        "p1": "+110",
        "p2": "-140"
      },
      "draftkings": {
        "p1": "+100",
        "p2": "-124"
      },
      "unibet": {
        "p1": "+102",
        "p2": "-129"
      }
    }
  },
  {
    "p1_player_name": "McIlroy, Rory",
    "p2_player_name": "Fleetwood, Tommy",
    "odds": {
      "betcris": {
        "p1": "-134",
        "p2": "+104"
      },
      "datagolf": {
        "p1": "-114",
        "p2": "+114"
      }
    }
  },
  {
    "p1_player_name": "McIlroy, Rory",
    "p2_player_name": "Scheffler, Scottie",
    "odds": {
      "bet365": {
        "p1": "+140",
        "p2": "-165"
      },
      "betcris": {
        "p1": "+135",
        "p2": "-170"
      },
      "betonline": {
        "p1": "+137",
        "p2": "-165"
      },
      "datagolf": {
        "p1": "+139",
        "p2": "-139"
      },
      "draftkings": {
        "p1": "+134",
        "p2": "-174"
      }
    }
  },
  {
    "p1_player_name": "McIlroy, Rory",
    "p2_player_name": "Thomas, Justin",
    "odds": {
      "bet365": {
        "p1": "-138",
        "p2": "+150"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+151"
      },
      "betmgm": {
        "p1": "-169",
        "p2": "+135"
      },
      "betonline": {
        "p1": "-155",
        "p2": "+129"
      },
      "bovada": {
        "p1": "-150",
        "p2": "+125"
      },
      "caesars": {
        "p1": "-165",
        "p2": "+127"
      },
      "draftkings": {
        "p1": "-168",
        "p2": "+134"
      },
      "pinnacle": {
        "p1": "-137",
        "p2": "+115"
      },
      "unibet": {
        "p1": "-175",
        "p2": "+135"
      }
    }
  },
  {
    "p1_player_name": "McIlroy, Rory",
    "p2_player_name": "Woodland, Gary",
    "odds": {
      "bet365": {
        "p1": "-163",
        "p2": "+180"
      },
      "datagolf": {
        "p1": "-118",
        "p2": "+174"
      },
      "pointsbet": {
        "p1": "-160",
        "p2": "+160"
      },
      "betmgm": {
        "p1": "-200",
        "p2": "+160"
      },
      "caesars": {
        "p1": "-190",
        "p2": "+150"
      },
      "draftkings": {
        "p1": "-192",
        "p2": "+152"
      },
      "fanduel": {
        "p1": "-188",
        "p2": "+138"
      },
      "unibet": {
        "p1": "-175",
        "p2": "+135"
      }
    }
  },
  {
    "p1_player_name": "McIlroy, Rory",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-107",
        "p2": "+107"
      },
      "draftkings": {
        "p1": "-125",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "McNealy, Maverick",
    "p2_player_name": "Reitan, Kristoffer",
    "odds": {
      "bet365": {
        "p1": "-125",
        "p2": "+137"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "+141"
      },
      "pointsbet": {
        "p1": "-115",
        "p2": "+120"
      },
      "betonline": {
        "p1": "-135",
        "p2": "+113"
      },
      "bovada": {
        "p1": "-135",
        "p2": "+115"
      },
      "caesars": {
        "p1": "-145",
        "p2": "+115"
      },
      "draftkings": {
        "p1": "-130",
        "p2": "+105"
      },
      "unibet": {
        "p1": "-139",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Meissner, Mac",
    "p2_player_name": "Brennan, Michael",
    "odds": {
      "betonline": {
        "p1": "-135",
        "p2": "+113"
      },
      "datagolf": {
        "p1": "-130",
        "p2": "+130"
      }
    }
  },
  {
    "p1_player_name": "Meissner, Mac",
    "p2_player_name": "McCarty, Matt",
    "odds": {
      "betcris": {
        "p1": "-147",
        "p2": "+117"
      },
      "betonline": {
        "p1": "-135",
        "p2": "+113"
      },
      "datagolf": {
        "p1": "-120",
        "p2": "+120"
      }
    }
  },
  {
    "p1_player_name": "Neergaard-Petersen, Rasmus",
    "p2_player_name": "Castillo, Ricky",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+107",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Neergaard-Petersen, Rasmus",
    "p2_player_name": "McCarty, Matt",
    "odds": {
      "datagolf": {
        "p1": "+117",
        "p2": "-117"
      },
      "pinnacle": {
        "p1": "+102",
        "p2": "-120"
      }
    }
  },
  {
    "p1_player_name": "Noren, Alex",
    "p2_player_name": "Hoge, Tom",
    "odds": {
      "caesars": {
        "p1": "-190",
        "p2": "+150"
      },
      "datagolf": {
        "p1": "-190",
        "p2": "+190"
      }
    }
  },
  {
    "p1_player_name": "Noren, Alex",
    "p2_player_name": "Taylor, Nick",
    "odds": {
      "betonline": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-108",
        "p2": "+108"
      }
    }
  },
  {
    "p1_player_name": "Noren, Alex",
    "p2_player_name": "Theegala, Sahith",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "+103",
        "p2": "+144"
      },
      "pointsbet": {
        "p1": "-115",
        "p2": "+115"
      },
      "betcris": {
        "p1": "-132",
        "p2": "+102"
      },
      "betmgm": {
        "p1": "-118",
        "p2": "-105"
      },
      "caesars": {
        "p1": "-135",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-122",
        "p2": "-104"
      },
      "fanduel": {
        "p1": "-125",
        "p2": "+100"
      },
      "pinnacle": {
        "p1": "-131",
        "p2": "+108"
      },
      "unibet": {
        "p1": "-139",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Novak, Andrew",
    "p2_player_name": "Brennan, Michael",
    "odds": {
      "datagolf": {
        "p1": "-124",
        "p2": "+124"
      },
      "pinnacle": {
        "p1": "-130",
        "p2": "+113"
      }
    }
  },
  {
    "p1_player_name": "Novak, Andrew",
    "p2_player_name": "Castillo, Ricky",
    "odds": {
      "datagolf": {
        "p1": "-112",
        "p2": "+112"
      },
      "unibet": {
        "p1": "-132",
        "p2": "+104"
      }
    }
  },
  {
    "p1_player_name": "Novak, Andrew",
    "p2_player_name": "Ghim, Doug",
    "odds": {
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "-102",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "Novak, Andrew",
    "p2_player_name": "Neergaard-Petersen, Rasmus",
    "odds": {
      "bet365": {
        "p1": "-125",
        "p2": "+105"
      },
      "betcris": {
        "p1": "-125",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-119",
        "p2": "+119"
      },
      "bovada": {
        "p1": "-125",
        "p2": "+105"
      }
    }
  },
  {
    "p1_player_name": "Olesen, Thorbjorn",
    "p2_player_name": "Bezuidenhout, Christiaan",
    "odds": {
      "betcris": {
        "p1": "+128",
        "p2": "-157"
      },
      "datagolf": {
        "p1": "+128",
        "p2": "-128"
      },
      "unibet": {
        "p1": "+104",
        "p2": "-132"
      }
    }
  },
  {
    "p1_player_name": "Olesen, Thorbjorn",
    "p2_player_name": "Cole, Eric",
    "odds": {
      "betonline": {
        "p1": "+105",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+109",
        "p2": "-109"
      }
    }
  },
  {
    "p1_player_name": "Olesen, Thorbjorn",
    "p2_player_name": "Moore, Taylor",
    "odds": {
      "datagolf": {
        "p1": "-101",
        "p2": "+101"
      },
      "fanduel": {
        "p1": "-125",
        "p2": "+100"
      }
    }
  },
  {
    "p1_player_name": "Pendrith, Taylor",
    "p2_player_name": "Hall, Harry",
    "odds": {
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+109",
        "p2": "-109"
      }
    }
  },
  {
    "p1_player_name": "Pendrith, Taylor",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "bet365": {
        "p1": "+115",
        "p2": "-135"
      },
      "datagolf": {
        "p1": "+131",
        "p2": "-131"
      }
    }
  },
  {
    "p1_player_name": "Poston, J.T.",
    "p2_player_name": "Bhatia, Akshay",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "bovada": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Poston, J.T.",
    "p2_player_name": "Cole, Eric",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+103"
      }
    }
  },
  {
    "p1_player_name": "Poston, J.T.",
    "p2_player_name": "Gerard, Ryan",
    "odds": {
      "datagolf": {
        "p1": "+123",
        "p2": "+120"
      },
      "pointsbet": {
        "p1": "+110",
        "p2": "-110"
      },
      "betcris": {
        "p1": "-108",
        "p2": "-122"
      },
      "betonline": {
        "p1": "+105",
        "p2": "-125"
      },
      "caesars": {
        "p1": "-110",
        "p2": "-145"
      },
      "draftkings": {
        "p1": "-104",
        "p2": "-120"
      },
      "fanduel": {
        "p1": "+100",
        "p2": "-125"
      },
      "pinnacle": {
        "p1": "-105",
        "p2": "-115"
      },
      "unibet": {
        "p1": "-109",
        "p2": "-117"
      }
    }
  },
  {
    "p1_player_name": "Poston, J.T.",
    "p2_player_name": "Hisatsune, Ryo",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "+126",
        "p2": "+118"
      },
      "pointsbet": {
        "p1": "+110",
        "p2": "-105"
      },
      "betcris": {
        "p1": "-111",
        "p2": "-119"
      },
      "betmgm": {
        "p1": "-105",
        "p2": "-118"
      },
      "betonline": {
        "p1": "-104",
        "p2": "-116"
      },
      "bovada": {
        "p1": "-115",
        "p2": "-105"
      },
      "caesars": {
        "p1": "-105",
        "p2": "-125"
      },
      "draftkings": {
        "p1": "-108",
        "p2": "-116"
      },
      "pinnacle": {
        "p1": "-103",
        "p2": "-115"
      },
      "unibet": {
        "p1": "-109",
        "p2": "-117"
      }
    }
  },
  {
    "p1_player_name": "Poston, J.T.",
    "p2_player_name": "Kim, Tom",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-105",
        "p2": "+105"
      }
    }
  },
  {
    "p1_player_name": "Putnam, Andrew",
    "p2_player_name": "Castillo, Ricky",
    "odds": {
      "datagolf": {
        "p1": "-112",
        "p2": "+112"
      },
      "pinnacle": {
        "p1": "-127",
        "p2": "+107"
      }
    }
  },
  {
    "p1_player_name": "Putnam, Andrew",
    "p2_player_name": "Meissner, Mac",
    "odds": {
      "bet365": {
        "p1": "+100",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "+106",
        "p2": "-106"
      },
      "bovada": {
        "p1": "+100",
        "p2": "-120"
      }
    }
  },
  {
    "p1_player_name": "Putnam, Andrew",
    "p2_player_name": "Novak, Andrew",
    "odds": {
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      },
      "draftkings": {
        "p1": "-122",
        "p2": "-108"
      }
    }
  },
  {
    "p1_player_name": "Rai, Aaron",
    "p2_player_name": "Fitzpatrick, Alex",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "+125"
      },
      "datagolf": {
        "p1": "+102",
        "p2": "+147"
      },
      "pointsbet": {
        "p1": "-120",
        "p2": "+125"
      },
      "betcris": {
        "p1": "-132",
        "p2": "+102"
      },
      "caesars": {
        "p1": "-145",
        "p2": "+115"
      },
      "draftkings": {
        "p1": "-142",
        "p2": "+114"
      },
      "fanduel": {
        "p1": "-138",
        "p2": "+110"
      },
      "pinnacle": {
        "p1": "-135",
        "p2": "+111"
      },
      "unibet": {
        "p1": "-139",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Reitan, Kristoffer",
    "p2_player_name": "Bridgeman, Jacob",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+127",
        "p2": "+115"
      },
      "pointsbet": {
        "p1": "+105",
        "p2": "-105"
      },
      "betcris": {
        "p1": "-111",
        "p2": "-119"
      },
      "betmgm": {
        "p1": "-111",
        "p2": "-111"
      },
      "betonline": {
        "p1": "-113",
        "p2": "-107"
      },
      "caesars": {
        "p1": "-105",
        "p2": "-125"
      },
      "draftkings": {
        "p1": "-114",
        "p2": "-110"
      },
      "fanduel": {
        "p1": "-110",
        "p2": "-120"
      },
      "pinnacle": {
        "p1": "+101",
        "p2": "-122"
      },
      "unibet": {
        "p1": "-105",
        "p2": "-122"
      }
    }
  },
  {
    "p1_player_name": "Rodgers, Patrick",
    "p2_player_name": "Eckroat, Austin",
    "odds": {
      "datagolf": {
        "p1": "-102",
        "p2": "+102"
      },
      "fanduel": {
        "p1": "-110",
        "p2": "-120"
      }
    }
  },
  {
    "p1_player_name": "Rodgers, Patrick",
    "p2_player_name": "Hojgaard, Nicolai",
    "odds": {
      "caesars": {
        "p1": "+140",
        "p2": "-180"
      },
      "datagolf": {
        "p1": "+140",
        "p2": "-140"
      }
    }
  },
  {
    "p1_player_name": "Rodgers, Patrick",
    "p2_player_name": "McCarthy, Denny",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+110",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Rodgers, Patrick",
    "p2_player_name": "Stevens, Sam",
    "odds": {
      "betcris": {
        "p1": "-106",
        "p2": "-124"
      },
      "datagolf": {
        "p1": "+111",
        "p2": "-111"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Burns, Sam",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "bovada": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+103",
        "p2": "-103"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "betcris": {
        "p1": "-116",
        "p2": "-114"
      },
      "datagolf": {
        "p1": "-108",
        "p2": "+108"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Fleetwood, Tommy",
    "odds": {
      "datagolf": {
        "p1": "+127",
        "p2": "-127"
      },
      "draftkings": {
        "p1": "+100",
        "p2": "-130"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Fowler, Rickie",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+130"
      },
      "datagolf": {
        "p1": "+110",
        "p2": "+135"
      },
      "betmgm": {
        "p1": "-105",
        "p2": "-118"
      },
      "betonline": {
        "p1": "-125",
        "p2": "+105"
      },
      "bovada": {
        "p1": "-130",
        "p2": "+110"
      },
      "caesars": {
        "p1": "-135",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-132",
        "p2": "+106"
      },
      "unibet": {
        "p1": "-122",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Im, Sungjae",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "+140"
      },
      "pointsbet": {
        "p1": "-120",
        "p2": "+120"
      },
      "betcris": {
        "p1": "-117",
        "p2": "-113"
      },
      "betmgm": {
        "p1": "-154",
        "p2": "+125"
      },
      "caesars": {
        "p1": "-140",
        "p2": "+110"
      },
      "draftkings": {
        "p1": "-148",
        "p2": "+118"
      },
      "fanduel": {
        "p1": "-138",
        "p2": "+110"
      },
      "unibet": {
        "p1": "-129",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Matsuyama, Hideki",
    "odds": {
      "bet365": {
        "p1": "+100",
        "p2": "-120"
      },
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+104",
        "p2": "-104"
      },
      "draftkings": {
        "p1": "-114",
        "p2": "-116"
      }
    }
  },
  {
    "p1_player_name": "Saddier, Adrien",
    "p2_player_name": "Blanchet, Chandler",
    "odds": {
      "betcris": {
        "p1": "-102",
        "p2": "-128"
      },
      "datagolf": {
        "p1": "+103",
        "p2": "-103"
      }
    }
  },
  {
    "p1_player_name": "Saddier, Adrien",
    "p2_player_name": "Thompson, Davis",
    "odds": {
      "datagolf": {
        "p1": "+132",
        "p2": "-132"
      },
      "unibet": {
        "p1": "+112",
        "p2": "-143"
      }
    }
  },
  {
    "p1_player_name": "Saddier, Adrien",
    "p2_player_name": "Yu, Kevin",
    "odds": {
      "datagolf": {
        "p1": "-102",
        "p2": "+102"
      },
      "fanduel": {
        "p1": "-125",
        "p2": "+100"
      }
    }
  },
  {
    "p1_player_name": "Schauffele, Xander",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "bet365": {
        "p1": "+115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "+139",
        "p2": "+106"
      },
      "pointsbet": {
        "p1": "+115",
        "p2": "-110"
      },
      "betcris": {
        "p1": "+100",
        "p2": "-130"
      },
      "betmgm": {
        "p1": "-105",
        "p2": "-118"
      },
      "bovada": {
        "p1": "-110",
        "p2": "-110"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "-110",
        "p2": "-114"
      },
      "pinnacle": {
        "p1": "-103",
        "p2": "-116"
      },
      "unibet": {
        "p1": "-109",
        "p2": "-117"
      }
    }
  },
  {
    "p1_player_name": "Schauffele, Xander",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "bet365": {
        "p1": "-140",
        "p2": "+160"
      },
      "datagolf": {
        "p1": "-124",
        "p2": "+181"
      },
      "pointsbet": {
        "p1": "-135",
        "p2": "+140"
      },
      "betcris": {
        "p1": "-170",
        "p2": "+135"
      },
      "caesars": {
        "p1": "-165",
        "p2": "+127"
      },
      "draftkings": {
        "p1": "-170",
        "p2": "+136"
      },
      "fanduel": {
        "p1": "-163",
        "p2": "+125"
      },
      "pinnacle": {
        "p1": "-167",
        "p2": "+136"
      },
      "unibet": {
        "p1": "-180",
        "p2": "+140"
      }
    }
  },
  {
    "p1_player_name": "Scheffler, Scottie",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "betonline": {
        "p1": "-165",
        "p2": "+137"
      },
      "datagolf": {
        "p1": "-148",
        "p2": "+148"
      }
    }
  },
  {
    "p1_player_name": "Scheffler, Scottie",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "bet365": {
        "p1": "-225",
        "p2": "+250"
      },
      "datagolf": {
        "p1": "-191",
        "p2": "+293"
      },
      "pointsbet": {
        "p1": "-240",
        "p2": "+240"
      },
      "betmgm": {
        "p1": "-303",
        "p2": "+235"
      },
      "bovada": {
        "p1": "-270",
        "p2": "+220"
      },
      "caesars": {
        "p1": "-320",
        "p2": "+240"
      },
      "draftkings": {
        "p1": "-310",
        "p2": "+240"
      },
      "pinnacle": {
        "p1": "-277",
        "p2": "+216"
      },
      "unibet": {
        "p1": "-278",
        "p2": "+220"
      }
    }
  },
  {
    "p1_player_name": "Scheffler, Scottie",
    "p2_player_name": "Schauffele, Xander",
    "odds": {
      "datagolf": {
        "p1": "-173",
        "p2": "+173"
      },
      "draftkings": {
        "p1": "-210",
        "p2": "+158"
      }
    }
  },
  {
    "p1_player_name": "Scott, Adam",
    "p2_player_name": "Bradley, Keegan",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "betcris": {
        "p1": "-115",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "-101",
        "p2": "+101"
      }
    }
  },
  {
    "p1_player_name": "Scott, Adam",
    "p2_player_name": "Fitzpatrick, Matt",
    "odds": {
      "bet365": {
        "p1": "+137",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+184",
        "p2": "-124"
      },
      "pointsbet": {
        "p1": "+125",
        "p2": "-120"
      },
      "betcris": {
        "p1": "+115",
        "p2": "-145"
      },
      "betmgm": {
        "p1": "+125",
        "p2": "-154"
      },
      "caesars": {
        "p1": "+127",
        "p2": "-165"
      },
      "draftkings": {
        "p1": "+106",
        "p2": "-150"
      },
      "fanduel": {
        "p1": "+125",
        "p2": "-150"
      },
      "unibet": {
        "p1": "+140",
        "p2": "-180"
      }
    }
  },
  {
    "p1_player_name": "Scott, Adam",
    "p2_player_name": "Im, Sungjae",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-107",
        "p2": "+107"
      }
    }
  },
  {
    "p1_player_name": "Scott, Adam",
    "p2_player_name": "Matsuyama, Hideki",
    "odds": {
      "betonline": {
        "p1": "+100",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "+118",
        "p2": "-118"
      }
    }
  },
  {
    "p1_player_name": "Scott, Adam",
    "p2_player_name": "Smalley, Alex",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "+115"
      },
      "datagolf": {
        "p1": "+114",
        "p2": "+131"
      },
      "pointsbet": {
        "p1": "-110",
        "p2": "+115"
      },
      "betmgm": {
        "p1": "-130",
        "p2": "+105"
      },
      "bovada": {
        "p1": "-125",
        "p2": "+105"
      },
      "caesars": {
        "p1": "-135",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-130",
        "p2": "+104"
      }
    }
  },
  {
    "p1_player_name": "Scott, Adam",
    "p2_player_name": "Spieth, Jordan",
    "odds": {
      "datagolf": {
        "p1": "+119",
        "p2": "-119"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-128"
      }
    }
  },
  {
    "p1_player_name": "Scott, Adam",
    "p2_player_name": "Woodland, Gary",
    "odds": {
      "betonline": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Smalley, Alex",
    "p2_player_name": "Bhatia, Akshay",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-114",
        "p2": "+114"
      },
      "bovada": {
        "p1": "-115",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Smith, Jordan",
    "p2_player_name": "Gerard, Ryan",
    "odds": {
      "betonline": {
        "p1": "+113",
        "p2": "-123"
      },
      "datagolf": {
        "p1": "+111",
        "p2": "-111"
      }
    }
  },
  {
    "p1_player_name": "Smith, Jordan",
    "p2_player_name": "Hisatsune, Ryo",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+130",
        "p2": "-130"
      },
      "bovada": {
        "p1": "+105",
        "p2": "-125"
      }
    }
  },
  {
    "p1_player_name": "Smith, Jordan",
    "p2_player_name": "Thorbjornsen, Michael",
    "odds": {
      "betcris": {
        "p1": "+103",
        "p2": "-133"
      },
      "datagolf": {
        "p1": "+107",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Smotherman, Austin",
    "p2_player_name": "Kim, Tom",
    "odds": {
      "betcris": {
        "p1": "+117",
        "p2": "-147"
      },
      "datagolf": {
        "p1": "+116",
        "p2": "-116"
      }
    }
  },
  {
    "p1_player_name": "Snedeker, Brandt",
    "p2_player_name": "Cole, Eric",
    "odds": {
      "bet365": {
        "p1": "+160",
        "p2": "-143"
      },
      "datagolf": {
        "p1": "+168",
        "p2": "-112"
      },
      "pointsbet": {
        "p1": "+135",
        "p2": "-125"
      },
      "betcris": {
        "p1": "+125",
        "p2": "-157"
      },
      "betmgm": {
        "p1": "+105",
        "p2": "-133"
      },
      "bovada": {
        "p1": "+140",
        "p2": "-170"
      },
      "caesars": {
        "p1": "+122",
        "p2": "-155"
      },
      "draftkings": {
        "p1": "+112",
        "p2": "-140"
      },
      "unibet": {
        "p1": "+128",
        "p2": "-162"
      }
    }
  },
  {
    "p1_player_name": "Snedeker, Brandt",
    "p2_player_name": "Hoge, Tom",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-107",
        "p2": "+107"
      }
    }
  },
  {
    "p1_player_name": "Snedeker, Brandt",
    "p2_player_name": "Yellamaraju, Sudarshan",
    "odds": {
      "bet365": {
        "p1": "+115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "+141",
        "p2": "+106"
      },
      "pointsbet": {
        "p1": "+135",
        "p2": "-125"
      },
      "betcris": {
        "p1": "-105",
        "p2": "-125"
      },
      "betmgm": {
        "p1": "+115",
        "p2": "-143"
      },
      "caesars": {
        "p1": "+120",
        "p2": "-150"
      },
      "draftkings": {
        "p1": "+112",
        "p2": "-140"
      },
      "fanduel": {
        "p1": "+110",
        "p2": "-150"
      },
      "unibet": {
        "p1": "+110",
        "p2": "-139"
      }
    }
  },
  {
    "p1_player_name": "Spaun, J.J.",
    "p2_player_name": "Bhatia, Akshay",
    "odds": {
      "betonline": {
        "p1": "-130",
        "p2": "+109"
      },
      "datagolf": {
        "p1": "-122",
        "p2": "+122"
      }
    }
  },
  {
    "p1_player_name": "Spaun, J.J.",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "+125"
      },
      "datagolf": {
        "p1": "-105",
        "p2": "+156"
      },
      "betmgm": {
        "p1": "-130",
        "p2": "+105"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      },
      "caesars": {
        "p1": "-140",
        "p2": "+110"
      },
      "draftkings": {
        "p1": "-130",
        "p2": "+104"
      },
      "pinnacle": {
        "p1": "-135",
        "p2": "+113"
      },
      "unibet": {
        "p1": "-136",
        "p2": "+106"
      }
    }
  },
  {
    "p1_player_name": "Spaun, J.J.",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "+115"
      },
      "datagolf": {
        "p1": "-101",
        "p2": "+147"
      },
      "betcris": {
        "p1": "-129",
        "p2": "-101"
      },
      "betmgm": {
        "p1": "-125",
        "p2": "+100"
      },
      "betonline": {
        "p1": "-130",
        "p2": "+109"
      },
      "caesars": {
        "p1": "-140",
        "p2": "+110"
      },
      "draftkings": {
        "p1": "-125",
        "p2": "+100"
      },
      "fanduel": {
        "p1": "-138",
        "p2": "+110"
      },
      "pinnacle": {
        "p1": "-131",
        "p2": "+108"
      },
      "unibet": {
        "p1": "-148",
        "p2": "+116"
      }
    }
  },
  {
    "p1_player_name": "Spaun, J.J.",
    "p2_player_name": "McNealy, Maverick",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-141",
        "p2": "+141"
      },
      "draftkings": {
        "p1": "-132",
        "p2": "+100"
      }
    }
  },
  {
    "p1_player_name": "Spaun, J.J.",
    "p2_player_name": "Smalley, Alex",
    "odds": {
      "datagolf": {
        "p1": "-106",
        "p2": "+106"
      },
      "draftkings": {
        "p1": "-118",
        "p2": "-112"
      },
      "pinnacle": {
        "p1": "-115",
        "p2": "-102"
      }
    }
  },
  {
    "p1_player_name": "Spieth, Jordan",
    "p2_player_name": "Smalley, Alex",
    "odds": {
      "betcris": {
        "p1": "-154",
        "p2": "+123"
      },
      "betonline": {
        "p1": "-144",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "-126",
        "p2": "+126"
      }
    }
  },
  {
    "p1_player_name": "Straka, Sepp",
    "p2_player_name": "Burns, Sam",
    "odds": {
      "betcris": {
        "p1": "+102",
        "p2": "-132"
      },
      "datagolf": {
        "p1": "+102",
        "p2": "-102"
      }
    }
  },
  {
    "p1_player_name": "Straka, Sepp",
    "p2_player_name": "Conners, Corey",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "-100",
        "p2": "+150"
      },
      "pointsbet": {
        "p1": "-125",
        "p2": "+125"
      },
      "betcris": {
        "p1": "-121",
        "p2": "-109"
      },
      "betmgm": {
        "p1": "-137",
        "p2": "+110"
      },
      "caesars": {
        "p1": "-145",
        "p2": "+115"
      },
      "draftkings": {
        "p1": "-134",
        "p2": "+108"
      },
      "fanduel": {
        "p1": "-138",
        "p2": "+110"
      },
      "unibet": {
        "p1": "-139",
        "p2": "+110"
      }
    }
  },
  {
    "p1_player_name": "Straka, Sepp",
    "p2_player_name": "Gotterup, Chris",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "+117",
        "p2": "+126"
      },
      "pointsbet": {
        "p1": "-105",
        "p2": "+105"
      },
      "betmgm": {
        "p1": "-105",
        "p2": "-118"
      },
      "betonline": {
        "p1": "-115",
        "p2": "-105"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      },
      "caesars": {
        "p1": "-125",
        "p2": "-105"
      },
      "draftkings": {
        "p1": "-108",
        "p2": "-116"
      },
      "pinnacle": {
        "p1": "-109",
        "p2": "-109"
      },
      "unibet": {
        "p1": "-114",
        "p2": "-114"
      }
    }
  },
  {
    "p1_player_name": "Taylor, Nick",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "bovada": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-108",
        "p2": "+108"
      }
    }
  },
  {
    "p1_player_name": "Taylor, Nick",
    "p2_player_name": "Conners, Corey",
    "odds": {
      "betcris": {
        "p1": "-119",
        "p2": "-111"
      },
      "datagolf": {
        "p1": "-116",
        "p2": "+116"
      }
    }
  },
  {
    "p1_player_name": "Taylor, Nick",
    "p2_player_name": "Echavarria, Nico",
    "odds": {
      "bet365": {
        "p1": "-150",
        "p2": "+162"
      },
      "datagolf": {
        "p1": "-123",
        "p2": "+183"
      },
      "pointsbet": {
        "p1": "-135",
        "p2": "+135"
      },
      "betmgm": {
        "p1": "-149",
        "p2": "+120"
      },
      "betonline": {
        "p1": "-171",
        "p2": "+142"
      },
      "bovada": {
        "p1": "-170",
        "p2": "+140"
      },
      "caesars": {
        "p1": "-165",
        "p2": "+127"
      },
      "draftkings": {
        "p1": "-160",
        "p2": "+128"
      },
      "unibet": {
        "p1": "-180",
        "p2": "+140"
      }
    }
  },
  {
    "p1_player_name": "Taylor, Nick",
    "p2_player_name": "English, Harris",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+103"
      }
    }
  },
  {
    "p1_player_name": "Theegala, Sahith",
    "p2_player_name": "Gerard, Ryan",
    "odds": {
      "betcris": {
        "p1": "+117",
        "p2": "-147"
      },
      "betonline": {
        "p1": "+117",
        "p2": "-140"
      },
      "datagolf": {
        "p1": "+123",
        "p2": "-123"
      }
    }
  },
  {
    "p1_player_name": "Theegala, Sahith",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "betonline": {
        "p1": "+121",
        "p2": "-145"
      },
      "datagolf": {
        "p1": "+127",
        "p2": "-127"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "betonline": {
        "p1": "+121",
        "p2": "-145"
      },
      "datagolf": {
        "p1": "+127",
        "p2": "-127"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Gotterup, Chris",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "bovada": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-117",
        "p2": "+117"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "datagolf": {
        "p1": "-104",
        "p2": "+104"
      },
      "draftkings": {
        "p1": "-116",
        "p2": "-114"
      },
      "pinnacle": {
        "p1": "-117",
        "p2": "-102"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "MacIntyre, Robert",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "betcris": {
        "p1": "-117",
        "p2": "-110"
      },
      "betonline": {
        "p1": "-123",
        "p2": "+103"
      },
      "datagolf": {
        "p1": "-119",
        "p2": "+119"
      },
      "unibet": {
        "p1": "-120",
        "p2": "-107"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Spaun, J.J.",
    "odds": {
      "datagolf": {
        "p1": "+108",
        "p2": "-108"
      },
      "draftkings": {
        "p1": "-112",
        "p2": "-118"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Straka, Sepp",
    "odds": {
      "datagolf": {
        "p1": "-107",
        "p2": "+107"
      },
      "draftkings": {
        "p1": "-125",
        "p2": "-104"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "betcris": {
        "p1": "+102",
        "p2": "-132"
      },
      "datagolf": {
        "p1": "+118",
        "p2": "-118"
      }
    }
  },
  {
    "p1_player_name": "Thorbjornsen, Michael",
    "p2_player_name": "Gerard, Ryan",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "-105"
      },
      "pinnacle": {
        "p1": "-105",
        "p2": "-112"
      },
      "unibet": {
        "p1": "-114",
        "p2": "-114"
      },
      "bovada": {
        "p1": "-110",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Van Rooyen, Erik",
    "p2_player_name": "Roy, Kevin",
    "odds": {
      "betcris": {
        "p1": "-103",
        "p2": "-127"
      },
      "datagolf": {
        "p1": "+133",
        "p2": "-133"
      }
    }
  },
  {
    "p1_player_name": "Vegas, Jhonattan",
    "p2_player_name": "Yellamaraju, Sudarshan",
    "odds": {
      "caesars": {
        "p1": "+140",
        "p2": "-180"
      },
      "datagolf": {
        "p1": "+168",
        "p2": "-168"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "datagolf": {
        "p1": "+147",
        "p2": "-147"
      },
      "unibet": {
        "p1": "+170",
        "p2": "-220"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Berger, Daniel",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-150",
        "p2": "+150"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Bradley, Keegan",
    "odds": {
      "datagolf": {
        "p1": "-105",
        "p2": "+105"
      },
      "pinnacle": {
        "p1": "-112",
        "p2": "-106"
      },
      "fanduel": {
        "p1": "-111",
        "p2": "-111"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Cantlay, Patrick",
    "odds": {
      "bet365": {
        "p1": "+137",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+146",
        "p2": "+102"
      },
      "pointsbet": {
        "p1": "+125",
        "p2": "-120"
      },
      "betmgm": {
        "p1": "+115",
        "p2": "-143"
      },
      "bovada": {
        "p1": "+120",
        "p2": "-145"
      },
      "caesars": {
        "p1": "+110",
        "p2": "-140"
      },
      "draftkings": {
        "p1": "+118",
        "p2": "-150"
      },
      "pinnacle": {
        "p1": "+120",
        "p2": "-143"
      },
      "unibet": {
        "p1": "+120",
        "p2": "-152"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Ghim, Doug",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-110",
        "p2": "+110"
      },
      "bovada": {
        "p1": "-120",
        "p2": "+100"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Hughes, Mackenzie",
    "odds": {
      "betcris": {
        "p1": "-165",
        "p2": "+134"
      },
      "datagolf": {
        "p1": "-143",
        "p2": "+143"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Matsuyama, Hideki",
    "odds": {
      "betcris": {
        "p1": "+101",
        "p2": "-131"
      },
      "datagolf": {
        "p1": "+107",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "McNealy, Maverick",
    "odds": {
      "betcris": {
        "p1": "-123",
        "p2": "-107"
      },
      "datagolf": {
        "p1": "-104",
        "p2": "+104"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Meissner, Mac",
    "odds": {
      "datagolf": {
        "p1": "-105",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-114",
        "p2": "-116"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Putnam, Andrew",
    "odds": {
      "betonline": {
        "p1": "-125",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "-111",
        "p2": "+111"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-104",
        "p2": "+104"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Reitan, Kristoffer",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "-116",
        "p2": "+116"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Taylor, Nick",
    "odds": {
      "datagolf": {
        "p1": "-106",
        "p2": "+106"
      },
      "draftkings": {
        "p1": "-115",
        "p2": "-114"
      }
    }
  },
  {
    "p1_player_name": "Yu, Kevin",
    "p2_player_name": "Nakajima, Keita",
    "odds": {
      "betcris": {
        "p1": "-113",
        "p2": "-117"
      },
      "betonline": {
        "p1": "-112",
        "p2": "+102"
      },
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      },
      "unibet": {
        "p1": "-132",
        "p2": "+104"
      }
    }
  }
];
