// Generated by scripts/build-outrights.ts on 2026-06-08T10:05:43.617Z
// the-memorial-tournament-2026 / r3 — outright WINNER odds, 53 entries.
// Best odds computed across real sportsbooks (DataGolf excluded). DO NOT EDIT BY HAND.

import type { OutrightEntry } from '../types';

export const r4OutrightsData: OutrightEntry[] = [
  {
    "player_name": "Burns, Sam",
    "dg_id": 19483,
    "bestOdds": "+238",
    "bestBook": "pinnacle",
    "dgOdds": "+323",
    "allBooks": {
      "bet365": "+200",
      "betmgm": "+225",
      "caesars": "+185",
      "draftkings": "+198",
      "fanduel": "+200",
      "pinnacle": "+238",
      "pointsbet": "+230",
      "betonline": "+235",
      "bovada": "+225",
      "unibet": "+225",
      "betcris": "+238"
    }
  },
  {
    "player_name": "Gerard, Ryan",
    "dg_id": 29767,
    "bestOdds": "+350",
    "bestBook": "pointsbet",
    "dgOdds": "+278",
    "allBooks": {
      "bet365": "+280",
      "betmgm": "+300",
      "caesars": "+300",
      "draftkings": "+285",
      "fanduel": "+310",
      "pinnacle": "+284",
      "pointsbet": "+350",
      "betonline": "+315",
      "bovada": "+330",
      "unibet": "+300",
      "betcris": "+328"
    }
  },
  {
    "player_name": "Poston, J.T.",
    "dg_id": 21554,
    "bestOdds": "+350",
    "bestBook": "betonline",
    "dgOdds": "+301",
    "allBooks": {
      "bet365": "+300",
      "betmgm": "+300",
      "caesars": "+300",
      "draftkings": "+265",
      "fanduel": "+300",
      "pinnacle": "+291",
      "pointsbet": "+330",
      "betonline": "+350",
      "bovada": "+330",
      "unibet": "+335",
      "betcris": "+325"
    }
  },
  {
    "player_name": "Fleetwood, Tommy",
    "dg_id": 12294,
    "bestOdds": "+1118",
    "bestBook": "pinnacle",
    "dgOdds": "+1967",
    "allBooks": {
      "bet365": "+900",
      "betmgm": "+900",
      "caesars": "+1000",
      "draftkings": "+1075",
      "fanduel": "+1000",
      "pinnacle": "+1118",
      "pointsbet": "+1050",
      "betonline": "+1100",
      "bovada": "+800",
      "unibet": "+1000",
      "betcris": "+1060"
    }
  },
  {
    "player_name": "Cole, Eric",
    "dg_id": 21756,
    "bestOdds": "+1855",
    "bestBook": "betcris",
    "dgOdds": "+1339",
    "allBooks": {
      "bet365": "+1600",
      "betmgm": "+1600",
      "caesars": "+1800",
      "draftkings": "+1750",
      "fanduel": "+1800",
      "pinnacle": "+1452",
      "pointsbet": "+1800",
      "betonline": "+1500",
      "bovada": "+1800",
      "unibet": "+1600",
      "betcris": "+1855"
    }
  },
  {
    "player_name": "Bradley, Keegan",
    "dg_id": 13872,
    "bestOdds": "+3173",
    "bestBook": "pinnacle",
    "dgOdds": "+4409",
    "allBooks": {
      "bet365": "+2500",
      "betmgm": "+2500",
      "caesars": "+3000",
      "draftkings": "+2800",
      "fanduel": "+3000",
      "pinnacle": "+3173",
      "pointsbet": "+2800",
      "betonline": "+2800",
      "bovada": "+2800",
      "unibet": "+2500",
      "betcris": "+3076"
    }
  },
  {
    "player_name": "Clark, Wyndham",
    "dg_id": 23604,
    "bestOdds": "+3307",
    "bestBook": "pinnacle",
    "dgOdds": "+4726",
    "allBooks": {
      "bet365": "+2500",
      "betmgm": "+2500",
      "caesars": "+3000",
      "draftkings": "+2250",
      "fanduel": "+3000",
      "pinnacle": "+3307",
      "pointsbet": "+2800",
      "betonline": "+2800",
      "bovada": "+2200",
      "unibet": "+2000",
      "betcris": "+3073"
    }
  },
  {
    "player_name": "Spaun, J.J.",
    "dg_id": 17536,
    "bestOdds": "+3579",
    "bestBook": "betcris",
    "dgOdds": "+4597",
    "allBooks": {
      "bet365": "+3000",
      "betmgm": "+3000",
      "caesars": "+3000",
      "draftkings": "+3400",
      "fanduel": "+3300",
      "pinnacle": "+3529",
      "pointsbet": "+3000",
      "betonline": "+3300",
      "bovada": "+2800",
      "unibet": "+2800",
      "betcris": "+3579"
    }
  },
  {
    "player_name": "Schauffele, Xander",
    "dg_id": 19895,
    "bestOdds": "+3631",
    "bestBook": "pinnacle",
    "dgOdds": "+5085",
    "allBooks": {
      "bet365": "+3300",
      "betmgm": "+3300",
      "caesars": "+2800",
      "draftkings": "+2900",
      "fanduel": "+3000",
      "pinnacle": "+3631",
      "pointsbet": "+3000",
      "betonline": "+3300",
      "bovada": "+2800",
      "unibet": "+3300",
      "betcris": "+3380"
    }
  },
  {
    "player_name": "Scheffler, Scottie",
    "dg_id": 18417,
    "bestOdds": "+4228",
    "bestBook": "pinnacle",
    "dgOdds": "+7455",
    "allBooks": {
      "bet365": "+3000",
      "betmgm": "+2800",
      "caesars": "+2800",
      "draftkings": "+4200",
      "fanduel": "+3300",
      "pinnacle": "+4228",
      "pointsbet": "+3000",
      "betonline": "+4000",
      "bovada": "+2200",
      "unibet": "+2800",
      "betcris": "+4086"
    }
  },
  {
    "player_name": "Noren, Alex",
    "dg_id": 10419,
    "bestOdds": "+12500",
    "bestBook": "betonline",
    "dgOdds": "+15067",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+9000",
      "caesars": "+10000",
      "draftkings": "+11000",
      "fanduel": "+10000",
      "pinnacle": "+10939",
      "pointsbet": "+10000",
      "betonline": "+12500",
      "bovada": "+10000",
      "unibet": "+8000",
      "betcris": "+12153"
    }
  },
  {
    "player_name": "McIlroy, Rory",
    "dg_id": 10091,
    "bestOdds": "+14000",
    "bestBook": "draftkings",
    "dgOdds": "+27895",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+8000",
      "caesars": "+10000",
      "draftkings": "+14000",
      "fanduel": "+10000",
      "pinnacle": "+10498",
      "pointsbet": "+12500",
      "betonline": "+12500",
      "bovada": "+8000",
      "unibet": "+8000",
      "betcris": "+12156"
    }
  },
  {
    "player_name": "Rai, Aaron",
    "dg_id": 18554,
    "bestOdds": "+15000",
    "bestBook": "betonline",
    "dgOdds": "+33861",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+9000",
      "caesars": "+10000",
      "draftkings": "+11500",
      "fanduel": "+10000",
      "pinnacle": "+14392",
      "pointsbet": "+10000",
      "betonline": "+15000",
      "bovada": "+10000",
      "unibet": "+8000",
      "betcris": "+14173"
    }
  },
  {
    "player_name": "Rose, Justin",
    "dg_id": 6093,
    "bestOdds": "+17500",
    "bestBook": "pointsbet",
    "dgOdds": "+27521",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+12500",
      "caesars": "+15000",
      "draftkings": "+16500",
      "fanduel": "+15000",
      "pinnacle": "+12788",
      "pointsbet": "+17500",
      "betonline": "+15000",
      "bovada": "+15000",
      "unibet": "+12500",
      "betcris": "+16190"
    }
  },
  {
    "player_name": "Lowry, Shane",
    "dg_id": 13900,
    "bestOdds": "+17500",
    "bestBook": "pointsbet",
    "dgOdds": "+37254",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+12500",
      "caesars": "+15000",
      "draftkings": "+17000",
      "fanduel": "+15000",
      "pinnacle": "+16691",
      "pointsbet": "+17500",
      "betonline": "+5000",
      "bovada": "+15000",
      "unibet": "+12500",
      "betcris": "+3381"
    }
  },
  {
    "player_name": "Kitayama, Kurt",
    "dg_id": 21891,
    "bestOdds": "+20000",
    "bestBook": "betonline",
    "dgOdds": "+28052",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+12500",
      "caesars": "+15000",
      "draftkings": "+17500",
      "fanduel": "+15000",
      "pinnacle": "+15929",
      "pointsbet": "+17500",
      "betonline": "+20000",
      "bovada": "+15000",
      "unibet": "+12500",
      "betcris": "+16190"
    }
  },
  {
    "player_name": "Fitzpatrick, Alex",
    "dg_id": 25362,
    "bestOdds": "+20036",
    "bestBook": "pinnacle",
    "dgOdds": "+48840",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+15000",
      "caesars": "+15000",
      "draftkings": "+17500",
      "fanduel": "+17500",
      "pinnacle": "+20036",
      "pointsbet": "+20000",
      "betonline": "+20000",
      "bovada": "+17500",
      "unibet": "+15000",
      "betcris": "+18208"
    }
  },
  {
    "player_name": "Cantlay, Patrick",
    "dg_id": 15466,
    "bestOdds": "+20157",
    "bestBook": "pinnacle",
    "dgOdds": "+62800",
    "allBooks": {
      "bet365": "+14000",
      "betmgm": "+12500",
      "caesars": "+15000",
      "draftkings": "+15000",
      "fanduel": "+12500",
      "pinnacle": "+20157",
      "pointsbet": "+15000",
      "betonline": "+15000",
      "bovada": "+15000",
      "unibet": "+15000",
      "betcris": "+16191"
    }
  },
  {
    "player_name": "Finau, Tony",
    "dg_id": 11676,
    "bestOdds": "+21000",
    "bestBook": "draftkings",
    "dgOdds": "+37150",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+15000",
      "caesars": "+15000",
      "draftkings": "+21000",
      "fanduel": "+15000",
      "pinnacle": "+18364",
      "pointsbet": "+17500",
      "betonline": "+20000",
      "bovada": "+17500",
      "unibet": "+15000",
      "betcris": "+16191"
    }
  },
  {
    "player_name": "McNealy, Maverick",
    "dg_id": 18634,
    "bestOdds": "+21153",
    "bestBook": "pinnacle",
    "dgOdds": "+47425",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+15000",
      "caesars": "+15000",
      "draftkings": "+17500",
      "fanduel": "+17500",
      "pinnacle": "+21153",
      "pointsbet": "+20000",
      "betonline": "+20000",
      "bovada": "+15000",
      "unibet": "+15000",
      "betcris": "+18208"
    }
  },
  {
    "player_name": "Hall, Harry",
    "dg_id": 27194,
    "bestOdds": "+50000",
    "bestBook": "fanduel",
    "dgOdds": "+86951",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+40000",
      "caesars": "+37500",
      "draftkings": "+46000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "bovada": "+35000",
      "unibet": "+35000",
      "betcris": "+20225"
    }
  },
  {
    "player_name": "Theegala, Sahith",
    "dg_id": 23014,
    "bestOdds": "+110000",
    "bestBook": "draftkings",
    "dgOdds": "+428471",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+47500",
      "draftkings": "+110000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "English, Harris",
    "dg_id": 14577,
    "bestOdds": "+130000",
    "bestBook": "draftkings",
    "dgOdds": "+211914",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+50000",
      "caesars": "+75000",
      "draftkings": "+130000",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "bovada": "+75000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Reitan, Kristoffer",
    "dg_id": 21407,
    "bestOdds": "+160000",
    "bestBook": "draftkings",
    "dgOdds": "+568620",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+50000",
      "caesars": "+75000",
      "draftkings": "+160000",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "bovada": "+100000"
    }
  },
  {
    "player_name": "Kim, Si Woo",
    "dg_id": 14609,
    "bestOdds": "+200000",
    "bestBook": "draftkings",
    "dgOdds": "+242324",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+75000",
      "draftkings": "+200000",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "bovada": "+100000"
    }
  },
  {
    "player_name": "Im, Sungjae",
    "dg_id": 17488,
    "bestOdds": "+200000",
    "bestBook": "draftkings",
    "dgOdds": "+316106",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+75000",
      "caesars": "+75000",
      "draftkings": "+200000",
      "fanduel": "+100000",
      "pointsbet": "+45000"
    }
  },
  {
    "player_name": "Aberg, Ludvig",
    "dg_id": 23950,
    "bestOdds": "+350000",
    "bestBook": "draftkings",
    "dgOdds": "+371993",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+100000",
      "caesars": "+150000",
      "draftkings": "+350000",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "bovada": "+125000"
    }
  },
  {
    "player_name": "Pendrith, Taylor",
    "dg_id": 17780,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+1999900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Fitzpatrick, Matt",
    "dg_id": 17646,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+1999900",
    "allBooks": {
      "bet365": "+250000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Cauley, Bud",
    "dg_id": 14502,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+1999900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Gotterup, Chris",
    "dg_id": 27774,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+2399900",
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+200000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Henley, Russell",
    "dg_id": 14578,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+3199900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Scott, Adam",
    "dg_id": 6430,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": "+11999900",
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Young, Cameron",
    "dg_id": 26651,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Snedeker, Brandt",
    "dg_id": 8820,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Echavarria, Nico",
    "dg_id": 22833,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Bridgeman, Jacob",
    "dg_id": 29433,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Woodland, Gary",
    "dg_id": 12577,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Hisatsune, Ryo",
    "dg_id": 22760,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Yellamaraju, Sudarshan",
    "dg_id": 29925,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "McCarthy, Denny",
    "dg_id": 19870,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Glover, Lucas",
    "dg_id": 7399,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Taylor, Nick",
    "dg_id": 13126,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Thomas, Justin",
    "dg_id": 14139,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Hoge, Tom",
    "dg_id": 15575,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Kuchar, Matt",
    "dg_id": 6169,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Fox, Ryan",
    "dg_id": 11889,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+45000"
    }
  },
  {
    "player_name": "Rodgers, Patrick",
    "dg_id": 16283,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Kim, Michael",
    "dg_id": 17543,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Straka, Sepp",
    "dg_id": 17511,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Conners, Corey",
    "dg_id": 17576,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  },
  {
    "player_name": "Matsuyama, Hideki",
    "dg_id": 13562,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+60000"
    }
  },
  {
    "player_name": "Meissner, Mac",
    "dg_id": 28159,
    "bestOdds": "+500000",
    "bestBook": "bet365",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+500000",
      "caesars": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+40000"
    }
  }
];
