// Generated by scripts/build-outrights.ts on 2026-06-10T23:57:26.751Z
// the-memorial-tournament-2026 / r3 — outright WINNER odds, 147 entries.
// Best odds computed across real sportsbooks (DataGolf excluded). DO NOT EDIT BY HAND.

import type { OutrightEntry } from '../types';

export const r4OutrightsData: OutrightEntry[] = [
  {
    "player_name": "Fleetwood, Tommy",
    "dg_id": 12294,
    "bestOdds": "+1251",
    "bestBook": "pinnacle",
    "dgOdds": "+1270",
    "allBooks": {
      "bet365": "+1100",
      "betmgm": "+1200",
      "caesars": "+1100",
      "draftkings": "+1150",
      "fanduel": "+1200",
      "pinnacle": "+1251",
      "pointsbet": "+1200",
      "betonline": "+1200",
      "bovada": "+1200",
      "unibet": "+1100",
      "betcris": "+1050"
    }
  },
  {
    "player_name": "Fitzpatrick, Matt",
    "dg_id": 17646,
    "bestOdds": "+1600",
    "bestBook": "betonline",
    "dgOdds": "+1605",
    "allBooks": {
      "bet365": "+1400",
      "betmgm": "+1400",
      "caesars": "+1400",
      "draftkings": "+1175",
      "fanduel": "+1500",
      "pinnacle": "+1503",
      "pointsbet": "+1500",
      "betonline": "+1600",
      "bovada": "+1400",
      "unibet": "+1400",
      "betcris": "+1251"
    }
  },
  {
    "player_name": "Burns, Sam",
    "dg_id": 19483,
    "bestOdds": "+1614",
    "bestBook": "pinnacle",
    "dgOdds": "+1997",
    "allBooks": {
      "bet365": "+1400",
      "betmgm": "+1400",
      "caesars": "+1400",
      "draftkings": "+1275",
      "fanduel": "+1500",
      "pinnacle": "+1614",
      "pointsbet": "+1500",
      "betonline": "+1400",
      "bovada": "+1400",
      "unibet": "+1400",
      "betcris": "+1551"
    }
  },
  {
    "player_name": "Clark, Wyndham",
    "dg_id": 23604,
    "bestOdds": "+2300",
    "bestBook": "draftkings",
    "dgOdds": "+2875",
    "allBooks": {
      "bet365": "+1800",
      "betmgm": "+2000",
      "caesars": "+1400",
      "draftkings": "+2300",
      "fanduel": "+1800",
      "pinnacle": "+2030",
      "pointsbet": "+1800",
      "betonline": "+2000",
      "bovada": "+2000",
      "unibet": "+2000",
      "betcris": "+2052"
    }
  },
  {
    "player_name": "Reitan, Kristoffer",
    "dg_id": 21407,
    "bestOdds": "+2800",
    "bestBook": "betmgm",
    "dgOdds": "+2807",
    "allBooks": {
      "bet365": "+2500",
      "betmgm": "+2800",
      "caesars": "+2400",
      "draftkings": "+2500",
      "fanduel": "+2500",
      "pinnacle": "+2489",
      "pointsbet": "+2500",
      "betonline": "+2500",
      "bovada": "+2800",
      "unibet": "+2500",
      "betcris": "+2551"
    }
  },
  {
    "player_name": "Morikawa, Collin",
    "dg_id": 22085,
    "bestOdds": "+2800",
    "bestBook": "bovada",
    "dgOdds": "+3204",
    "allBooks": {
      "bet365": "+2200",
      "betmgm": "+2500",
      "caesars": "+2100",
      "draftkings": "+2350",
      "fanduel": "+2200",
      "pinnacle": "+2429",
      "pointsbet": "+2200",
      "betonline": "+2500",
      "bovada": "+2800",
      "unibet": "+2200",
      "betcris": "+2252"
    }
  },
  {
    "player_name": "Rose, Justin",
    "dg_id": 6093,
    "bestOdds": "+3052",
    "bestBook": "betcris",
    "dgOdds": "+3311",
    "allBooks": {
      "bet365": "+2500",
      "betmgm": "+2800",
      "caesars": "+2500",
      "draftkings": "+2500",
      "fanduel": "+3000",
      "pinnacle": "+2936",
      "pointsbet": "+2800",
      "betonline": "+3000",
      "bovada": "+2800",
      "unibet": "+2800",
      "betcris": "+3052"
    }
  },
  {
    "player_name": "Hojgaard, Nicolai",
    "dg_id": 23602,
    "bestOdds": "+3300",
    "bestBook": "betmgm",
    "dgOdds": "+3358",
    "allBooks": {
      "bet365": "+3000",
      "betmgm": "+3300",
      "caesars": "+2800",
      "draftkings": "+2900",
      "fanduel": "+3300",
      "pinnacle": "+3158",
      "pointsbet": "+3000",
      "betonline": "+3000",
      "bovada": "+3000",
      "unibet": "+2800",
      "betcris": "+3052"
    }
  },
  {
    "player_name": "Koepka, Brooks",
    "dg_id": 16243,
    "bestOdds": "+3550",
    "bestBook": "betcris",
    "dgOdds": "+5900",
    "allBooks": {
      "bet365": "+3300",
      "betmgm": "+3000",
      "caesars": "+2500",
      "draftkings": "+2700",
      "fanduel": "+3000",
      "pinnacle": "+2756",
      "pointsbet": "+2800",
      "betonline": "+3500",
      "bovada": "+3000",
      "unibet": "+3000",
      "betcris": "+3550"
    }
  },
  {
    "player_name": "MacIntyre, Robert",
    "dg_id": 23323,
    "bestOdds": "+3553",
    "bestBook": "betcris",
    "dgOdds": "+3868",
    "allBooks": {
      "bet365": "+2800",
      "betmgm": "+3000",
      "caesars": "+2400",
      "draftkings": "+2450",
      "fanduel": "+2700",
      "pinnacle": "+3282",
      "pointsbet": "+2500",
      "betonline": "+3500",
      "bovada": "+3000",
      "unibet": "+2800",
      "betcris": "+3553"
    }
  },
  {
    "player_name": "Fitzpatrick, Alex",
    "dg_id": 25362,
    "bestOdds": "+3900",
    "bestBook": "draftkings",
    "dgOdds": "+4537",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+3500",
      "caesars": "+3000",
      "draftkings": "+3900",
      "fanduel": "+3500",
      "pinnacle": "+3777",
      "pointsbet": "+3500",
      "betonline": "+3500",
      "bovada": "+3500",
      "unibet": "+3300",
      "betcris": "+3552"
    }
  },
  {
    "player_name": "Hovland, Viktor",
    "dg_id": 18841,
    "bestOdds": "+4000",
    "bestBook": "betonline",
    "dgOdds": "+4955",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+3500",
      "caesars": "+3000",
      "draftkings": "+3100",
      "fanduel": "+3500",
      "pinnacle": "+3924",
      "pointsbet": "+3500",
      "betonline": "+4000",
      "bovada": "+3500",
      "unibet": "+3300",
      "betcris": "+3853"
    }
  },
  {
    "player_name": "Lowry, Shane",
    "dg_id": 13900,
    "bestOdds": "+4000",
    "bestBook": "fanduel",
    "dgOdds": "+5136",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+3500",
      "caesars": "+3500",
      "draftkings": "+3300",
      "fanduel": "+4000",
      "pinnacle": "+3955",
      "pointsbet": "+4000",
      "betonline": "+4000",
      "bovada": "+4000",
      "unibet": "+3300",
      "betcris": "+3552"
    }
  },
  {
    "player_name": "Rai, Aaron",
    "dg_id": 18554,
    "bestOdds": "+4100",
    "bestBook": "draftkings",
    "dgOdds": "+3897",
    "allBooks": {
      "bet365": "+3300",
      "betmgm": "+3500",
      "caesars": "+3000",
      "draftkings": "+4100",
      "fanduel": "+3300",
      "pinnacle": "+3833",
      "pointsbet": "+3000",
      "betonline": "+3500",
      "bovada": "+3500",
      "unibet": "+3300",
      "betcris": "+2851"
    }
  },
  {
    "player_name": "Noren, Alex",
    "dg_id": 10419,
    "bestOdds": "+4253",
    "bestBook": "betcris",
    "dgOdds": "+4354",
    "allBooks": {
      "bet365": "+3300",
      "betmgm": "+3500",
      "caesars": "+3000",
      "draftkings": "+3700",
      "fanduel": "+3500",
      "pinnacle": "+3659",
      "pointsbet": "+3500",
      "betonline": "+4000",
      "bovada": "+4000",
      "unibet": "+4000",
      "betcris": "+4253"
    }
  },
  {
    "player_name": "Bridgeman, Jacob",
    "dg_id": 29433,
    "bestOdds": "+4500",
    "bestBook": "betonline",
    "dgOdds": "+4879",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+3500",
      "caesars": "+4000",
      "draftkings": "+3700",
      "fanduel": "+4000",
      "pinnacle": "+3829",
      "pointsbet": "+4000",
      "betonline": "+4500",
      "bovada": "+4500",
      "unibet": "+3300",
      "betcris": "+3553"
    }
  },
  {
    "player_name": "Taylor, Nick",
    "dg_id": 13126,
    "bestOdds": "+4552",
    "bestBook": "betcris",
    "dgOdds": "+7553",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+4000",
      "caesars": "+3500",
      "draftkings": "+4500",
      "fanduel": "+4000",
      "pinnacle": "+4391",
      "pointsbet": "+4000",
      "betonline": "+4000",
      "bovada": "+3500",
      "unibet": "+3300",
      "betcris": "+4552"
    }
  },
  {
    "player_name": "Cauley, Bud",
    "dg_id": 14502,
    "bestOdds": "+5000",
    "bestBook": "betmgm",
    "dgOdds": "+4639",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+5000",
      "caesars": "+3000",
      "draftkings": "+4600",
      "fanduel": "+4000",
      "pinnacle": "+4576",
      "pointsbet": "+4000",
      "betonline": "+4500",
      "bovada": "+5000",
      "unibet": "+4500",
      "betcris": "+4050"
    }
  },
  {
    "player_name": "Cole, Eric",
    "dg_id": 21756,
    "bestOdds": "+5053",
    "bestBook": "betcris",
    "dgOdds": "+6236",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+4500",
      "caesars": "+3500",
      "draftkings": "+4400",
      "fanduel": "+4000",
      "pinnacle": "+4848",
      "pointsbet": "+4000",
      "betonline": "+4500",
      "bovada": "+4000",
      "unibet": "+4000",
      "betcris": "+5053"
    }
  },
  {
    "player_name": "Brennan, Michael",
    "dg_id": 29197,
    "bestOdds": "+5300",
    "bestBook": "draftkings",
    "dgOdds": "+8199",
    "allBooks": {
      "bet365": "+4500",
      "betmgm": "+4000",
      "caesars": "+4000",
      "draftkings": "+5300",
      "fanduel": "+4500",
      "pinnacle": "+4490",
      "pointsbet": "+4500",
      "betonline": "+4500",
      "bovada": "+4500",
      "unibet": "+4000",
      "betcris": "+5053"
    }
  },
  {
    "player_name": "Thorbjornsen, Michael",
    "dg_id": 26649,
    "bestOdds": "+5500",
    "bestBook": "betonline",
    "dgOdds": "+6852",
    "allBooks": {
      "bet365": "+4500",
      "betmgm": "+4000",
      "caesars": "+3500",
      "draftkings": "+3600",
      "fanduel": "+4000",
      "pinnacle": "+4497",
      "pointsbet": "+4000",
      "betonline": "+5500",
      "bovada": "+4500",
      "unibet": "+4000",
      "betcris": "+3853"
    }
  },
  {
    "player_name": "Mitchell, Keith",
    "dg_id": 17365,
    "bestOdds": "+6000",
    "bestBook": "betonline",
    "dgOdds": "+6303",
    "allBooks": {
      "bet365": "+5500",
      "betmgm": "+4000",
      "caesars": "+5000",
      "draftkings": "+4500",
      "fanduel": "+5000",
      "pinnacle": "+5185",
      "pointsbet": "+5000",
      "betonline": "+6000",
      "bovada": "+5500",
      "unibet": "+4500",
      "betcris": "+5053"
    }
  },
  {
    "player_name": "Hall, Harry",
    "dg_id": 27194,
    "bestOdds": "+6500",
    "bestBook": "betonline",
    "dgOdds": "+6836",
    "allBooks": {
      "bet365": "+5000",
      "betmgm": "+4500",
      "caesars": "+4500",
      "draftkings": "+4200",
      "fanduel": "+4000",
      "pinnacle": "+6038",
      "pointsbet": "+4500",
      "betonline": "+6500",
      "bovada": "+6000",
      "unibet": "+5000",
      "betcris": "+5053"
    }
  },
  {
    "player_name": "Meissner, Mac",
    "dg_id": 28159,
    "bestOdds": "+6855",
    "bestBook": "betcris",
    "dgOdds": "+6934",
    "allBooks": {
      "bet365": "+5000",
      "betmgm": "+5500",
      "caesars": "+5000",
      "draftkings": "+6400",
      "fanduel": "+5500",
      "pinnacle": "+6065",
      "pointsbet": "+5000",
      "betonline": "+6000",
      "bovada": "+6000",
      "unibet": "+4500",
      "betcris": "+6855"
    }
  },
  {
    "player_name": "Greyserman, Max",
    "dg_id": 23465,
    "bestOdds": "+7800",
    "bestBook": "draftkings",
    "dgOdds": "+12246",
    "allBooks": {
      "bet365": "+6600",
      "betmgm": "+6000",
      "caesars": "+6500",
      "draftkings": "+7800",
      "fanduel": "+7000",
      "pinnacle": "+6600",
      "pointsbet": "+7000",
      "betonline": "+6500",
      "bovada": "+7000",
      "unibet": "+6000",
      "betcris": "+7055"
    }
  },
  {
    "player_name": "Finau, Tony",
    "dg_id": 11676,
    "bestOdds": "+7856",
    "bestBook": "betcris",
    "dgOdds": "+7602",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+6000",
      "caesars": "+6500",
      "draftkings": "+7000",
      "fanduel": "+6000",
      "pinnacle": "+6404",
      "pointsbet": "+6000",
      "betonline": "+7000",
      "bovada": "+6000",
      "unibet": "+7000",
      "betcris": "+7856"
    }
  },
  {
    "player_name": "Theegala, Sahith",
    "dg_id": 23014,
    "bestOdds": "+8000",
    "bestBook": "betonline",
    "dgOdds": "+8659",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+5500",
      "caesars": "+6000",
      "draftkings": "+5400",
      "fanduel": "+6000",
      "pinnacle": "+7285",
      "pointsbet": "+6000",
      "betonline": "+8000",
      "bovada": "+6500",
      "unibet": "+6600",
      "betcris": "+6055"
    }
  },
  {
    "player_name": "Smith, Jordan",
    "dg_id": 18586,
    "bestOdds": "+8000",
    "bestBook": "betonline",
    "dgOdds": "+8750",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+7500",
      "caesars": "+7000",
      "draftkings": "+6800",
      "fanduel": "+7000",
      "pinnacle": "+6803",
      "pointsbet": "+7000",
      "betonline": "+8000",
      "bovada": "+7000",
      "unibet": "+7000",
      "betcris": "+7055"
    }
  },
  {
    "player_name": "Fox, Ryan",
    "dg_id": 11889,
    "bestOdds": "+8056",
    "bestBook": "betcris",
    "dgOdds": "+9202",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+5000",
      "caesars": "+5000",
      "draftkings": "+5200",
      "fanduel": "+5000",
      "pinnacle": "+7658",
      "pointsbet": "+5000",
      "betonline": "+8000",
      "bovada": "+6500",
      "unibet": "+6000",
      "betcris": "+8056"
    }
  },
  {
    "player_name": "Thompson, Davis",
    "dg_id": 27364,
    "bestOdds": "+8393",
    "bestBook": "pinnacle",
    "dgOdds": "+9817",
    "allBooks": {
      "bet365": "+7500",
      "betmgm": "+6000",
      "caesars": "+7000",
      "draftkings": "+7200",
      "fanduel": "+8000",
      "pinnacle": "+8393",
      "pointsbet": "+8000",
      "betonline": "+8000",
      "bovada": "+7500",
      "unibet": "+6600",
      "betcris": "+7555"
    }
  },
  {
    "player_name": "Yellamaraju, Sudarshan",
    "dg_id": 29925,
    "bestOdds": "+8713",
    "bestBook": "pinnacle",
    "dgOdds": "+9850",
    "allBooks": {
      "bet365": "+6600",
      "betmgm": "+7500",
      "caesars": "+7000",
      "draftkings": "+6300",
      "fanduel": "+7000",
      "pinnacle": "+8713",
      "pointsbet": "+7000",
      "betonline": "+8000",
      "bovada": "+7000",
      "unibet": "+6600",
      "betcris": "+7555"
    }
  },
  {
    "player_name": "Conners, Corey",
    "dg_id": 17576,
    "bestOdds": "+9000",
    "bestBook": "betonline",
    "dgOdds": "+10408",
    "allBooks": {
      "bet365": "+6600",
      "betmgm": "+6000",
      "caesars": "+5500",
      "draftkings": "+6400",
      "fanduel": "+7000",
      "pinnacle": "+8133",
      "pointsbet": "+7000",
      "betonline": "+9000",
      "bovada": "+7000",
      "unibet": "+7000",
      "betcris": "+8556"
    }
  },
  {
    "player_name": "Pendrith, Taylor",
    "dg_id": 17780,
    "bestOdds": "+9050",
    "bestBook": "betcris",
    "dgOdds": "+10353",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+5500",
      "caesars": "+6500",
      "draftkings": "+6900",
      "fanduel": "+6500",
      "pinnacle": "+7658",
      "pointsbet": "+6600",
      "betonline": "+7500",
      "bovada": "+6500",
      "unibet": "+8000",
      "betcris": "+9050"
    }
  },
  {
    "player_name": "Potgieter, Aldrich",
    "dg_id": 27900,
    "bestOdds": "+9054",
    "bestBook": "betcris",
    "dgOdds": "+13821",
    "allBooks": {
      "bet365": "+7000",
      "betmgm": "+7500",
      "caesars": "+6000",
      "draftkings": "+7600",
      "fanduel": "+7000",
      "pinnacle": "+8240",
      "pointsbet": "+7000",
      "betonline": "+8000",
      "bovada": "+7500",
      "unibet": "+6600",
      "betcris": "+9054"
    }
  },
  {
    "player_name": "Hoey, Rico",
    "dg_id": 23504,
    "bestOdds": "+10050",
    "bestBook": "betcris",
    "dgOdds": "+9688",
    "allBooks": {
      "bet365": "+7500",
      "betmgm": "+7000",
      "caesars": "+7000",
      "draftkings": "+6400",
      "fanduel": "+8000",
      "pinnacle": "+8800",
      "pointsbet": "+8000",
      "betonline": "+9000",
      "bovada": "+10000",
      "unibet": "+8000",
      "betcris": "+10050"
    }
  },
  {
    "player_name": "Keefer, Johnny",
    "dg_id": 32457,
    "bestOdds": "+10058",
    "bestBook": "betcris",
    "dgOdds": "+15773",
    "allBooks": {
      "bet365": "+7000",
      "betmgm": "+7000",
      "caesars": "+7000",
      "draftkings": "+7400",
      "fanduel": "+8000",
      "pinnacle": "+7559",
      "pointsbet": "+8000",
      "betonline": "+8500",
      "bovada": "+7500",
      "unibet": "+6600",
      "betcris": "+10058"
    }
  },
  {
    "player_name": "Ghim, Doug",
    "dg_id": 24550,
    "bestOdds": "+10558",
    "bestBook": "betcris",
    "dgOdds": "+10501",
    "allBooks": {
      "bet365": "+8000",
      "betmgm": "+7500",
      "caesars": "+7000",
      "draftkings": "+8400",
      "fanduel": "+8000",
      "pinnacle": "+9685",
      "pointsbet": "+8000",
      "betonline": "+10000",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+10558"
    }
  },
  {
    "player_name": "Kim, Tom",
    "dg_id": 24766,
    "bestOdds": "+11000",
    "bestBook": "betonline",
    "dgOdds": "+13204",
    "allBooks": {
      "bet365": "+7000",
      "betmgm": "+9000",
      "caesars": "+9000",
      "draftkings": "+10000",
      "fanduel": "+10000",
      "pinnacle": "+10827",
      "pointsbet": "+9000",
      "betonline": "+11000",
      "bovada": "+10000",
      "unibet": "+7000",
      "betcris": "+8056"
    }
  },
  {
    "player_name": "Hughes, Mackenzie",
    "dg_id": 15556,
    "bestOdds": "+11000",
    "bestBook": "draftkings",
    "dgOdds": "+21561",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+7000",
      "caesars": "+5500",
      "draftkings": "+11000",
      "fanduel": "+6500",
      "pinnacle": "+7714",
      "pointsbet": "+6600",
      "betonline": "+9000",
      "bovada": "+7000",
      "unibet": "+7000",
      "betcris": "+8556"
    }
  },
  {
    "player_name": "Fisk, Steven",
    "dg_id": 26657,
    "bestOdds": "+11508",
    "bestBook": "betcris",
    "dgOdds": "+14051",
    "allBooks": {
      "bet365": "+8000",
      "betmgm": "+10000",
      "caesars": "+7000",
      "draftkings": "+8800",
      "fanduel": "+7000",
      "pinnacle": "+9912",
      "pointsbet": "+7000",
      "betonline": "+11000",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+11508"
    }
  },
  {
    "player_name": "Li, Haotong",
    "dg_id": 15310,
    "bestOdds": "+12500",
    "bestBook": "pointsbet",
    "dgOdds": "+18948",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+9000",
      "caesars": "+9000",
      "draftkings": "+10500",
      "fanduel": "+10000",
      "pinnacle": "+11832",
      "pointsbet": "+12500",
      "betonline": "+12500",
      "bovada": "+10000",
      "unibet": "+10000",
      "betcris": "+12058"
    }
  },
  {
    "player_name": "Wallace, Matt",
    "dg_id": 20706,
    "bestOdds": "+12668",
    "bestBook": "pinnacle",
    "dgOdds": "+17092",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+8000",
      "caesars": "+7500",
      "draftkings": "+9800",
      "fanduel": "+10000",
      "pinnacle": "+12668",
      "pointsbet": "+9000",
      "betonline": "+12500",
      "bovada": "+10000",
      "unibet": "+8000",
      "betcris": "+11508"
    }
  },
  {
    "player_name": "Bezuidenhout, Christiaan",
    "dg_id": 18103,
    "bestOdds": "+13060",
    "bestBook": "betcris",
    "dgOdds": "+15444",
    "allBooks": {
      "bet365": "+8000",
      "betmgm": "+8000",
      "caesars": "+7500",
      "draftkings": "+9800",
      "fanduel": "+8000",
      "pinnacle": "+11276",
      "pointsbet": "+8000",
      "betonline": "+12500",
      "bovada": "+8000",
      "unibet": "+9000",
      "betcris": "+13060"
    }
  },
  {
    "player_name": "Putnam, Andrew",
    "dg_id": 14704,
    "bestOdds": "+13060",
    "bestBook": "betcris",
    "dgOdds": "+15857",
    "allBooks": {
      "bet365": "+7500",
      "betmgm": "+7500",
      "caesars": "+7500",
      "draftkings": "+9800",
      "fanduel": "+8000",
      "pinnacle": "+10963",
      "pointsbet": "+8000",
      "betonline": "+11000",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+13060"
    }
  },
  {
    "player_name": "Neergaard-Petersen, Rasmus",
    "dg_id": 23841,
    "bestOdds": "+13500",
    "bestBook": "betonline",
    "dgOdds": "+14358",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+10000",
      "caesars": "+9000",
      "draftkings": "+11500",
      "fanduel": "+10000",
      "pinnacle": "+12679",
      "pointsbet": "+9000",
      "betonline": "+13500",
      "bovada": "+10000",
      "unibet": "+10000",
      "betcris": "+9557"
    }
  },
  {
    "player_name": "Homa, Max",
    "dg_id": 17538,
    "bestOdds": "+13500",
    "bestBook": "betonline",
    "dgOdds": "+15052",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+9000",
      "caesars": "+7000",
      "draftkings": "+8400",
      "fanduel": "+10000",
      "pinnacle": "+12454",
      "pointsbet": "+9000",
      "betonline": "+13500",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+13060"
    }
  },
  {
    "player_name": "Castillo, Ricky",
    "dg_id": 27819,
    "bestOdds": "+13550",
    "bestBook": "betcris",
    "dgOdds": "+13058",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+10000",
      "caesars": "+8000",
      "draftkings": "+10500",
      "fanduel": "+10000",
      "pinnacle": "+11618",
      "pointsbet": "+9000",
      "betonline": "+13500",
      "bovada": "+10000",
      "unibet": "+8000",
      "betcris": "+13550"
    }
  },
  {
    "player_name": "Bauchou, Zach",
    "dg_id": 19846,
    "bestOdds": "+14000",
    "bestBook": "draftkings",
    "dgOdds": "+15206",
    "allBooks": {
      "bet365": "+7000",
      "betmgm": "+8000",
      "caesars": "+9000",
      "draftkings": "+14000",
      "fanduel": "+10000",
      "pinnacle": "+9808",
      "pointsbet": "+9000",
      "betonline": "+8000",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+9557"
    }
  },
  {
    "player_name": "Moore, Taylor",
    "dg_id": 21944,
    "bestOdds": "+14060",
    "bestBook": "betcris",
    "dgOdds": "+13821",
    "allBooks": {
      "bet365": "+11000",
      "betmgm": "+10000",
      "caesars": "+12500",
      "draftkings": "+11500",
      "fanduel": "+10000",
      "pinnacle": "+12421",
      "pointsbet": "+12500",
      "betonline": "+13500",
      "bovada": "+12500",
      "unibet": "+10000",
      "betcris": "+14060"
    }
  },
  {
    "player_name": "McGreevy, Max",
    "dg_id": 23505,
    "bestOdds": "+15000",
    "bestBook": "pointsbet",
    "dgOdds": "+16520",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+10000",
      "caesars": "+12500",
      "draftkings": "+13500",
      "fanduel": "+12500",
      "pinnacle": "+12636",
      "pointsbet": "+15000",
      "betonline": "+13500",
      "bovada": "+12500",
      "unibet": "+12500",
      "betcris": "+10558"
    }
  },
  {
    "player_name": "Smotherman, Austin",
    "dg_id": 22985,
    "bestOdds": "+15000",
    "bestBook": "bet365",
    "dgOdds": "+16707",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+13500",
      "fanduel": "+10000",
      "pinnacle": "+14462",
      "pointsbet": "+12500",
      "betonline": "+12500",
      "bovada": "+12500",
      "unibet": "+12500",
      "betcris": "+13060"
    }
  },
  {
    "player_name": "Schmid, Matti",
    "dg_id": 20722,
    "bestOdds": "+15000",
    "bestBook": "betonline",
    "dgOdds": "+23710",
    "allBooks": {
      "bet365": "+11000",
      "betmgm": "+11000",
      "caesars": "+12500",
      "draftkings": "+14000",
      "fanduel": "+10000",
      "pinnacle": "+14405",
      "pointsbet": "+12500",
      "betonline": "+15000",
      "bovada": "+12500",
      "unibet": "+12500",
      "betcris": "+9557"
    }
  },
  {
    "player_name": "Olesen, Thorbjorn",
    "dg_id": 13412,
    "bestOdds": "+15061",
    "bestBook": "betcris",
    "dgOdds": "+16660",
    "allBooks": {
      "bet365": "+11000",
      "betmgm": "+9000",
      "caesars": "+9000",
      "draftkings": "+10500",
      "fanduel": "+10000",
      "pinnacle": "+14599",
      "pointsbet": "+10000",
      "betonline": "+15000",
      "bovada": "+12500",
      "unibet": "+10000",
      "betcris": "+15061"
    }
  },
  {
    "player_name": "Suber, Jackson",
    "dg_id": 29279,
    "bestOdds": "+16000",
    "bestBook": "draftkings",
    "dgOdds": "+27173",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+10000",
      "caesars": "+9000",
      "draftkings": "+16000",
      "fanduel": "+10000",
      "pinnacle": "+11187",
      "pointsbet": "+9000",
      "betonline": "+11000",
      "bovada": "+15000",
      "unibet": "+10000",
      "betcris": "+11558"
    }
  },
  {
    "player_name": "Jaeger, Stephan",
    "dg_id": 16394,
    "bestOdds": "+17063",
    "bestBook": "betcris",
    "dgOdds": "+17495",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+7500",
      "caesars": "+9000",
      "draftkings": "+9000",
      "fanduel": "+10000",
      "pinnacle": "+12465",
      "pointsbet": "+9000",
      "betonline": "+12500",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+17063"
    }
  },
  {
    "player_name": "James, Ben",
    "dg_id": 29827,
    "bestOdds": "+17500",
    "bestBook": "betonline",
    "dgOdds": "+19381",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+15000",
      "caesars": "+12500",
      "draftkings": "+15000",
      "fanduel": "+12500",
      "pinnacle": "+15627",
      "pointsbet": "+15000",
      "betonline": "+17500",
      "bovada": "+17500",
      "unibet": "+10000",
      "betcris": "+11008"
    }
  },
  {
    "player_name": "Yu, Kevin",
    "dg_id": 17881,
    "bestOdds": "+17500",
    "bestBook": "betonline",
    "dgOdds": "+22456",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+11000",
      "caesars": "+12500",
      "draftkings": "+14000",
      "fanduel": "+10000",
      "pinnacle": "+14073",
      "pointsbet": "+12500",
      "betonline": "+17500",
      "bovada": "+12500",
      "unibet": "+10000",
      "betcris": "+15061"
    }
  },
  {
    "player_name": "Kirk, Chris",
    "dg_id": 12423,
    "bestOdds": "+17500",
    "bestBook": "betonline",
    "dgOdds": "+30988",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+16500",
      "fanduel": "+12500",
      "pinnacle": "+16394",
      "pointsbet": "+15000",
      "betonline": "+17500",
      "bovada": "+12500",
      "unibet": "+12500",
      "betcris": "+16062"
    }
  },
  {
    "player_name": "Eckroat, Austin",
    "dg_id": 26653,
    "bestOdds": "+17962",
    "bestBook": "pinnacle",
    "dgOdds": "+35828",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+12500",
      "caesars": "+17500",
      "draftkings": "+16500",
      "fanduel": "+15000",
      "pinnacle": "+17962",
      "pointsbet": "+17500",
      "betonline": "+17500",
      "bovada": "+15000",
      "unibet": "+12500",
      "betcris": "+17063"
    }
  },
  {
    "player_name": "Mouw, William",
    "dg_id": 29770,
    "bestOdds": "+18291",
    "bestBook": "pinnacle",
    "dgOdds": "+22122",
    "allBooks": {
      "bet365": "+14000",
      "betmgm": "+15000",
      "caesars": "+15000",
      "draftkings": "+17000",
      "fanduel": "+12500",
      "pinnacle": "+18291",
      "pointsbet": "+15000",
      "betonline": "+17500",
      "bovada": "+15000",
      "unibet": "+10000",
      "betcris": "+10058"
    }
  },
  {
    "player_name": "Hodges, Lee",
    "dg_id": 25157,
    "bestOdds": "+18500",
    "bestBook": "betonline",
    "dgOdds": "+27049",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+12500",
      "caesars": "+15000",
      "draftkings": "+17500",
      "fanduel": "+12500",
      "pinnacle": "+15908",
      "pointsbet": "+15000",
      "betonline": "+18500",
      "bovada": "+15000",
      "unibet": "+12500",
      "betcris": "+12560"
    }
  },
  {
    "player_name": "Hossler, Beau",
    "dg_id": 15470,
    "bestOdds": "+18571",
    "bestBook": "pinnacle",
    "dgOdds": "+23156",
    "allBooks": {
      "bet365": "+17000",
      "betmgm": "+11000",
      "caesars": "+17500",
      "draftkings": "+15500",
      "fanduel": "+15000",
      "pinnacle": "+18571",
      "pointsbet": "+17500",
      "betonline": "+18500",
      "bovada": "+15000",
      "unibet": "+10000",
      "betcris": "+12058"
    }
  },
  {
    "player_name": "Ewart, A.J.",
    "dg_id": 21883,
    "bestOdds": "+19500",
    "bestBook": "draftkings",
    "dgOdds": "+44676",
    "allBooks": {
      "bet365": "+11000",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+19500",
      "fanduel": "+12500",
      "pointsbet": "+15000",
      "betonline": "+13500",
      "unibet": "+12500"
    }
  },
  {
    "player_name": "McCarthy, Denny",
    "dg_id": 19870,
    "bestOdds": "+19550",
    "bestBook": "betcris",
    "dgOdds": "+20953",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+10000",
      "caesars": "+15000",
      "draftkings": "+12500",
      "fanduel": "+15000",
      "pinnacle": "+14149",
      "pointsbet": "+17500",
      "betonline": "+13500",
      "bovada": "+12500",
      "unibet": "+12500",
      "betcris": "+19550"
    }
  },
  {
    "player_name": "Higgo, Garrick",
    "dg_id": 24342,
    "bestOdds": "+20000",
    "bestBook": "pointsbet",
    "dgOdds": "+27937",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+15000",
      "caesars": "+17500",
      "draftkings": "+17500",
      "fanduel": "+17500",
      "pinnacle": "+15603",
      "pointsbet": "+20000",
      "betonline": "+17500",
      "bovada": "+17500",
      "unibet": "+12500",
      "betcris": "+13060"
    }
  },
  {
    "player_name": "Svensson, Jesper",
    "dg_id": 26850,
    "bestOdds": "+20000",
    "bestBook": "draftkings",
    "dgOdds": "+35194",
    "allBooks": {
      "bet365": "+16000",
      "betmgm": "+12500",
      "caesars": "+15000",
      "draftkings": "+20000",
      "fanduel": "+17500",
      "pinnacle": "+14381",
      "pointsbet": "+20000",
      "betonline": "+20000",
      "bovada": "+17500",
      "unibet": "+15000",
      "betcris": "+16563"
    }
  },
  {
    "player_name": "Dumont De Chassart, Adrien",
    "dg_id": 22002,
    "bestOdds": "+21015",
    "bestBook": "betcris",
    "dgOdds": "+29312",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+11000",
      "caesars": "+15000",
      "draftkings": "+16000",
      "fanduel": "+15000",
      "pinnacle": "+19484",
      "pointsbet": "+17500",
      "betonline": "+18500",
      "bovada": "+15000",
      "unibet": "+12500",
      "betcris": "+21015"
    }
  },
  {
    "player_name": "Ventura, Kris",
    "dg_id": 15651,
    "bestOdds": "+22500",
    "bestBook": "betonline",
    "dgOdds": "+34784",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+17500",
      "caesars": "+15000",
      "draftkings": "+18500",
      "fanduel": "+15000",
      "pinnacle": "+21000",
      "pointsbet": "+17500",
      "betonline": "+22500",
      "bovada": "+20000",
      "unibet": "+15000",
      "betcris": "+18563"
    }
  },
  {
    "player_name": "Power, Seamus",
    "dg_id": 10104,
    "bestOdds": "+22500",
    "bestBook": "betonline",
    "dgOdds": "+36485",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+12500",
      "caesars": "+15000",
      "draftkings": "+16500",
      "fanduel": "+15000",
      "pinnacle": "+21413",
      "pointsbet": "+17500",
      "betonline": "+22500",
      "bovada": "+20000",
      "unibet": "+15000",
      "betcris": "+20565"
    }
  },
  {
    "player_name": "Ramey, Chad",
    "dg_id": 19840,
    "bestOdds": "+22500",
    "bestBook": "betonline",
    "dgOdds": "+40716",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+15000",
      "caesars": "+17500",
      "draftkings": "+20000",
      "fanduel": "+17500",
      "pointsbet": "+20000",
      "betonline": "+22500",
      "bovada": "+17500",
      "unibet": "+17500",
      "betcris": "+18563"
    }
  },
  {
    "player_name": "Dou, Zecheng",
    "dg_id": 16757,
    "bestOdds": "+25000",
    "bestBook": "betonline",
    "dgOdds": "+28886",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+22500",
      "caesars": "+20000",
      "draftkings": "+22500",
      "fanduel": "+17500",
      "pinnacle": "+20845",
      "pointsbet": "+20000",
      "betonline": "+25000",
      "bovada": "+20000",
      "unibet": "+20000",
      "betcris": "+20565"
    }
  },
  {
    "player_name": "Grillo, Emiliano",
    "dg_id": 12808,
    "bestOdds": "+25000",
    "bestBook": "draftkings",
    "dgOdds": "+37875",
    "allBooks": {
      "bet365": "+16000",
      "betmgm": "+17500",
      "caesars": "+17500",
      "draftkings": "+25000",
      "fanduel": "+15000",
      "pinnacle": "+16285",
      "pointsbet": "+17500",
      "betonline": "+25000",
      "bovada": "+17500",
      "unibet": "+15000",
      "betcris": "+14561"
    }
  },
  {
    "player_name": "Horschel, Billy",
    "dg_id": 11276,
    "bestOdds": "+26298",
    "bestBook": "pinnacle",
    "dgOdds": "+52997",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+15000",
      "caesars": "+20000",
      "draftkings": "+24000",
      "fanduel": "+17500",
      "pinnacle": "+26298",
      "pointsbet": "+20000",
      "betonline": "+25000",
      "bovada": "+25000",
      "unibet": "+12500"
    }
  },
  {
    "player_name": "Nakajima, Keita",
    "dg_id": 21074,
    "bestOdds": "+30000",
    "bestBook": "pointsbet",
    "dgOdds": "+30669",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+17500",
      "caesars": "+20000",
      "draftkings": "+23000",
      "fanduel": "+17500",
      "pinnacle": "+22790",
      "pointsbet": "+30000",
      "betonline": "+25000",
      "bovada": "+20000",
      "unibet": "+15000",
      "betcris": "+15511"
    }
  },
  {
    "player_name": "Blanchet, Chandler",
    "dg_id": 24956,
    "bestOdds": "+30000",
    "bestBook": "betonline",
    "dgOdds": "+31314",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+22500",
      "caesars": "+17500",
      "draftkings": "+25000",
      "fanduel": "+17500",
      "pinnacle": "+24720",
      "pointsbet": "+20000",
      "betonline": "+30000",
      "bovada": "+25000",
      "unibet": "+20000",
      "betcris": "+2057"
    }
  },
  {
    "player_name": "Vegas, Jhonattan",
    "dg_id": 13508,
    "bestOdds": "+30000",
    "bestBook": "pointsbet",
    "dgOdds": "+36045",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+25000",
      "caesars": "+20000",
      "draftkings": "+24000",
      "fanduel": "+22500",
      "pinnacle": "+25875",
      "pointsbet": "+30000",
      "betonline": "+27500",
      "bovada": "+25000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Roy, Kevin",
    "dg_id": 18424,
    "bestOdds": "+30000",
    "bestBook": "pointsbet",
    "dgOdds": "+36045",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+17500",
      "caesars": "+20000",
      "draftkings": "+24000",
      "fanduel": "+17500",
      "pointsbet": "+30000",
      "betonline": "+27500",
      "bovada": "+20000",
      "unibet": "+15000",
      "betcris": "+23067"
    }
  },
  {
    "player_name": "Brown, Dan",
    "dg_id": 20766,
    "bestOdds": "+30000",
    "bestBook": "pointsbet",
    "dgOdds": "+40168",
    "allBooks": {
      "bet365": "+18000",
      "betmgm": "+22500",
      "caesars": "+25000",
      "draftkings": "+26000",
      "fanduel": "+22500",
      "pointsbet": "+30000",
      "betonline": "+30000",
      "bovada": "+25000",
      "unibet": "+15000",
      "betcris": "+20565"
    }
  },
  {
    "player_name": "Glover, Lucas",
    "dg_id": 7399,
    "bestOdds": "+30000",
    "bestBook": "pointsbet",
    "dgOdds": "+42453",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+17500",
      "caesars": "+20000",
      "draftkings": "+28000",
      "fanduel": "+17500",
      "pointsbet": "+30000",
      "betonline": "+30000",
      "bovada": "+25000",
      "unibet": "+15000"
    }
  },
  {
    "player_name": "Parry, John",
    "dg_id": 13764,
    "bestOdds": "+30000",
    "bestBook": "pointsbet",
    "dgOdds": "+44018",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+15000",
      "caesars": "+20000",
      "draftkings": "+21000",
      "fanduel": "+17500",
      "pinnacle": "+28085",
      "pointsbet": "+30000",
      "betonline": "+22500",
      "bovada": "+25000",
      "unibet": "+10000",
      "betcris": "+23067"
    }
  },
  {
    "player_name": "Hoge, Tom",
    "dg_id": 15575,
    "bestOdds": "+30000",
    "bestBook": "draftkings",
    "dgOdds": "+49487",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+22500",
      "caesars": "+20000",
      "draftkings": "+30000",
      "fanduel": "+22500",
      "pinnacle": "+26221",
      "pointsbet": "+30000",
      "betonline": "+25000",
      "bovada": "+25000",
      "unibet": "+20000"
    }
  },
  {
    "player_name": "Whaley, Vince",
    "dg_id": 25908,
    "bestOdds": "+30000",
    "bestBook": "bet365",
    "dgOdds": "+56504",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+22500",
      "caesars": "+25000",
      "draftkings": "+27000",
      "fanduel": "+22500",
      "pointsbet": "+30000",
      "betonline": "+30000",
      "bovada": "+30000",
      "unibet": "+20000"
    }
  },
  {
    "player_name": "Clanton, Luke",
    "dg_id": 32330,
    "bestOdds": "+30355",
    "bestBook": "pinnacle",
    "dgOdds": "+61756",
    "allBooks": {
      "bet365": "+27500",
      "betmgm": "+22500",
      "caesars": "+25000",
      "draftkings": "+28000",
      "fanduel": "+22500",
      "pinnacle": "+30355",
      "pointsbet": "+30000",
      "bovada": "+20000",
      "unibet": "+20000"
    }
  },
  {
    "player_name": "Ryder, Sam",
    "dg_id": 16715,
    "bestOdds": "+32000",
    "bestBook": "draftkings",
    "dgOdds": "+52532",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+17500",
      "caesars": "+20000",
      "draftkings": "+32000",
      "fanduel": "+22500",
      "pointsbet": "+30000",
      "betonline": "+22500",
      "bovada": "+25000",
      "unibet": "+20000",
      "betcris": "+20565"
    }
  },
  {
    "player_name": "Hubbard, Mark",
    "dg_id": 16333,
    "bestOdds": "+32500",
    "bestBook": "betonline",
    "dgOdds": "+39900",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+17500",
      "caesars": "+17500",
      "draftkings": "+30000",
      "fanduel": "+22500",
      "pinnacle": "+24027",
      "pointsbet": "+30000",
      "betonline": "+32500",
      "bovada": "+25000",
      "unibet": "+10000"
    }
  },
  {
    "player_name": "Hadwin, Adam",
    "dg_id": 13965,
    "bestOdds": "+32500",
    "bestBook": "betonline",
    "dgOdds": "+46412",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+25000",
      "caesars": "+17500",
      "draftkings": "+26000",
      "fanduel": "+22500",
      "pinnacle": "+28906",
      "pointsbet": "+30000",
      "betonline": "+32500",
      "bovada": "+25000",
      "unibet": "+17500",
      "betcris": "+30573"
    }
  },
  {
    "player_name": "Shipley, Neal",
    "dg_id": 32055,
    "bestOdds": "+32500",
    "bestBook": "betonline",
    "dgOdds": "+47519",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+17500",
      "caesars": "+17500",
      "draftkings": "+27500",
      "fanduel": "+17500",
      "pointsbet": "+20000",
      "betonline": "+32500",
      "bovada": "+22500",
      "unibet": "+20000"
    }
  },
  {
    "player_name": "Springer, Hayden",
    "dg_id": 21995,
    "bestOdds": "+33000",
    "bestBook": "draftkings",
    "dgOdds": "+51182",
    "allBooks": {
      "bet365": "+27500",
      "betmgm": "+17500",
      "caesars": "+20000",
      "draftkings": "+33000",
      "fanduel": "+17500",
      "pointsbet": "+30000",
      "betonline": "+32500",
      "bovada": "+25000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Pavon, Matthieu",
    "dg_id": 19960,
    "bestOdds": "+35000",
    "bestBook": "bet365",
    "dgOdds": "+52074",
    "allBooks": {
      "bet365": "+35000",
      "betmgm": "+30000",
      "caesars": "+32500",
      "draftkings": "+34000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "bovada": "+35000",
      "unibet": "+17500"
    }
  },
  {
    "player_name": "Vilips, Karl",
    "dg_id": 24304,
    "bestOdds": "+35000",
    "bestBook": "pointsbet",
    "dgOdds": "+71329",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+22500",
      "caesars": "+27500",
      "draftkings": "+32500",
      "fanduel": "+25000",
      "pinnacle": "+31716",
      "pointsbet": "+35000",
      "betonline": "+32500",
      "bovada": "+30000",
      "unibet": "+25000",
      "betcris": "+20565"
    }
  },
  {
    "player_name": "Fishburn, Patrick",
    "dg_id": 25094,
    "bestOdds": "+36000",
    "bestBook": "draftkings",
    "dgOdds": "+51182",
    "allBooks": {
      "bet365": "+27500",
      "betmgm": "+17500",
      "caesars": "+25000",
      "draftkings": "+36000",
      "fanduel": "+22500",
      "pinnacle": "+31171",
      "pointsbet": "+30000",
      "betonline": "+30000",
      "bovada": "+25000",
      "unibet": "+15000"
    }
  },
  {
    "player_name": "Kanaya, Takumi",
    "dg_id": 19729,
    "bestOdds": "+37000",
    "bestBook": "draftkings",
    "dgOdds": "+61124",
    "allBooks": {
      "bet365": "+35000",
      "betmgm": "+25000",
      "caesars": "+32500",
      "draftkings": "+37000",
      "fanduel": "+35000",
      "pinnacle": "+30948",
      "pointsbet": "+35000",
      "bovada": "+35000",
      "unibet": "+20000"
    }
  },
  {
    "player_name": "Svensson, Adam",
    "dg_id": 13997,
    "bestOdds": "+37500",
    "bestBook": "draftkings",
    "dgOdds": "+50747",
    "allBooks": {
      "bet365": "+27500",
      "betmgm": "+25000",
      "caesars": "+27500",
      "draftkings": "+37500",
      "fanduel": "+25000",
      "pointsbet": "+35000",
      "betonline": "+30000",
      "bovada": "+30000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Waring, Paul",
    "dg_id": 12426,
    "bestOdds": "+40000",
    "bestBook": "draftkings",
    "dgOdds": "+47900",
    "allBooks": {
      "bet365": "+35000",
      "betmgm": "+35000",
      "caesars": "+32500",
      "draftkings": "+40000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "betonline": "+40000",
      "bovada": "+40000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Dahmen, Joel",
    "dg_id": 14509,
    "bestOdds": "+40000",
    "bestBook": "bet365",
    "dgOdds": "+66567",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+30000",
      "caesars": "+32500",
      "draftkings": "+36000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "bovada": "+40000",
      "unibet": "+20000"
    }
  },
  {
    "player_name": "Crowe, Trace",
    "dg_id": 27780,
    "bestOdds": "+40000",
    "bestBook": "bet365",
    "dgOdds": "+71329",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+25000",
      "caesars": "+27500",
      "draftkings": "+38000",
      "fanduel": "+25000",
      "pointsbet": "+35000",
      "bovada": "+35000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Griffin, Lanto",
    "dg_id": 15330,
    "bestOdds": "+45000",
    "bestBook": "draftkings",
    "dgOdds": "+71329",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+25000",
      "caesars": "+27500",
      "draftkings": "+45000",
      "fanduel": "+25000",
      "pointsbet": "+35000",
      "bovada": "+25000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Stanger, Jimmy",
    "dg_id": 23048,
    "bestOdds": "+45000",
    "bestBook": "bet365",
    "dgOdds": "+103348",
    "allBooks": {
      "bet365": "+45000",
      "betmgm": "+30000",
      "caesars": "+32500",
      "draftkings": "+44000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "bovada": "+40000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Van Rooyen, Erik",
    "dg_id": 17550,
    "bestOdds": "+46000",
    "bestBook": "draftkings",
    "dgOdds": "+103348",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+35000",
      "caesars": "+25000",
      "draftkings": "+46000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "betonline": "+32500",
      "bovada": "+40000",
      "unibet": "+25000",
      "betcris": "+33075"
    }
  },
  {
    "player_name": "Dunlap, Nick",
    "dg_id": 28270,
    "bestOdds": "+49000",
    "bestBook": "draftkings",
    "dgOdds": "+98261",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+30000",
      "caesars": "+32500",
      "draftkings": "+49000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "bovada": "+30000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Nyholm, Pontus",
    "dg_id": 25475,
    "bestOdds": "+49000",
    "bestBook": "draftkings",
    "dgOdds": "+99900",
    "allBooks": {
      "bet365": "+45000",
      "betmgm": "+30000",
      "caesars": "+32500",
      "draftkings": "+49000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "betonline": "+40000",
      "bovada": "+45000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Skinns, David",
    "dg_id": 10873,
    "bestOdds": "+50000",
    "bestBook": "draftkings",
    "dgOdds": "+75849",
    "allBooks": {
      "bet365": "+45000",
      "betmgm": "+30000",
      "caesars": "+37500",
      "draftkings": "+50000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "bovada": "+45000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Lipsky, David",
    "dg_id": 15980,
    "bestOdds": "+50000",
    "bestBook": "draftkings",
    "dgOdds": "+103348",
    "allBooks": {
      "bet365": "+35000",
      "betmgm": "+35000",
      "caesars": "+27500",
      "draftkings": "+50000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "bovada": "+35000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Lebioda, Hank",
    "dg_id": 21943,
    "bestOdds": "+55000",
    "bestBook": "draftkings",
    "dgOdds": "+67316",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+35000",
      "caesars": "+37500",
      "draftkings": "+55000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "bovada": "+50000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "VanDerLaan, John",
    "dg_id": 25319,
    "bestOdds": "+55000",
    "bestBook": "draftkings",
    "dgOdds": "+76823",
    "allBooks": {
      "bet365": "+45000",
      "betmgm": "+35000",
      "caesars": "+32500",
      "draftkings": "+55000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "bovada": "+45000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Wu, Dylan",
    "dg_id": 25002,
    "bestOdds": "+55000",
    "bestBook": "draftkings",
    "dgOdds": "+113108",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+50000",
      "caesars": "+37500",
      "draftkings": "+55000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "bovada": "+50000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Willett, Danny",
    "dg_id": 12920,
    "bestOdds": "+60000",
    "bestBook": "draftkings",
    "dgOdds": "+96674",
    "allBooks": {
      "bet365": "+27500",
      "betmgm": "+30000",
      "caesars": "+30000",
      "draftkings": "+60000",
      "fanduel": "+25000",
      "pointsbet": "+35000",
      "bovada": "+30000",
      "unibet": "+25000",
      "betcris": "+28571"
    }
  },
  {
    "player_name": "Phillips, Chandler",
    "dg_id": 27164,
    "bestOdds": "+70000",
    "bestBook": "draftkings",
    "dgOdds": "+193448",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+37500",
      "draftkings": "+70000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "bovada": "+60000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Hirata, Kensei",
    "dg_id": 20954,
    "bestOdds": "+75000",
    "bestBook": "fanduel",
    "dgOdds": "+108991",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+50000",
      "caesars": "+47500",
      "draftkings": "+70000",
      "fanduel": "+75000",
      "pointsbet": "+40000",
      "bovada": "+50000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Lamprecht, Christo",
    "dg_id": 24343,
    "bestOdds": "+75000",
    "bestBook": "bet365",
    "dgOdds": "+117547",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+35000",
      "caesars": "+47500",
      "draftkings": "+75000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "bovada": "+50000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Sloan, Roger",
    "dg_id": 14050,
    "bestOdds": "+80000",
    "bestBook": "draftkings",
    "dgOdds": "+122349",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+50000",
      "caesars": "+47500",
      "draftkings": "+80000",
      "fanduel": "+75000",
      "pointsbet": "+40000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Walker, Danny",
    "dg_id": 25003,
    "bestOdds": "+82500",
    "bestBook": "draftkings",
    "dgOdds": "+162062",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+82500",
      "fanduel": "+75000",
      "pointsbet": "+45000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Tosti, Alejandro",
    "dg_id": 17032,
    "bestOdds": "+90000",
    "bestBook": "draftkings",
    "dgOdds": "+89452",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+90000",
      "fanduel": "+50000",
      "pointsbet": "+60000",
      "bovada": "+50000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Silverman, Ben",
    "dg_id": 17381,
    "bestOdds": "+90000",
    "bestBook": "pointsbet",
    "dgOdds": "+124900",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+35000",
      "caesars": "+30000",
      "draftkings": "+52500",
      "fanduel": "+50000",
      "pointsbet": "+90000",
      "bovada": "+50000",
      "unibet": "+35000",
      "betcris": "+42582"
    }
  },
  {
    "player_name": "Schenk, Adam",
    "dg_id": 19477,
    "bestOdds": "+100000",
    "bestBook": "fanduel",
    "dgOdds": "+139435",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+72500",
      "fanduel": "+100000",
      "pointsbet": "+45000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Davis, Cam",
    "dg_id": 17786,
    "bestOdds": "+100000",
    "bestBook": "draftkings",
    "dgOdds": "+157795",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+100000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Riley, Davis",
    "dg_id": 19872,
    "bestOdds": "+100000",
    "bestBook": "fanduel",
    "dgOdds": "+162062",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+30000",
      "draftkings": "+90000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Lower, Justin",
    "dg_id": 17723,
    "bestOdds": "+100000",
    "bestBook": "fanduel",
    "dgOdds": "+162062",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+50000",
      "draftkings": "+75000",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "bovada": "+60000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Peterson, Paul",
    "dg_id": 16341,
    "bestOdds": "+100000",
    "bestBook": "draftkings",
    "dgOdds": "+176371",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+100000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Campbell, Brian",
    "dg_id": 18628,
    "bestOdds": "+100000",
    "bestBook": "fanduel",
    "dgOdds": "+285614",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+50000",
      "caesars": "+40000",
      "draftkings": "+80000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "bovada": "+60000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Kang, Jeffrey",
    "dg_id": 21889,
    "bestOdds": "+110000",
    "bestBook": "draftkings",
    "dgOdds": "+119900",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+40000",
      "draftkings": "+110000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Hoffman, Charley",
    "dg_id": 5768,
    "bestOdds": "+115000",
    "bestBook": "draftkings",
    "dgOdds": "+230669",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+47500",
      "draftkings": "+115000",
      "fanduel": "+75000",
      "pointsbet": "+90000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Malnati, Peter",
    "dg_id": 14926,
    "bestOdds": "+130000",
    "bestBook": "draftkings",
    "dgOdds": "+146241",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+130000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Harrington, Padraig",
    "dg_id": 5716,
    "bestOdds": "+130000",
    "bestBook": "draftkings",
    "dgOdds": "+599900",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+75000",
      "caesars": "+100000",
      "draftkings": "+130000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Garnett, Brice",
    "dg_id": 11451,
    "bestOdds": "+135000",
    "bestBook": "draftkings",
    "dgOdds": "+176371",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+50000",
      "caesars": "+47500",
      "draftkings": "+135000",
      "fanduel": "+75000",
      "pointsbet": "+40000",
      "bovada": "+60000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Chatfield, Davis",
    "dg_id": 30620,
    "bestOdds": "+135000",
    "bestBook": "draftkings",
    "dgOdds": "+187400",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+135000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Highsmith, Joe",
    "dg_id": 28469,
    "bestOdds": "+135000",
    "bestBook": "draftkings",
    "dgOdds": "+206797",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+75000",
      "draftkings": "+135000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Villegas, Camilo",
    "dg_id": 9171,
    "bestOdds": "+150000",
    "bestBook": "draftkings",
    "dgOdds": "+374900",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+50000",
      "caesars": "+47500",
      "draftkings": "+150000",
      "fanduel": "+75000",
      "pointsbet": "+40000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Anderson, Matthew",
    "dg_id": 26617,
    "bestOdds": "+160000",
    "bestBook": "draftkings",
    "dgOdds": "+315689",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+160000",
      "fanduel": "+75000",
      "pointsbet": "+40000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Rozo, Marcelo",
    "dg_id": 16591,
    "bestOdds": "+180000",
    "bestBook": "draftkings",
    "dgOdds": "+285614",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+75000",
      "caesars": "+47500",
      "draftkings": "+180000",
      "fanduel": "+75000",
      "pointsbet": "+60000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Savoie, Joey",
    "dg_id": 25289,
    "bestOdds": "+200000",
    "bestBook": "draftkings",
    "dgOdds": "+239900",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+50000",
      "caesars": "+37500",
      "draftkings": "+200000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Martin, Ben",
    "dg_id": 14007,
    "bestOdds": "+200000",
    "bestBook": "bet365",
    "dgOdds": "+461438",
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+125000",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "bovada": "+100000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Kizzire, Patton",
    "dg_id": 13470,
    "bestOdds": "+200000",
    "bestBook": "draftkings",
    "dgOdds": "+499900",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+150000",
      "caesars": "+100000",
      "draftkings": "+200000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Nesbitt, Drew",
    "dg_id": 16492,
    "bestOdds": "+200000",
    "bestBook": "bet365",
    "dgOdds": "+545355",
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+150000",
      "caesars": "+150000",
      "draftkings": "+200000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Lew, Dawson",
    "dg_id": 30040252,
    "bestOdds": "+200000",
    "bestBook": "bet365",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+75000",
      "caesars": "+47500",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Campos, Rafael",
    "dg_id": 12909,
    "bestOdds": "+300000",
    "bestBook": "draftkings",
    "dgOdds": "+857043",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+75000",
      "caesars": "+200000",
      "draftkings": "+300000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+150000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "O'Donovan, Declan",
    "dg_id": 30717,
    "bestOdds": "+300000",
    "bestBook": "draftkings",
    "dgOdds": "+857043",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+150000",
      "caesars": "+100000",
      "draftkings": "+300000",
      "fanduel": "+100000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Zhao, Eric",
    "dg_id": 30036882,
    "bestOdds": "+300000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+100000",
      "draftkings": "+300000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "O'Hair, Sean",
    "dg_id": 7626,
    "bestOdds": "+325000",
    "bestBook": "draftkings",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+325000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Weir, Mike",
    "dg_id": 5513,
    "bestOdds": "+350000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+100000",
      "draftkings": "+350000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Matthews, Justin",
    "dg_id": 32259,
    "bestOdds": "+400000",
    "bestBook": "draftkings",
    "dgOdds": "+999900",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+60000",
      "caesars": "+100000",
      "draftkings": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "McCulloch, Ashton",
    "dg_id": 32260,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+999900",
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Sihota, Jeevan",
    "dg_id": 29702,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "betmgm": "+150000",
      "caesars": "+100000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Covello, Vince",
    "dg_id": 11441,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+150000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Benson, Yohann",
    "dg_id": 9457,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+200000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Sanderson, Calen",
    "dg_id": 35395,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+150000",
      "caesars": "+100000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Desmarchais, Laurent",
    "dg_id": 31347,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+150000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  }
];
