// Generated by scripts/build-outrights.ts on 2026-06-15T18:27:35.491Z
// rbc-canadian-open-2026 / r3 — outright WINNER odds, 156 entries.
// Best odds computed across real sportsbooks (DataGolf excluded). DO NOT EDIT BY HAND.

import type { OutrightEntry } from '../types';

export const r4OutrightsData: OutrightEntry[] = [
  {
    "player_name": "Scheffler, Scottie",
    "dg_id": 18417,
    "bestOdds": "+650",
    "bestBook": "pointsbet",
    "dgOdds": "+736",
    "allBooks": {
      "bet365": "+600",
      "betmgm": "+550",
      "caesars": "+450",
      "draftkings": "+460",
      "fanduel": "+600",
      "pinnacle": "+601",
      "pointsbet": "+650",
      "betonline": "+600",
      "bovada": "+600",
      "unibet": "+550",
      "betcris": "+558"
    }
  },
  {
    "player_name": "McIlroy, Rory",
    "dg_id": 10091,
    "bestOdds": "+1219",
    "bestBook": "pinnacle",
    "dgOdds": "+1634",
    "allBooks": {
      "bet365": "+1100",
      "betmgm": "+1200",
      "caesars": "+1100",
      "draftkings": "+970",
      "fanduel": "+1200",
      "pinnacle": "+1219",
      "pointsbet": "+1200",
      "betonline": "+1200",
      "bovada": "+1200",
      "unibet": "+1200",
      "betcris": "+1116"
    }
  },
  {
    "player_name": "Rahm, Jon",
    "dg_id": 19195,
    "bestOdds": "+1600",
    "bestBook": "betonline",
    "dgOdds": "+2077",
    "allBooks": {
      "bet365": "+1200",
      "betmgm": "+1400",
      "caesars": "+1400",
      "draftkings": "+1050",
      "fanduel": "+1500",
      "pinnacle": "+1441",
      "pointsbet": "+1500",
      "betonline": "+1600",
      "bovada": "+1400",
      "unibet": "+1400",
      "betcris": "+1400"
    }
  },
  {
    "player_name": "Schauffele, Xander",
    "dg_id": 19895,
    "bestOdds": "+2051",
    "bestBook": "betcris",
    "dgOdds": "+1971",
    "allBooks": {
      "bet365": "+1800",
      "betmgm": "+1800",
      "caesars": "+2000",
      "draftkings": "+1850",
      "fanduel": "+2000",
      "pinnacle": "+1879",
      "pointsbet": "+2000",
      "betonline": "+2000",
      "bovada": "+2000",
      "unibet": "+1800",
      "betcris": "+2051"
    }
  },
  {
    "player_name": "Young, Cameron",
    "dg_id": 26651,
    "bestOdds": "+2219",
    "bestBook": "pinnacle",
    "dgOdds": "+3032",
    "allBooks": {
      "bet365": "+1800",
      "betmgm": "+2000",
      "caesars": "+1200",
      "draftkings": "+2050",
      "fanduel": "+2200",
      "pinnacle": "+2219",
      "pointsbet": "+2000",
      "betonline": "+2200",
      "bovada": "+1800",
      "unibet": "+2000",
      "betcris": "+2027"
    }
  },
  {
    "player_name": "Fitzpatrick, Matt",
    "dg_id": 17646,
    "bestOdds": "+2287",
    "bestBook": "betcris",
    "dgOdds": "+2420",
    "allBooks": {
      "bet365": "+1800",
      "betmgm": "+2000",
      "caesars": "+1600",
      "draftkings": "+2100",
      "fanduel": "+2000",
      "pinnacle": "+2259",
      "pointsbet": "+2000",
      "betonline": "+2200",
      "bovada": "+2000",
      "unibet": "+1800",
      "betcris": "+2287"
    }
  },
  {
    "player_name": "Fleetwood, Tommy",
    "dg_id": 12294,
    "bestOdds": "+2400",
    "bestBook": "draftkings",
    "dgOdds": "+2412",
    "allBooks": {
      "bet365": "+1800",
      "betmgm": "+2200",
      "caesars": "+1600",
      "draftkings": "+2400",
      "fanduel": "+2000",
      "pinnacle": "+1922",
      "pointsbet": "+2000",
      "betonline": "+2200",
      "bovada": "+2200",
      "unibet": "+1800",
      "betcris": "+2230"
    }
  },
  {
    "player_name": "Aberg, Ludvig",
    "dg_id": 23950,
    "bestOdds": "+2600",
    "bestBook": "draftkings",
    "dgOdds": "+2863",
    "allBooks": {
      "bet365": "+2200",
      "betmgm": "+2200",
      "caesars": "+2100",
      "draftkings": "+2600",
      "fanduel": "+2200",
      "pinnacle": "+2323",
      "pointsbet": "+2200",
      "betonline": "+2500",
      "bovada": "+2500",
      "unibet": "+2200",
      "betcris": "+2489"
    }
  },
  {
    "player_name": "DeChambeau, Bryson",
    "dg_id": 19841,
    "bestOdds": "+3603",
    "bestBook": "pinnacle",
    "dgOdds": "+5369",
    "allBooks": {
      "bet365": "+2800",
      "betmgm": "+2500",
      "caesars": "+3000",
      "draftkings": "+2900",
      "fanduel": "+3000",
      "pinnacle": "+3603",
      "pointsbet": "+2800",
      "betonline": "+3000",
      "bovada": "+2500",
      "unibet": "+2500",
      "betcris": "+3050"
    }
  },
  {
    "player_name": "Koepka, Brooks",
    "dg_id": 16243,
    "bestOdds": "+4095",
    "bestBook": "pinnacle",
    "dgOdds": "+7868",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+3000",
      "caesars": "+2500",
      "draftkings": "+3400",
      "fanduel": "+3500",
      "pinnacle": "+4095",
      "pointsbet": "+3500",
      "betonline": "+4000",
      "bovada": "+3500",
      "unibet": "+3300",
      "betcris": "+3050"
    }
  },
  {
    "player_name": "Henley, Russell",
    "dg_id": 14578,
    "bestOdds": "+4114",
    "bestBook": "pinnacle",
    "dgOdds": "+4381",
    "allBooks": {
      "bet365": "+3300",
      "betmgm": "+4000",
      "caesars": "+3000",
      "draftkings": "+3700",
      "fanduel": "+3500",
      "pinnacle": "+4114",
      "pointsbet": "+3500",
      "betonline": "+3500",
      "bovada": "+4000",
      "unibet": "+3300",
      "betcris": "+3991"
    }
  },
  {
    "player_name": "Kim, Si Woo",
    "dg_id": 14609,
    "bestOdds": "+4500",
    "bestBook": "bovada",
    "dgOdds": "+4220",
    "allBooks": {
      "bet365": "+3300",
      "betmgm": "+4000",
      "caesars": "+3000",
      "draftkings": "+3900",
      "fanduel": "+3300",
      "pinnacle": "+4080",
      "pointsbet": "+3000",
      "betonline": "+4000",
      "bovada": "+4500",
      "unibet": "+4000",
      "betcris": "+4099"
    }
  },
  {
    "player_name": "Burns, Sam",
    "dg_id": 19483,
    "bestOdds": "+4500",
    "bestBook": "betonline",
    "dgOdds": "+4774",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+4000",
      "caesars": "+2800",
      "draftkings": "+3900",
      "fanduel": "+4000",
      "pinnacle": "+4387",
      "pointsbet": "+4000",
      "betonline": "+4500",
      "bovada": "+4000",
      "unibet": "+3500",
      "betcris": "+4058"
    }
  },
  {
    "player_name": "Clark, Wyndham",
    "dg_id": 23604,
    "bestOdds": "+4508",
    "bestBook": "pinnacle",
    "dgOdds": "+8435",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+4000",
      "caesars": "+3500",
      "draftkings": "+3800",
      "fanduel": "+4000",
      "pinnacle": "+4508",
      "pointsbet": "+4000",
      "betonline": "+4500",
      "bovada": "+3500",
      "unibet": "+3500",
      "betcris": "+4259"
    }
  },
  {
    "player_name": "Hatton, Tyrrell",
    "dg_id": 14796,
    "bestOdds": "+4700",
    "bestBook": "draftkings",
    "dgOdds": "+6909",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+3300",
      "caesars": "+4500",
      "draftkings": "+4700",
      "fanduel": "+4000",
      "pinnacle": "+4540",
      "pointsbet": "+4000",
      "betonline": "+4500",
      "bovada": "+4000",
      "unibet": "+3500",
      "betcris": "+4057"
    }
  },
  {
    "player_name": "Reed, Patrick",
    "dg_id": 14838,
    "bestOdds": "+5000",
    "bestBook": "betonline",
    "dgOdds": "+8855",
    "allBooks": {
      "bet365": "+4000",
      "betmgm": "+4000",
      "caesars": "+4500",
      "draftkings": "+4900",
      "fanduel": "+4500",
      "pinnacle": "+4907",
      "pointsbet": "+4500",
      "betonline": "+5000",
      "bovada": "+4500",
      "unibet": "+4000",
      "betcris": "+4550"
    }
  },
  {
    "player_name": "Morikawa, Collin",
    "dg_id": 22085,
    "bestOdds": "+5070",
    "bestBook": "betcris",
    "dgOdds": "+5582",
    "allBooks": {
      "bet365": "+3500",
      "betmgm": "+4000",
      "caesars": "+4000",
      "draftkings": "+3600",
      "fanduel": "+4000",
      "pinnacle": "+4879",
      "pointsbet": "+4000",
      "betonline": "+4500",
      "bovada": "+4000",
      "unibet": "+4000",
      "betcris": "+5070"
    }
  },
  {
    "player_name": "Gotterup, Chris",
    "dg_id": 27774,
    "bestOdds": "+5450",
    "bestBook": "betcris",
    "dgOdds": "+6574",
    "allBooks": {
      "bet365": "+4000",
      "betmgm": "+4000",
      "caesars": "+4500",
      "draftkings": "+4600",
      "fanduel": "+4000",
      "pinnacle": "+5416",
      "pointsbet": "+4000",
      "betonline": "+5000",
      "bovada": "+4500",
      "unibet": "+4500",
      "betcris": "+5450"
    }
  },
  {
    "player_name": "Hovland, Viktor",
    "dg_id": 18841,
    "bestOdds": "+5500",
    "bestBook": "betonline",
    "dgOdds": "+5967",
    "allBooks": {
      "bet365": "+4500",
      "betmgm": "+4000",
      "caesars": "+4500",
      "draftkings": "+5000",
      "fanduel": "+4500",
      "pinnacle": "+5205",
      "pointsbet": "+4500",
      "betonline": "+5500",
      "bovada": "+4500",
      "unibet": "+4500",
      "betcris": "+5196"
    }
  },
  {
    "player_name": "Thomas, Justin",
    "dg_id": 14139,
    "bestOdds": "+5577",
    "bestBook": "betcris",
    "dgOdds": "+6545",
    "allBooks": {
      "bet365": "+4000",
      "betmgm": "+4000",
      "caesars": "+4500",
      "draftkings": "+4600",
      "fanduel": "+4000",
      "pinnacle": "+5513",
      "pointsbet": "+4000",
      "betonline": "+5500",
      "bovada": "+4500",
      "unibet": "+4500",
      "betcris": "+5577"
    }
  },
  {
    "player_name": "Rose, Justin",
    "dg_id": 6093,
    "bestOdds": "+5755",
    "bestBook": "pinnacle",
    "dgOdds": "+9117",
    "allBooks": {
      "bet365": "+4000",
      "betmgm": "+4500",
      "caesars": "+4500",
      "draftkings": "+5300",
      "fanduel": "+5000",
      "pinnacle": "+5755",
      "pointsbet": "+5000",
      "betonline": "+5500",
      "bovada": "+4500",
      "unibet": "+4000",
      "betcris": "+5070"
    }
  },
  {
    "player_name": "Cantlay, Patrick",
    "dg_id": 15466,
    "bestOdds": "+6065",
    "bestBook": "betcris",
    "dgOdds": "+5609",
    "allBooks": {
      "bet365": "+4000",
      "betmgm": "+4500",
      "caesars": "+5000",
      "draftkings": "+4500",
      "fanduel": "+4500",
      "pinnacle": "+4956",
      "pointsbet": "+5000",
      "betonline": "+5500",
      "bovada": "+5000",
      "unibet": "+4000",
      "betcris": "+6065"
    }
  },
  {
    "player_name": "Spaun, J.J.",
    "dg_id": 17536,
    "bestOdds": "+6100",
    "bestBook": "draftkings",
    "dgOdds": "+6861",
    "allBooks": {
      "bet365": "+4000",
      "betmgm": "+5000",
      "caesars": "+5500",
      "draftkings": "+6100",
      "fanduel": "+5000",
      "pinnacle": "+5622",
      "pointsbet": "+5000",
      "betonline": "+5000",
      "bovada": "+5000",
      "unibet": "+5500",
      "betcris": "+5876"
    }
  },
  {
    "player_name": "Lee, Min Woo",
    "dg_id": 16841,
    "bestOdds": "+7550",
    "bestBook": "betcris",
    "dgOdds": "+6942",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+7000",
      "caesars": "+6000",
      "draftkings": "+6700",
      "fanduel": "+6500",
      "pinnacle": "+6994",
      "pointsbet": "+6600",
      "betonline": "+7000",
      "bovada": "+7000",
      "unibet": "+6600",
      "betcris": "+7550"
    }
  },
  {
    "player_name": "Matsuyama, Hideki",
    "dg_id": 13562,
    "bestOdds": "+8000",
    "bestBook": "betonline",
    "dgOdds": "+11948",
    "allBooks": {
      "bet365": "+5500",
      "betmgm": "+6000",
      "caesars": "+5500",
      "draftkings": "+6700",
      "fanduel": "+6000",
      "pinnacle": "+7850",
      "pointsbet": "+6000",
      "betonline": "+8000",
      "bovada": "+6000",
      "unibet": "+6600",
      "betcris": "+7656"
    }
  },
  {
    "player_name": "Lowry, Shane",
    "dg_id": 13900,
    "bestOdds": "+8400",
    "bestBook": "draftkings",
    "dgOdds": "+11416",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+7000",
      "caesars": "+7000",
      "draftkings": "+8400",
      "fanduel": "+6500",
      "pinnacle": "+8139",
      "pointsbet": "+6600",
      "betonline": "+7500",
      "bovada": "+6000",
      "unibet": "+6600",
      "betcris": "+7608"
    }
  },
  {
    "player_name": "Spieth, Jordan",
    "dg_id": 14636,
    "bestOdds": "+8463",
    "bestBook": "pinnacle",
    "dgOdds": "+9867",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+6600",
      "caesars": "+6000",
      "draftkings": "+7000",
      "fanduel": "+6500",
      "pinnacle": "+8463",
      "pointsbet": "+6600",
      "betonline": "+8000",
      "bovada": "+6000",
      "unibet": "+6600",
      "betcris": "+5577"
    }
  },
  {
    "player_name": "MacIntyre, Robert",
    "dg_id": 23323,
    "bestOdds": "+8620",
    "bestBook": "betcris",
    "dgOdds": "+9640",
    "allBooks": {
      "bet365": "+5500",
      "betmgm": "+7000",
      "caesars": "+5500",
      "draftkings": "+6200",
      "fanduel": "+6500",
      "pinnacle": "+7206",
      "pointsbet": "+6600",
      "betonline": "+7500",
      "bovada": "+6500",
      "unibet": "+6600",
      "betcris": "+8620"
    }
  },
  {
    "player_name": "Niemann, Joaquin",
    "dg_id": 18079,
    "bestOdds": "+8621",
    "bestBook": "betcris",
    "dgOdds": "+12348",
    "allBooks": {
      "bet365": "+6000",
      "betmgm": "+6000",
      "caesars": "+6000",
      "draftkings": "+7000",
      "fanduel": "+7000",
      "pinnacle": "+8355",
      "pointsbet": "+7000",
      "betonline": "+8000",
      "bovada": "+6000",
      "unibet": "+6600",
      "betcris": "+8621"
    }
  },
  {
    "player_name": "Kitayama, Kurt",
    "dg_id": 21891,
    "bestOdds": "+9000",
    "bestBook": "bovada",
    "dgOdds": "+7563",
    "allBooks": {
      "bet365": "+6600",
      "betmgm": "+7500",
      "caesars": "+6000",
      "draftkings": "+7200",
      "fanduel": "+6500",
      "pinnacle": "+8020",
      "pointsbet": "+6600",
      "betonline": "+8000",
      "bovada": "+9000",
      "unibet": "+6600",
      "betcris": "+8050"
    }
  },
  {
    "player_name": "McNealy, Maverick",
    "dg_id": 18634,
    "bestOdds": "+9659",
    "bestBook": "betcris",
    "dgOdds": "+8363",
    "allBooks": {
      "bet365": "+7000",
      "betmgm": "+7000",
      "caesars": "+7500",
      "draftkings": "+7800",
      "fanduel": "+8000",
      "pinnacle": "+7604",
      "pointsbet": "+8000",
      "betonline": "+9000",
      "bovada": "+8000",
      "unibet": "+6600",
      "betcris": "+9659"
    }
  },
  {
    "player_name": "Griffin, Ben",
    "dg_id": 24968,
    "bestOdds": "+10050",
    "bestBook": "betcris",
    "dgOdds": "+10501",
    "allBooks": {
      "bet365": "+6600",
      "betmgm": "+7000",
      "caesars": "+7500",
      "draftkings": "+7400",
      "fanduel": "+8000",
      "pinnacle": "+8993",
      "pointsbet": "+8000",
      "betonline": "+9000",
      "bovada": "+7000",
      "unibet": "+6600",
      "betcris": "+10050"
    }
  },
  {
    "player_name": "Rai, Aaron",
    "dg_id": 18554,
    "bestOdds": "+10500",
    "bestBook": "draftkings",
    "dgOdds": "+12374",
    "allBooks": {
      "bet365": "+7500",
      "betmgm": "+8000",
      "caesars": "+7000",
      "draftkings": "+10500",
      "fanduel": "+7000",
      "pinnacle": "+9472",
      "pointsbet": "+7000",
      "betonline": "+9000",
      "bovada": "+8000",
      "unibet": "+8000",
      "betcris": "+10050"
    }
  },
  {
    "player_name": "Scott, Adam",
    "dg_id": 6430,
    "bestOdds": "+10560",
    "bestBook": "betcris",
    "dgOdds": "+9752",
    "allBooks": {
      "bet365": "+7500",
      "betmgm": "+9000",
      "caesars": "+7000",
      "draftkings": "+7600",
      "fanduel": "+8000",
      "pinnacle": "+9002",
      "pointsbet": "+8000",
      "betonline": "+10000",
      "bovada": "+9000",
      "unibet": "+9000",
      "betcris": "+10560"
    }
  },
  {
    "player_name": "Cauley, Bud",
    "dg_id": 14502,
    "bestOdds": "+11000",
    "bestBook": "betonline",
    "dgOdds": "+10426",
    "allBooks": {
      "bet365": "+8000",
      "betmgm": "+8000",
      "caesars": "+9000",
      "draftkings": "+9800",
      "fanduel": "+10000",
      "pinnacle": "+9379",
      "pointsbet": "+9000",
      "betonline": "+11000",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+9551"
    }
  },
  {
    "player_name": "Reitan, Kristoffer",
    "dg_id": 21407,
    "bestOdds": "+11000",
    "bestBook": "draftkings",
    "dgOdds": "+10750",
    "allBooks": {
      "bet365": "+8000",
      "betmgm": "+9000",
      "caesars": "+7500",
      "draftkings": "+11000",
      "fanduel": "+8000",
      "pinnacle": "+9271",
      "pointsbet": "+8000",
      "betonline": "+11000",
      "bovada": "+8000",
      "unibet": "+8000",
      "betcris": "+10142"
    }
  },
  {
    "player_name": "Fitzpatrick, Alex",
    "dg_id": 25362,
    "bestOdds": "+12500",
    "bestBook": "betonline",
    "dgOdds": "+11178",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+10000",
      "caesars": "+9000",
      "draftkings": "+10000",
      "fanduel": "+8000",
      "pinnacle": "+10107",
      "pointsbet": "+8000",
      "betonline": "+12500",
      "bovada": "+9000",
      "unibet": "+8000",
      "betcris": "+11550"
    }
  },
  {
    "player_name": "English, Harris",
    "dg_id": 14577,
    "bestOdds": "+12674",
    "bestBook": "betcris",
    "dgOdds": "+11094",
    "allBooks": {
      "bet365": "+7500",
      "betmgm": "+8000",
      "caesars": "+9000",
      "draftkings": "+8800",
      "fanduel": "+8000",
      "pinnacle": "+9748",
      "pointsbet": "+8000",
      "betonline": "+9000",
      "bovada": "+9000",
      "unibet": "+6600",
      "betcris": "+12674"
    }
  },
  {
    "player_name": "Hojgaard, Nicolai",
    "dg_id": 23602,
    "bestOdds": "+13693",
    "bestBook": "betcris",
    "dgOdds": "+12693",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+9000",
      "caesars": "+9000",
      "draftkings": "+12000",
      "fanduel": "+10000",
      "pinnacle": "+11230",
      "pointsbet": "+10000",
      "betonline": "+11000",
      "bovada": "+9000",
      "unibet": "+9000",
      "betcris": "+13693"
    }
  },
  {
    "player_name": "Gerard, Ryan",
    "dg_id": 29767,
    "bestOdds": "+13693",
    "bestBook": "betcris",
    "dgOdds": "+13029",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+10000",
      "caesars": "+12500",
      "draftkings": "+10500",
      "fanduel": "+10000",
      "pinnacle": "+11261",
      "pointsbet": "+12500",
      "betonline": "+12500",
      "bovada": "+10000",
      "unibet": "+8000",
      "betcris": "+13693"
    }
  },
  {
    "player_name": "Straka, Sepp",
    "dg_id": 17511,
    "bestOdds": "+14426",
    "bestBook": "pinnacle",
    "dgOdds": "+16338",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+10000",
      "caesars": "+9000",
      "draftkings": "+11000",
      "fanduel": "+10000",
      "pinnacle": "+14426",
      "pointsbet": "+10000",
      "betonline": "+12500",
      "bovada": "+10000",
      "unibet": "+10000",
      "betcris": "+11696"
    }
  },
  {
    "player_name": "Knapp, Jake",
    "dg_id": 19396,
    "bestOdds": "+14550",
    "bestBook": "betcris",
    "dgOdds": "+13233",
    "allBooks": {
      "bet365": "+11000",
      "betmgm": "+9000",
      "caesars": "+9000",
      "draftkings": "+9800",
      "fanduel": "+10000",
      "pinnacle": "+11864",
      "pointsbet": "+9000",
      "betonline": "+12500",
      "bovada": "+9000",
      "unibet": "+12500",
      "betcris": "+14550"
    }
  },
  {
    "player_name": "Smith, Cameron",
    "dg_id": 15856,
    "bestOdds": "+15000",
    "bestBook": "draftkings",
    "dgOdds": "+42453",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+8000",
      "caesars": "+12500",
      "draftkings": "+15000",
      "fanduel": "+10000",
      "pinnacle": "+13315",
      "pointsbet": "+12500",
      "betonline": "+11000",
      "bovada": "+9000",
      "unibet": "+10000",
      "betcris": "+10050"
    }
  },
  {
    "player_name": "Noren, Alex",
    "dg_id": 10419,
    "bestOdds": "+15050",
    "bestBook": "betcris",
    "dgOdds": "+15052",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+15000",
      "caesars": "+9000",
      "draftkings": "+13500",
      "fanduel": "+10000",
      "pinnacle": "+13240",
      "pointsbet": "+9000",
      "betonline": "+13500",
      "bovada": "+12500",
      "unibet": "+8000",
      "betcris": "+15050"
    }
  },
  {
    "player_name": "Bridgeman, Jacob",
    "dg_id": 29433,
    "bestOdds": "+15050",
    "bestBook": "betcris",
    "dgOdds": "+15900",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+13000",
      "fanduel": "+10000",
      "pinnacle": "+13769",
      "pointsbet": "+12500",
      "betonline": "+15000",
      "bovada": "+15000",
      "unibet": "+10000",
      "betcris": "+15050"
    }
  },
  {
    "player_name": "Puig, David",
    "dg_id": 28984,
    "bestOdds": "+15052",
    "bestBook": "betcris",
    "dgOdds": "+13567",
    "allBooks": {
      "bet365": "+11000",
      "betmgm": "+12500",
      "caesars": "+9000",
      "draftkings": "+9800",
      "fanduel": "+10000",
      "pinnacle": "+12617",
      "pointsbet": "+10000",
      "betonline": "+13500",
      "bovada": "+15000",
      "unibet": "+10000",
      "betcris": "+15052"
    }
  },
  {
    "player_name": "Smalley, Alex",
    "dg_id": 18474,
    "bestOdds": "+16500",
    "bestBook": "betonline",
    "dgOdds": "+17444",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+10000",
      "caesars": "+9000",
      "draftkings": "+10500",
      "fanduel": "+10000",
      "pinnacle": "+14935",
      "pointsbet": "+12500",
      "betonline": "+16500",
      "bovada": "+12500",
      "unibet": "+10000",
      "betcris": "+14996"
    }
  },
  {
    "player_name": "Woodland, Gary",
    "dg_id": 12577,
    "bestOdds": "+16818",
    "bestBook": "pinnacle",
    "dgOdds": "+17972",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+12500",
      "caesars": "+9000",
      "draftkings": "+12000",
      "fanduel": "+10000",
      "pinnacle": "+16818",
      "pointsbet": "+10000",
      "betonline": "+12500",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+13550"
    }
  },
  {
    "player_name": "Bradley, Keegan",
    "dg_id": 13872,
    "bestOdds": "+17170",
    "bestBook": "pinnacle",
    "dgOdds": "+17918",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+15000",
      "fanduel": "+12500",
      "pinnacle": "+17170",
      "pointsbet": "+15000",
      "betonline": "+16500",
      "bovada": "+12500",
      "unibet": "+9000",
      "betcris": "+15050"
    }
  },
  {
    "player_name": "Bhatia, Akshay",
    "dg_id": 26096,
    "bestOdds": "+17253",
    "bestBook": "pinnacle",
    "dgOdds": "+27173",
    "allBooks": {
      "bet365": "+10000",
      "betmgm": "+11000",
      "caesars": "+12500",
      "draftkings": "+14500",
      "fanduel": "+10000",
      "pinnacle": "+17253",
      "pointsbet": "+12500",
      "betonline": "+11000",
      "bovada": "+10000",
      "unibet": "+9000",
      "betcris": "+11550"
    }
  },
  {
    "player_name": "Poston, J.T.",
    "dg_id": 21554,
    "bestOdds": "+18500",
    "bestBook": "betonline",
    "dgOdds": "+21639",
    "allBooks": {
      "bet365": "+11000",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+11500",
      "fanduel": "+12500",
      "pinnacle": "+16607",
      "pointsbet": "+15000",
      "betonline": "+18500",
      "bovada": "+12500",
      "unibet": "+9000",
      "betcris": "+17550"
    }
  },
  {
    "player_name": "Fowler, Rickie",
    "dg_id": 12965,
    "bestOdds": "+18510",
    "bestBook": "pinnacle",
    "dgOdds": "+21252",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+11000",
      "fanduel": "+12500",
      "pinnacle": "+18510",
      "pointsbet": "+15000",
      "betonline": "+15000",
      "bovada": "+12500",
      "unibet": "+10000",
      "betcris": "+15050"
    }
  },
  {
    "player_name": "Day, Jason",
    "dg_id": 9771,
    "bestOdds": "+18935",
    "bestBook": "pinnacle",
    "dgOdds": "+30512",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+13500",
      "fanduel": "+12500",
      "pinnacle": "+18935",
      "pointsbet": "+15000",
      "betonline": "+18500",
      "bovada": "+12500",
      "unibet": "+12500",
      "betcris": "+17550"
    }
  },
  {
    "player_name": "Fox, Ryan",
    "dg_id": 11889,
    "bestOdds": "+20239",
    "bestBook": "pinnacle",
    "dgOdds": "+23066",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+16500",
      "fanduel": "+12500",
      "pinnacle": "+20239",
      "pointsbet": "+15000",
      "betonline": "+13500",
      "bovada": "+15000",
      "unibet": "+10000",
      "betcris": "+15050"
    }
  },
  {
    "player_name": "Mitchell, Keith",
    "dg_id": 17365,
    "bestOdds": "+21550",
    "bestBook": "betcris",
    "dgOdds": "+19317",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+15000",
      "caesars": "+12500",
      "draftkings": "+14500",
      "fanduel": "+12500",
      "pinnacle": "+19907",
      "pointsbet": "+15000",
      "betonline": "+20000",
      "bovada": "+17500",
      "unibet": "+12500",
      "betcris": "+21550"
    }
  },
  {
    "player_name": "Berger, Daniel",
    "dg_id": 17606,
    "bestOdds": "+21855",
    "bestBook": "pinnacle",
    "dgOdds": "+31314",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+17500",
      "caesars": "+12500",
      "draftkings": "+21000",
      "fanduel": "+15000",
      "pinnacle": "+21855",
      "pointsbet": "+17500",
      "betonline": "+20000",
      "bovada": "+15000",
      "unibet": "+12500",
      "betcris": "+20050"
    }
  },
  {
    "player_name": "Koivun, Jackson",
    "dg_id": 32319,
    "bestOdds": "+22550",
    "bestBook": "betcris",
    "dgOdds": "+21483",
    "allBooks": {
      "bet365": "+9000",
      "betmgm": "+12500",
      "caesars": "+12500",
      "draftkings": "+14500",
      "fanduel": "+12500",
      "pinnacle": "+14712",
      "pointsbet": "+15000",
      "betonline": "+13500",
      "bovada": "+12500",
      "unibet": "+9000",
      "betcris": "+22550"
    }
  },
  {
    "player_name": "Johnson, Dustin",
    "dg_id": 12422,
    "bestOdds": "+22550",
    "bestBook": "betcris",
    "dgOdds": "+23615",
    "allBooks": {
      "bet365": "+12500",
      "betmgm": "+15000",
      "caesars": "+12500",
      "draftkings": "+17000",
      "fanduel": "+15000",
      "pinnacle": "+20757",
      "pointsbet": "+17500",
      "betonline": "+18500",
      "bovada": "+15000",
      "unibet": "+10000",
      "betcris": "+22550"
    }
  },
  {
    "player_name": "Theegala, Sahith",
    "dg_id": 23014,
    "bestOdds": "+22550",
    "bestBook": "betcris",
    "dgOdds": "+26806",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+15000",
      "caesars": "+17500",
      "draftkings": "+17500",
      "fanduel": "+17500",
      "pinnacle": "+21085",
      "pointsbet": "+20000",
      "betonline": "+22500",
      "bovada": "+15000",
      "unibet": "+15000",
      "betcris": "+22550"
    }
  },
  {
    "player_name": "Hall, Harry",
    "dg_id": 27194,
    "bestOdds": "+22819",
    "bestBook": "betcris",
    "dgOdds": "+25541",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+17500",
      "caesars": "+12500",
      "draftkings": "+18000",
      "fanduel": "+15000",
      "pinnacle": "+20525",
      "pointsbet": "+17500",
      "betonline": "+18500",
      "bovada": "+17500",
      "unibet": "+10000",
      "betcris": "+22819"
    }
  },
  {
    "player_name": "Conners, Corey",
    "dg_id": 17576,
    "bestOdds": "+23298",
    "bestBook": "pinnacle",
    "dgOdds": "+32332",
    "allBooks": {
      "bet365": "+14000",
      "betmgm": "+17500",
      "caesars": "+17500",
      "draftkings": "+21000",
      "fanduel": "+15000",
      "pinnacle": "+23298",
      "pointsbet": "+17500",
      "betonline": "+18500",
      "bovada": "+15000",
      "unibet": "+12500",
      "betcris": "+22550"
    }
  },
  {
    "player_name": "Harman, Brian",
    "dg_id": 8825,
    "bestOdds": "+24975",
    "bestBook": "betcris",
    "dgOdds": "+25110",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+17500",
      "caesars": "+12500",
      "draftkings": "+21000",
      "fanduel": "+15000",
      "pinnacle": "+20425",
      "pointsbet": "+17500",
      "betonline": "+20000",
      "bovada": "+20000",
      "unibet": "+15000",
      "betcris": "+24975"
    }
  },
  {
    "player_name": "Taylor, Nick",
    "dg_id": 13126,
    "bestOdds": "+25050",
    "bestBook": "betcris",
    "dgOdds": "+32687",
    "allBooks": {
      "bet365": "+15000",
      "betmgm": "+15000",
      "caesars": "+17500",
      "draftkings": "+24000",
      "fanduel": "+17500",
      "pinnacle": "+22662",
      "pointsbet": "+20000",
      "betonline": "+17500",
      "bovada": "+12500",
      "unibet": "+15000",
      "betcris": "+25050"
    }
  },
  {
    "player_name": "Im, Sungjae",
    "dg_id": 17488,
    "bestOdds": "+25050",
    "bestBook": "betcris",
    "dgOdds": "+42757",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+15000",
      "caesars": "+17500",
      "draftkings": "+21000",
      "fanduel": "+17500",
      "pinnacle": "+21654",
      "pointsbet": "+20000",
      "betonline": "+20000",
      "bovada": "+17500",
      "unibet": "+12500",
      "betcris": "+25050"
    }
  },
  {
    "player_name": "Yellamaraju, Sudarshan",
    "dg_id": 29925,
    "bestOdds": "+30000",
    "bestBook": "pointsbet",
    "dgOdds": "+33991",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+20000",
      "caesars": "+22500",
      "draftkings": "+14000",
      "fanduel": "+17500",
      "pinnacle": "+26687",
      "pointsbet": "+30000",
      "betonline": "+27500",
      "bovada": "+20000",
      "unibet": "+15000",
      "betcris": "+29970"
    }
  },
  {
    "player_name": "Hisatsune, Ryo",
    "dg_id": 22760,
    "bestOdds": "+30000",
    "bestBook": "pointsbet",
    "dgOdds": "+34186",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+20000",
      "caesars": "+17500",
      "draftkings": "+24000",
      "fanduel": "+17500",
      "pinnacle": "+26665",
      "pointsbet": "+30000",
      "betonline": "+25000",
      "bovada": "+20000",
      "unibet": "+20000",
      "betcris": "+25358"
    }
  },
  {
    "player_name": "Greyserman, Max",
    "dg_id": 23465,
    "bestOdds": "+30050",
    "bestBook": "betcris",
    "dgOdds": "+30669",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+20000",
      "caesars": "+22500",
      "draftkings": "+29000",
      "fanduel": "+22500",
      "pinnacle": "+24336",
      "pointsbet": "+30000",
      "betonline": "+30000",
      "bovada": "+25000",
      "unibet": "+20000",
      "betcris": "+30050"
    }
  },
  {
    "player_name": "Kim, Tom",
    "dg_id": 24766,
    "bestOdds": "+30425",
    "bestBook": "betcris",
    "dgOdds": "+32509",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+15000",
      "caesars": "+17500",
      "draftkings": "+19000",
      "fanduel": "+17500",
      "pinnacle": "+23868",
      "pointsbet": "+30000",
      "betonline": "+22500",
      "bovada": "+17500",
      "unibet": "+15000",
      "betcris": "+30425"
    }
  },
  {
    "player_name": "Kim, Michael",
    "dg_id": 17543,
    "bestOdds": "+32550",
    "bestBook": "betcris",
    "dgOdds": "+40168",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+22500",
      "caesars": "+22500",
      "draftkings": "+29000",
      "fanduel": "+22500",
      "pinnacle": "+30924",
      "pointsbet": "+30000",
      "betonline": "+27500",
      "bovada": "+22500",
      "unibet": "+20000",
      "betcris": "+32550"
    }
  },
  {
    "player_name": "Stevens, Sam",
    "dg_id": 25569,
    "bestOdds": "+32550",
    "bestBook": "betcris",
    "dgOdds": "+43065",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+25000",
      "caesars": "+22500",
      "draftkings": "+28000",
      "fanduel": "+22500",
      "pinnacle": "+30924",
      "pointsbet": "+30000",
      "betonline": "+27500",
      "bovada": "+22500",
      "unibet": "+20000",
      "betcris": "+32550"
    }
  },
  {
    "player_name": "Coody, Pierceson",
    "dg_id": 28309,
    "bestOdds": "+32550",
    "bestBook": "betcris",
    "dgOdds": "+43696",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+22500",
      "caesars": "+22500",
      "draftkings": "+19500",
      "fanduel": "+17500",
      "pinnacle": "+28909",
      "pointsbet": "+30000",
      "betonline": "+27500",
      "bovada": "+30000",
      "unibet": "+17500",
      "betcris": "+32550"
    }
  },
  {
    "player_name": "Novak, Andrew",
    "dg_id": 23475,
    "bestOdds": "+32553",
    "bestBook": "betcris",
    "dgOdds": "+33049",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+25000",
      "caesars": "+22500",
      "draftkings": "+29000",
      "fanduel": "+22500",
      "pinnacle": "+25522",
      "pointsbet": "+30000",
      "betonline": "+30000",
      "bovada": "+25000",
      "unibet": "+20000",
      "betcris": "+32553"
    }
  },
  {
    "player_name": "Schaper, Jayden",
    "dg_id": 26991,
    "bestOdds": "+35000",
    "bestBook": "betonline",
    "dgOdds": "+43065",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+25000",
      "caesars": "+22500",
      "draftkings": "+26000",
      "fanduel": "+17500",
      "pinnacle": "+24263",
      "pointsbet": "+30000",
      "betonline": "+35000",
      "bovada": "+25000",
      "unibet": "+17500",
      "betcris": "+32550"
    }
  },
  {
    "player_name": "Putnam, Andrew",
    "dg_id": 14704,
    "bestOdds": "+35000",
    "bestBook": "betonline",
    "dgOdds": "+48287",
    "allBooks": {
      "bet365": "+27500",
      "betmgm": "+30000",
      "caesars": "+22500",
      "draftkings": "+32000",
      "fanduel": "+22500",
      "pinnacle": "+31256",
      "pointsbet": "+30000",
      "betonline": "+35000",
      "bovada": "+25000",
      "unibet": "+25000",
      "betcris": "+26750"
    }
  },
  {
    "player_name": "Suber, Jackson",
    "dg_id": 29279,
    "bestOdds": "+35000",
    "bestBook": "pointsbet",
    "dgOdds": "+57592",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+25000",
      "caesars": "+27500",
      "draftkings": "+23000",
      "fanduel": "+25000",
      "pinnacle": "+30924",
      "pointsbet": "+35000",
      "betonline": "+27500",
      "bovada": "+25000",
      "unibet": "+20000",
      "betcris": "+25358"
    }
  },
  {
    "player_name": "James, Ben",
    "dg_id": 29827,
    "bestOdds": "+35000",
    "bestBook": "pointsbet",
    "dgOdds": "+58152",
    "allBooks": {
      "betmgm": "+30000",
      "caesars": "+27500",
      "draftkings": "+33000",
      "fanduel": "+25000",
      "pinnacle": "+33991",
      "pointsbet": "+35000",
      "betonline": "+35000",
      "bovada": "+20000",
      "unibet": "+35000",
      "betcris": "+30050"
    }
  },
  {
    "player_name": "Herbert, Lucas",
    "dg_id": 17064,
    "bestOdds": "+35504",
    "bestBook": "betcris",
    "dgOdds": "+32867",
    "allBooks": {
      "bet365": "+17500",
      "betmgm": "+17500",
      "caesars": "+17500",
      "draftkings": "+26000",
      "fanduel": "+17500",
      "pinnacle": "+24357",
      "pointsbet": "+30000",
      "betonline": "+25000",
      "bovada": "+25000",
      "unibet": "+17500",
      "betcris": "+35504"
    }
  },
  {
    "player_name": "Thompson, Davis",
    "dg_id": 27364,
    "bestOdds": "+35504",
    "bestBook": "betcris",
    "dgOdds": "+35828",
    "allBooks": {
      "bet365": "+20000",
      "betmgm": "+20000",
      "caesars": "+22500",
      "draftkings": "+24000",
      "fanduel": "+22500",
      "pinnacle": "+28813",
      "pointsbet": "+30000",
      "betonline": "+25000",
      "bovada": "+20000",
      "unibet": "+15000",
      "betcris": "+35504"
    }
  },
  {
    "player_name": "Brennan, Michael",
    "dg_id": 29197,
    "bestOdds": "+38000",
    "bestBook": "draftkings",
    "dgOdds": "+40441",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+25000",
      "caesars": "+22500",
      "draftkings": "+38000",
      "fanduel": "+22500",
      "pinnacle": "+27320",
      "pointsbet": "+30000",
      "betonline": "+27500",
      "bovada": "+20000",
      "unibet": "+25000",
      "betcris": "+30431"
    }
  },
  {
    "player_name": "McCarty, Matt",
    "dg_id": 28635,
    "bestOdds": "+40560",
    "bestBook": "betcris",
    "dgOdds": "+36710",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+25000",
      "caesars": "+17500",
      "draftkings": "+30000",
      "fanduel": "+17500",
      "pinnacle": "+28708",
      "pointsbet": "+30000",
      "betonline": "+27500",
      "bovada": "+25000",
      "unibet": "+20000",
      "betcris": "+40560"
    }
  },
  {
    "player_name": "Ortiz, Carlos",
    "dg_id": 14735,
    "bestOdds": "+40575",
    "bestBook": "betcris",
    "dgOdds": "+95138",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+25000",
      "caesars": "+27500",
      "draftkings": "+29000",
      "fanduel": "+25000",
      "pinnacle": "+35674",
      "pointsbet": "+35000",
      "betonline": "+35000",
      "bovada": "+25000",
      "unibet": "+25000",
      "betcris": "+40575"
    }
  },
  {
    "player_name": "Keefer, Johnny",
    "dg_id": 32457,
    "bestOdds": "+41000",
    "bestBook": "draftkings",
    "dgOdds": "+72189",
    "allBooks": {
      "bet365": "+25000",
      "betmgm": "+30000",
      "caesars": "+27500",
      "draftkings": "+41000",
      "fanduel": "+35000",
      "pinnacle": "+35029",
      "pointsbet": "+35000",
      "betonline": "+30000",
      "bovada": "+25000",
      "unibet": "+20000",
      "betcris": "+35504"
    }
  },
  {
    "player_name": "Mouw, William",
    "dg_id": 29770,
    "bestOdds": "+42500",
    "bestBook": "draftkings",
    "dgOdds": "+52532",
    "allBooks": {
      "bet365": "+35000",
      "betmgm": "+40000",
      "caesars": "+32500",
      "draftkings": "+42500",
      "fanduel": "+35000",
      "pinnacle": "+37135",
      "pointsbet": "+35000",
      "betonline": "+40000",
      "bovada": "+35000",
      "unibet": "+25000",
      "betcris": "+32550"
    }
  },
  {
    "player_name": "McGreevy, Max",
    "dg_id": 23505,
    "bestOdds": "+45050",
    "bestBook": "betcris",
    "dgOdds": "+59306",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+35000",
      "caesars": "+27500",
      "draftkings": "+45000",
      "fanduel": "+35000",
      "pinnacle": "+38522",
      "pointsbet": "+35000",
      "betonline": "+35000",
      "bovada": "+30000",
      "unibet": "+25000",
      "betcris": "+45050"
    }
  },
  {
    "player_name": "Schmid, Matti",
    "dg_id": 20722,
    "bestOdds": "+50000",
    "bestBook": "draftkings",
    "dgOdds": "+74900",
    "allBooks": {
      "bet365": "+27500",
      "betmgm": "+30000",
      "caesars": "+22500",
      "draftkings": "+50000",
      "fanduel": "+22500",
      "pinnacle": "+36744",
      "pointsbet": "+30000",
      "betonline": "+35000",
      "bovada": "+30000",
      "unibet": "+25000",
      "betcris": "+35050"
    }
  },
  {
    "player_name": "Dumont De Chassart, Adrien",
    "dg_id": 22002,
    "bestOdds": "+50000",
    "bestBook": "fanduel",
    "dgOdds": "+89452",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+40000",
      "caesars": "+37500",
      "draftkings": "+45000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "betonline": "+45000",
      "bovada": "+50000",
      "unibet": "+35000",
      "betcris": "+40575"
    }
  },
  {
    "player_name": "Kirk, Chris",
    "dg_id": 12423,
    "bestOdds": "+50000",
    "bestBook": "draftkings",
    "dgOdds": "+103348",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+30000",
      "caesars": "+27500",
      "draftkings": "+50000",
      "fanduel": "+35000",
      "pinnacle": "+40954",
      "pointsbet": "+35000",
      "betonline": "+35000",
      "bovada": "+30000",
      "unibet": "+25000",
      "betcris": "+35504"
    }
  },
  {
    "player_name": "Echavarria, Nico",
    "dg_id": 22833,
    "bestOdds": "+50000",
    "bestBook": "fanduel",
    "dgOdds": "+111011",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+35000",
      "caesars": "+32500",
      "draftkings": "+49000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "betonline": "+32500",
      "bovada": "+35000",
      "unibet": "+35000",
      "betcris": "+35504"
    }
  },
  {
    "player_name": "Rodgers, Patrick",
    "dg_id": 16283,
    "bestOdds": "+50000",
    "bestBook": "fanduel",
    "dgOdds": "+119900",
    "allBooks": {
      "bet365": "+35000",
      "betmgm": "+35000",
      "caesars": "+47500",
      "draftkings": "+46000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "betonline": "+40000",
      "bovada": "+35000",
      "unibet": "+25000",
      "betcris": "+37568"
    }
  },
  {
    "player_name": "Grillo, Emiliano",
    "dg_id": 12808,
    "bestOdds": "+55000",
    "bestBook": "draftkings",
    "dgOdds": "+96674",
    "allBooks": {
      "bet365": "+30000",
      "betmgm": "+35000",
      "caesars": "+37500",
      "draftkings": "+55000",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "betonline": "+35000",
      "bovada": "+30000",
      "unibet": "+25000",
      "betcris": "+35504"
    }
  },
  {
    "player_name": "Kohles, Ben",
    "dg_id": 16395,
    "bestOdds": "+57500",
    "bestBook": "draftkings",
    "dgOdds": "+73071",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+45000",
      "caesars": "+47500",
      "draftkings": "+57500",
      "fanduel": "+50000",
      "pointsbet": "+45000",
      "betonline": "+50000",
      "bovada": "+50000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Kimsey, Nathan",
    "dg_id": 18027,
    "bestOdds": "+57500",
    "bestBook": "draftkings",
    "dgOdds": "+101595",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+40000",
      "caesars": "+27500",
      "draftkings": "+57500",
      "fanduel": "+35000",
      "pointsbet": "+35000",
      "betonline": "+40000",
      "bovada": "+50000",
      "unibet": "+25000"
    }
  },
  {
    "player_name": "Parry, John",
    "dg_id": 13764,
    "bestOdds": "+57500",
    "bestBook": "draftkings",
    "dgOdds": "+130335",
    "allBooks": {
      "bet365": "+35000",
      "betmgm": "+40000",
      "caesars": "+37500",
      "draftkings": "+57500",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "betonline": "+40000",
      "bovada": "+35000",
      "unibet": "+25000",
      "betcris": "+40575"
    }
  },
  {
    "player_name": "Horschel, Billy",
    "dg_id": 11276,
    "bestOdds": "+60000",
    "bestBook": "draftkings",
    "dgOdds": "+146241",
    "allBooks": {
      "bet365": "+22500",
      "betmgm": "+30000",
      "caesars": "+27500",
      "draftkings": "+60000",
      "fanduel": "+25000",
      "pinnacle": "+43316",
      "pointsbet": "+35000",
      "betonline": "+27500",
      "bovada": "+25000",
      "unibet": "+25000",
      "betcris": "+25358"
    }
  },
  {
    "player_name": "Stout, Preston",
    "dg_id": 32089,
    "bestOdds": "+75000",
    "bestBook": "fanduel",
    "dgOdds": "+105163",
    "allBooks": {
      "bet365": "+45000",
      "betmgm": "+60000",
      "caesars": "+47500",
      "draftkings": "+45000",
      "fanduel": "+75000",
      "pointsbet": "+40000",
      "betonline": "+50000",
      "bovada": "+50000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Surratt, Caleb",
    "dg_id": 30463,
    "bestOdds": "+77500",
    "bestBook": "draftkings",
    "dgOdds": "+285614",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+50000",
      "caesars": "+37500",
      "draftkings": "+77500",
      "fanduel": "+50000",
      "pinnacle": "+41803",
      "pointsbet": "+40000",
      "betonline": "+45000",
      "bovada": "+50000",
      "unibet": "+35000"
    }
  },
  {
    "player_name": "Canter, Laurie",
    "dg_id": 14795,
    "bestOdds": "+85000",
    "bestBook": "draftkings",
    "dgOdds": "+214186",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+50000",
      "caesars": "+47500",
      "draftkings": "+85000",
      "fanduel": "+50000",
      "pinnacle": "+45183",
      "pointsbet": "+40000",
      "betonline": "+60000",
      "bovada": "+50000",
      "unibet": "+50000",
      "betcris": "+45648"
    }
  },
  {
    "player_name": "Roy, Kevin",
    "dg_id": 18424,
    "bestOdds": "+90000",
    "bestBook": "draftkings",
    "dgOdds": "+239900",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+50000",
      "caesars": "+47500",
      "draftkings": "+90000",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "betonline": "+50000",
      "bovada": "+40000",
      "unibet": "+50000",
      "betcris": "+45648"
    }
  },
  {
    "player_name": "Stanger, Jimmy",
    "dg_id": 23048,
    "bestOdds": "+97500",
    "bestBook": "draftkings",
    "dgOdds": "+239900",
    "allBooks": {
      "bet365": "+40000",
      "betmgm": "+50000",
      "caesars": "+37500",
      "draftkings": "+97500",
      "fanduel": "+50000",
      "pointsbet": "+40000",
      "betonline": "+45000",
      "bovada": "+40000",
      "unibet": "+50000",
      "betcris": "+40575"
    }
  },
  {
    "player_name": "Saddier, Adrien",
    "dg_id": 14792,
    "bestOdds": "+100000",
    "bestBook": "fanduel",
    "dgOdds": "+146241",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+50000",
      "caesars": "+50000",
      "draftkings": "+90000",
      "fanduel": "+100000",
      "pointsbet": "+45000",
      "betonline": "+75000",
      "bovada": "+75000",
      "unibet": "+75000"
    }
  },
  {
    "player_name": "Shipley, Neal",
    "dg_id": 32055,
    "bestOdds": "+100000",
    "bestBook": "fanduel",
    "dgOdds": "+162062",
    "allBooks": {
      "bet365": "+50000",
      "betmgm": "+50000",
      "caesars": "+50000",
      "draftkings": "+67500",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+60000",
      "bovada": "+60000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Du Plessis, Hennie",
    "dg_id": 19421,
    "bestOdds": "+100000",
    "bestBook": "betmgm",
    "dgOdds": "+171329",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+100000",
      "pointsbet": "+90000",
      "betonline": "+100000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Russell, Miles",
    "dg_id": 32064,
    "bestOdds": "+100000",
    "bestBook": "betmgm",
    "dgOdds": "+374900",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+100000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+60000",
      "bovada": "+50000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Jordan, Matthew",
    "dg_id": 25601,
    "bestOdds": "+115000",
    "bestBook": "draftkings",
    "dgOdds": "+285614",
    "allBooks": {
      "bet365": "+35000",
      "betmgm": "+50000",
      "caesars": "+22500",
      "draftkings": "+115000",
      "fanduel": "+25000",
      "pointsbet": "+35000",
      "betonline": "+35000",
      "bovada": "+50000",
      "unibet": "+50000",
      "betcris": "+40575"
    }
  },
  {
    "player_name": "Blair, Zac",
    "dg_id": 17639,
    "bestOdds": "+130000",
    "bestBook": "draftkings",
    "dgOdds": "+187400",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+60000",
      "caesars": "+50000",
      "draftkings": "+130000",
      "fanduel": "+100000",
      "pointsbet": "+45000",
      "betonline": "+75000",
      "bovada": "+50000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Hammer, Cole",
    "dg_id": 19864,
    "bestOdds": "+145000",
    "bestBook": "draftkings",
    "dgOdds": "+272627",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+60000",
      "caesars": "+75000",
      "draftkings": "+145000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+125000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Dossey, Cooper",
    "dg_id": 29347,
    "bestOdds": "+150000",
    "bestBook": "caesars",
    "dgOdds": "+122349",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+50000",
      "caesars": "+150000",
      "draftkings": "+72500",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+100000",
      "bovada": "+100000",
      "unibet": "+75000"
    }
  },
  {
    "player_name": "Phillips, Chandler",
    "dg_id": 27164,
    "bestOdds": "+150000",
    "bestBook": "caesars",
    "dgOdds": "+249900",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+150000",
      "draftkings": "+67500",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+125000",
      "bovada": "+100000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Tosti, Alejandro",
    "dg_id": 17032,
    "bestOdds": "+150000",
    "bestBook": "draftkings",
    "dgOdds": "+333233",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+75000",
      "draftkings": "+150000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+100000",
      "bovada": "+50000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Harrington, Padraig",
    "dg_id": 5716,
    "bestOdds": "+170000",
    "bestBook": "draftkings",
    "dgOdds": "+1199900",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+150000",
      "draftkings": "+170000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+100000",
      "bovada": "+75000",
      "unibet": "+50000",
      "betcris": "+50718"
    }
  },
  {
    "player_name": "Wu, Dylan",
    "dg_id": 25002,
    "bestOdds": "+180000",
    "bestBook": "draftkings",
    "dgOdds": "+315689",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+100000",
      "caesars": "+50000",
      "draftkings": "+180000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+125000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Coussaud, Ugo",
    "dg_id": 20727,
    "bestOdds": "+200000",
    "bestBook": "caesars",
    "dgOdds": "+193448",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+200000",
      "draftkings": "+92500",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+125000",
      "bovada": "+100000",
      "unibet": "+75000"
    }
  },
  {
    "player_name": "Silverman, Ben",
    "dg_id": 17381,
    "bestOdds": "+200000",
    "bestBook": "draftkings",
    "dgOdds": "+399900",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+200000",
      "fanduel": "+100000",
      "pointsbet": "+45000",
      "betonline": "+100000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Norgaard, Niklas",
    "dg_id": 15676,
    "bestOdds": "+200000",
    "bestBook": "draftkings",
    "dgOdds": "+749900",
    "allBooks": {
      "bet365": "+60000",
      "betmgm": "+50000",
      "caesars": "+50000",
      "draftkings": "+200000",
      "fanduel": "+100000",
      "pointsbet": "+45000",
      "betonline": "+75000",
      "bovada": "+75000",
      "unibet": "+50000",
      "betcris": "+45648"
    }
  },
  {
    "player_name": "Montgomery, Taylor",
    "dg_id": 25442,
    "bestOdds": "+200000",
    "bestBook": "draftkings",
    "dgOdds": "+999900",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+150000",
      "draftkings": "+200000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+125000",
      "bovada": "+100000",
      "unibet": "+75000"
    }
  },
  {
    "player_name": "Kim, T.K.",
    "dg_id": 18349,
    "bestOdds": "+200000",
    "bestBook": "betonline",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+100000",
      "caesars": "+47500",
      "betonline": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Yuan, Carl",
    "dg_id": 17266,
    "bestOdds": "+250000",
    "bestBook": "draftkings",
    "dgOdds": "+545355",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+125000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Hardy, Nick",
    "dg_id": 19865,
    "bestOdds": "+250000",
    "bestBook": "draftkings",
    "dgOdds": "+599900",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+50000",
      "draftkings": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+45000",
      "betonline": "+100000",
      "bovada": "+75000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Uihlein, Peter",
    "dg_id": 11357,
    "bestOdds": "+250000",
    "bestBook": "draftkings",
    "dgOdds": "+1499900",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+50000",
      "caesars": "+50000",
      "draftkings": "+250000",
      "fanduel": "+100000",
      "pointsbet": "+40000",
      "betonline": "+60000",
      "bovada": "+40000",
      "unibet": "+50000",
      "betcris": "+40575"
    }
  },
  {
    "player_name": "Fang, Ethan",
    "dg_id": 34025,
    "bestOdds": "+275000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+275000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+200000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Puebla, Giuseppe",
    "dg_id": 33280,
    "bestOdds": "+300000",
    "bestBook": "betonline",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+300000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Sato, Taihei",
    "dg_id": 14371,
    "bestOdds": "+325000",
    "bestBook": "draftkings",
    "dgOdds": "+428471",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+75000",
      "caesars": "+150000",
      "draftkings": "+325000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+150000",
      "bovada": "+150000",
      "unibet": "+75000"
    }
  },
  {
    "player_name": "Nicholas, James",
    "dg_id": 27598,
    "bestOdds": "+325000",
    "bestBook": "draftkings",
    "dgOdds": "+599900",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+100000",
      "caesars": "+150000",
      "draftkings": "+325000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+100000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Lee, Eric",
    "dg_id": 30035245,
    "bestOdds": "+325000",
    "bestBook": "draftkings",
    "dgOdds": "+666567",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+150000",
      "draftkings": "+325000",
      "betonline": "+200000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "McDowell, Graeme",
    "dg_id": 7548,
    "bestOdds": "+325000",
    "bestBook": "draftkings",
    "dgOdds": "+1999900",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+75000",
      "caesars": "+150000",
      "draftkings": "+325000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+150000",
      "bovada": "+100000",
      "unibet": "+50000"
    }
  },
  {
    "player_name": "Higgs, Harry",
    "dg_id": 14140,
    "bestOdds": "+350000",
    "bestBook": "draftkings",
    "dgOdds": "+666567",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+100000",
      "caesars": "+150000",
      "draftkings": "+350000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+125000",
      "bovada": "+100000",
      "unibet": "+75000"
    }
  },
  {
    "player_name": "Leach, Greyson",
    "dg_id": 35062,
    "bestOdds": "+350000",
    "bestBook": "draftkings",
    "dgOdds": "+666567",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+150000",
      "caesars": "+100000",
      "draftkings": "+350000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+150000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Cowan, Ryder",
    "dg_id": 30035557,
    "bestOdds": "+400000",
    "bestBook": "caesars",
    "dgOdds": "+1499900",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+150000",
      "caesars": "+400000",
      "draftkings": "+325000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+200000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Howell, Mason",
    "dg_id": 33759,
    "bestOdds": "+400000",
    "bestBook": "caesars",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+100000",
      "caesars": "+400000",
      "draftkings": "+300000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+200000",
      "bovada": "+150000",
      "unibet": "+75000"
    }
  },
  {
    "player_name": "Arni Sveinsson, Gunnlaugur",
    "dg_id": 30036877,
    "bestOdds": "+400000",
    "bestBook": "caesars",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+150000",
      "caesars": "+400000",
      "draftkings": "+275000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+250000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Herrington, Jackson",
    "dg_id": 35015,
    "bestOdds": "+400000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+150000",
      "draftkings": "+400000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+300000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Rozo, Marcelo",
    "dg_id": 16591,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+857043",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+100000",
      "caesars": "+200000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+150000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Repetto Taylor, Rocco Paolo",
    "dg_id": 31235,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+75000",
      "caesars": "+150000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+45000",
      "betonline": "+150000",
      "bovada": "+100000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Peacock, Jake",
    "dg_id": 33952,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+150000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Lee, Bryan",
    "dg_id": 33756,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+250000",
      "bovada": "+100000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Tibbits, Spencer",
    "dg_id": 26650,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+300000",
      "betmgm": "+150000",
      "draftkings": "+450000",
      "betonline": "+400000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Celli, Filippo",
    "dg_id": 23549,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+150000",
      "caesars": "+150000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+150000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Holmes, J.B.",
    "dg_id": 7959,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+100000",
      "caesars": "+400000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+300000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Van Paris, Jackson",
    "dg_id": 31955,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+125000",
      "betmgm": "+150000",
      "caesars": "+75000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+150000",
      "bovada": "+100000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Reilly, Logan",
    "dg_id": 30039012,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+150000",
      "caesars": "+150000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+250000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Pulcini, Mateo",
    "dg_id": 35013,
    "bestOdds": "+450000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+400000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+300000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Hidalgo Portillo, Angel",
    "dg_id": 24127,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+1999900",
    "allBooks": {
      "bet365": "+75000",
      "betmgm": "+75000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+45000",
      "betonline": "+100000",
      "bovada": "+75000",
      "unibet": "+75000"
    }
  },
  {
    "player_name": "Onishi, Kaito",
    "dg_id": 25263,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+200000",
      "betmgm": "+100000",
      "caesars": "+150000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+250000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Coleman, Hamilton",
    "dg_id": 34994,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+2999900",
    "allBooks": {
      "bet365": "+300000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+400000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Oiwa, Ryuichi",
    "dg_id": 20761,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+150000",
      "betmgm": "+100000",
      "caesars": "+150000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+200000",
      "bovada": "+150000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Higgins, Robbie",
    "dg_id": 33442,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+5999900",
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+300000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Robles, Matt",
    "dg_id": 30039992,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+300000",
      "betmgm": "+150000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+400000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Kyes, Chase",
    "dg_id": 30039832,
    "bestOdds": "+500000",
    "bestBook": "betonline",
    "dgOdds": null,
    "allBooks": {
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+450000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+500000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Schoenberger, Jack",
    "dg_id": 30039809,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "betmgm": "+150000",
      "caesars": "+400000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+500000",
      "bovada": "+100000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Harber, Vaughn",
    "dg_id": 30042170,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+500000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Holtz, Brandon",
    "dg_id": 35014,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+300000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+400000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Shah, Manav",
    "dg_id": 21901,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+300000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Wu, Brandon",
    "dg_id": 25213,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": "+1999900",
    "allBooks": {
      "bet365": "+100000",
      "betmgm": "+75000",
      "caesars": "+75000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+60000",
      "betonline": "+125000",
      "bovada": "+100000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Sollon, Jake",
    "dg_id": 30528,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+250000",
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+300000",
      "bovada": "+200000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Ormond, Jackson",
    "dg_id": 35389,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "bet365": "+300000",
      "betmgm": "+150000",
      "caesars": "+150000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+400000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  },
  {
    "player_name": "Fleming, Marek",
    "dg_id": 30042928,
    "bestOdds": "+500000",
    "bestBook": "draftkings",
    "dgOdds": null,
    "allBooks": {
      "betmgm": "+150000",
      "caesars": "+200000",
      "draftkings": "+500000",
      "fanduel": "+100000",
      "pointsbet": "+90000",
      "betonline": "+500000",
      "bovada": "+250000",
      "unibet": "+100000"
    }
  }
];
