// Generated by scripts/build-ticker.ts on 2026-08-09T15:34:48.925Z
// wyndham-championship-2026 — round 3 tee times + scores. 81 players. DO NOT EDIT BY HAND.

export interface TickerEntry {
  player: string;
  teeTime: string;
  startHole: number;
  score: number | null;
  pos: string;
  thru: number | null;
}

export const tickerRound = 3;
/** ISO timestamp of the latest live-data pull. The Header reads this
 *  to compute "Last Updated" — keeps in sync with the every-30-min
 *  ticker refresh instead of the (hours-old) rankings-data build time. */
export const tickerGeneratedAt = '2026-08-09T15:34:48.925Z';
export const tickerData: TickerEntry[] = [
  {
    "player": "Akina, Kihei",
    "teeTime": "7:45 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Bauchou, Zach",
    "teeTime": "12:10 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Bezuidenhout, Christiaan",
    "teeTime": "7:05 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Bradley, Keegan",
    "teeTime": "7:15 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Brennan, Michael",
    "teeTime": "1:05 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Campos, Rafael",
    "teeTime": "11:40 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Castillo, Ricky",
    "teeTime": "9:55 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Cauley, Bud",
    "teeTime": "9:55 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Chatfield, Davis",
    "teeTime": "7:05 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Cole, Eric",
    "teeTime": "12:45 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Collet, Tyler",
    "teeTime": "12:00 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Crowe, Trace",
    "teeTime": "11:20 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Dahmen, Joel",
    "teeTime": "11:30 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Echavarria, Nico",
    "teeTime": "8:05 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Eckroat, Austin",
    "teeTime": "10:15 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Finau, Tony",
    "teeTime": "7:25 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Fishburn, Patrick",
    "teeTime": "9:20 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Fitzpatrick, Alex",
    "teeTime": "10:45 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Ghim, Doug",
    "teeTime": "1:45 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Greyserman, Max",
    "teeTime": "1:35 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Hall, Harry",
    "teeTime": "10:25 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Highsmith, Joe",
    "teeTime": "10:55 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Hirata, Kensei",
    "teeTime": "7:35 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Hodges, Lee",
    "teeTime": "9:30 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Hoey, Rico",
    "teeTime": "1:05 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Hoge, Tom",
    "teeTime": "12:45 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Hojgaard, Rasmus",
    "teeTime": "9:40 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Horschel, Billy",
    "teeTime": "12:55 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Hossler, Beau",
    "teeTime": "1:55 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Hughes, Mackenzie",
    "teeTime": "10:45 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Im, Sungjae",
    "teeTime": "10:05 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "James, Ben",
    "teeTime": "1:55 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Kim, Michael",
    "teeTime": "10:35 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Kim, Tom",
    "teeTime": "12:20 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Kirk, Chris",
    "teeTime": "9:40 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Kizzire, Patton",
    "teeTime": "7:55 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Koepka, Brooks",
    "teeTime": "12:00 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Kohles, Ben",
    "teeTime": "7:00 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Koivun, Jackson",
    "teeTime": "10:25 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Lower, Justin",
    "teeTime": "8:50 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Malnati, Peter",
    "teeTime": "7:45 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Matsuyama, Hideki",
    "teeTime": "11:30 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "McCarthy, Denny",
    "teeTime": "12:30 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "McCarty, Matt",
    "teeTime": "9:00 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "McNealy, Maverick",
    "teeTime": "10:55 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Mitchell, Keith",
    "teeTime": "8:15 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Noren, Alex",
    "teeTime": "1:25 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Novak, Andrew",
    "teeTime": "9:30 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Nyholm, Pontus",
    "teeTime": "8:40 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Olesen, Thorbjorn",
    "teeTime": "9:10 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Parry, John",
    "teeTime": "8:30 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Pendrith, Taylor",
    "teeTime": "10:15 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Penge, Marco",
    "teeTime": "8:50 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Phillips, Chandler",
    "teeTime": "11:40 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Putnam, Andrew",
    "teeTime": "8:30 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Rai, Aaron",
    "teeTime": "9:00 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Ramey, Chad",
    "teeTime": "12:55 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Roy, Kevin",
    "teeTime": "11:05 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Saddier, Adrien",
    "teeTime": "11:20 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Schmid, Matti",
    "teeTime": "1:15 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Shipley, Neal",
    "teeTime": "9:20 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Simpson, Webb",
    "teeTime": "7:25 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Skinns, David",
    "teeTime": "1:25 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Smalley, Alex",
    "teeTime": "1:15 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Smith, Jordan",
    "teeTime": "1:45 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Smotherman, Austin",
    "teeTime": "7:35 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Snedeker, Brandt",
    "teeTime": "10:35 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Spieth, Jordan",
    "teeTime": "7:55 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Springer, Hayden",
    "teeTime": "11:50 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Streelman, Kevin",
    "teeTime": "10:05 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Suber, Jackson",
    "teeTime": "12:20 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Taylor, Nick",
    "teeTime": "8:05 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Theegala, Sahith",
    "teeTime": "1:35 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Thomas, Justin",
    "teeTime": "9:10 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Thompson, Davis",
    "teeTime": "12:30 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Van Rooyen, Erik",
    "teeTime": "11:05 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Ventura, Kristoffer",
    "teeTime": "8:40 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Walker, Danny",
    "teeTime": "11:50 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Wallace, Matt",
    "teeTime": "8:15 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Young, Cameron",
    "teeTime": "7:15 AM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  },
  {
    "player": "Yu, Kevin",
    "teeTime": "12:10 PM",
    "startHole": 1,
    "score": null,
    "pos": "--",
    "thru": null
  }
];
