// Generated by scripts/build-ticker.ts on 2026-05-24T17:12:59.405Z
// cj-cup-byron-nelson-2026 — round 1 tee times + scores. 70 players. DO NOT EDIT BY HAND.

export interface TickerEntry {
  player: string;
  teeTime: string;
  startHole: number;
  score: number | null;
  pos: string;
  thru: number | null;
}

export const tickerRound = 1;
export const tickerData: TickerEntry[] = [
  {
    "player": "Kim, Si Woo",
    "teeTime": "7:33 AM",
    "startHole": 10,
    "score": -21,
    "pos": "1",
    "thru": 0
  },
  {
    "player": "Clark, Wyndham",
    "teeTime": "7:44 AM",
    "startHole": 10,
    "score": -19,
    "pos": "T2",
    "thru": 0
  },
  {
    "player": "Scheffler, Scottie",
    "teeTime": "7:33 AM",
    "startHole": 10,
    "score": -19,
    "pos": "T2",
    "thru": 0
  },
  {
    "player": "Hoge, Tom",
    "teeTime": "7:22 AM",
    "startHole": 10,
    "score": -17,
    "pos": "T4",
    "thru": 0
  },
  {
    "player": "Im, Sungjae",
    "teeTime": "12:43 PM",
    "startHole": 1,
    "score": -17,
    "pos": "T4",
    "thru": 0
  },
  {
    "player": "Jaeger, Stephan",
    "teeTime": "7:44 AM",
    "startHole": 10,
    "score": -17,
    "pos": "T4",
    "thru": 0
  },
  {
    "player": "Bauchou, Zach",
    "teeTime": "2:00 PM",
    "startHole": 1,
    "score": -16,
    "pos": "7",
    "thru": 0
  },
  {
    "player": "Greyserman, Max",
    "teeTime": "12:54 PM",
    "startHole": 1,
    "score": -15,
    "pos": "T8",
    "thru": 0
  },
  {
    "player": "Higgo, Garrick",
    "teeTime": "12:43 PM",
    "startHole": 10,
    "score": -15,
    "pos": "T8",
    "thru": 18
  },
  {
    "player": "Koepka, Brooks",
    "teeTime": "7:33 AM",
    "startHole": 10,
    "score": -15,
    "pos": "T8",
    "thru": 0
  },
  {
    "player": "Mitchell, Keith",
    "teeTime": "7:11 AM",
    "startHole": 1,
    "score": -15,
    "pos": "T8",
    "thru": 0
  },
  {
    "player": "Suber, Jackson",
    "teeTime": "8:50 AM",
    "startHole": 10,
    "score": -15,
    "pos": "T8",
    "thru": 1
  },
  {
    "player": "Svensson, Jesper",
    "teeTime": "1:49 PM",
    "startHole": 10,
    "score": -15,
    "pos": "T8",
    "thru": 4
  },
  {
    "player": "Brown, Blades",
    "teeTime": "7:44 AM",
    "startHole": 10,
    "score": -14,
    "pos": "T14",
    "thru": 2
  },
  {
    "player": "Clanton, Luke",
    "teeTime": "1:38 PM",
    "startHole": 1,
    "score": -14,
    "pos": "T14",
    "thru": 13
  },
  {
    "player": "Cole, Eric",
    "teeTime": "8:17 AM",
    "startHole": 10,
    "score": -14,
    "pos": "T14",
    "thru": 18
  },
  {
    "player": "Finau, Tony",
    "teeTime": "7:55 AM",
    "startHole": 10,
    "score": -14,
    "pos": "T14",
    "thru": 2
  },
  {
    "player": "Grillo, Emiliano",
    "teeTime": "7:00 AM",
    "startHole": 1,
    "score": -14,
    "pos": "T14",
    "thru": 11
  },
  {
    "player": "Hirata, Kensei",
    "teeTime": "1:38 PM",
    "startHole": 1,
    "score": -14,
    "pos": "T14",
    "thru": 3
  },
  {
    "player": "Hubbard, Mark",
    "teeTime": "7:00 AM",
    "startHole": 10,
    "score": -14,
    "pos": "T14",
    "thru": 9
  },
  {
    "player": "Keefer, Johnny",
    "teeTime": "8:28 AM",
    "startHole": 1,
    "score": -14,
    "pos": "T14",
    "thru": 10
  },
  {
    "player": "Malnati, Peter",
    "teeTime": "12:10 PM",
    "startHole": 10,
    "score": -14,
    "pos": "T14",
    "thru": 6
  },
  {
    "player": "Meissner, Mac",
    "teeTime": "12:10 PM",
    "startHole": 1,
    "score": -14,
    "pos": "T14",
    "thru": 13
  },
  {
    "player": "Moore, Taylor",
    "teeTime": "1:16 PM",
    "startHole": 10,
    "score": -14,
    "pos": "T14",
    "thru": 5
  },
  {
    "player": "Spieth, Jordan",
    "teeTime": "12:43 PM",
    "startHole": 1,
    "score": -14,
    "pos": "T14",
    "thru": 15
  },
  {
    "player": "Van Rooyen, Erik",
    "teeTime": "7:11 AM",
    "startHole": 10,
    "score": -14,
    "pos": "T14",
    "thru": 1
  },
  {
    "player": "Ewart, A.J.",
    "teeTime": "2:00 PM",
    "startHole": 10,
    "score": -13,
    "pos": "T27",
    "thru": 11
  },
  {
    "player": "Hisatsune, Ryo",
    "teeTime": "12:32 PM",
    "startHole": 1,
    "score": -13,
    "pos": "T27",
    "thru": 4
  },
  {
    "player": "Power, Seamus",
    "teeTime": "7:22 AM",
    "startHole": 1,
    "score": -13,
    "pos": "T27",
    "thru": 11
  },
  {
    "player": "Ryder, Sam",
    "teeTime": "1:16 PM",
    "startHole": 1,
    "score": -13,
    "pos": "T27",
    "thru": 7
  },
  {
    "player": "Saddier, Adrien",
    "teeTime": "9:01 AM",
    "startHole": 10,
    "score": -13,
    "pos": "T27",
    "thru": 16
  },
  {
    "player": "Duncan, Tyler",
    "teeTime": "1:05 PM",
    "startHole": 10,
    "score": -12,
    "pos": "T32",
    "thru": 11
  },
  {
    "player": "Fisk, Steven",
    "teeTime": "7:55 AM",
    "startHole": 1,
    "score": -12,
    "pos": "T32",
    "thru": 3
  },
  {
    "player": "Ghim, Doug",
    "teeTime": "7:00 AM",
    "startHole": 1,
    "score": -12,
    "pos": "T32",
    "thru": 12
  },
  {
    "player": "Kirk, Chris",
    "teeTime": "12:43 PM",
    "startHole": 1,
    "score": -12,
    "pos": "T32",
    "thru": 6
  },
  {
    "player": "Neergaard-Petersen, Rasmus",
    "teeTime": "8:50 AM",
    "startHole": 1,
    "score": -12,
    "pos": "T32",
    "thru": 4
  },
  {
    "player": "Noh, S.Y.",
    "teeTime": "7:00 AM",
    "startHole": 1,
    "score": -12,
    "pos": "T32",
    "thru": 4
  },
  {
    "player": "Parry, John",
    "teeTime": "1:49 PM",
    "startHole": 1,
    "score": -12,
    "pos": "T32",
    "thru": 16
  },
  {
    "player": "Pavon, Matthieu",
    "teeTime": "1:05 PM",
    "startHole": 10,
    "score": -12,
    "pos": "T32",
    "thru": 14
  },
  {
    "player": "Shipley, Neal",
    "teeTime": "8:39 AM",
    "startHole": 10,
    "score": -12,
    "pos": "T32",
    "thru": 18
  },
  {
    "player": "Brown, Dan",
    "teeTime": "1:38 PM",
    "startHole": 10,
    "score": -11,
    "pos": "T41",
    "thru": 18
  },
  {
    "player": "Coody, Pierceson",
    "teeTime": "12:32 PM",
    "startHole": 1,
    "score": -11,
    "pos": "T41",
    "thru": 9
  },
  {
    "player": "Eckroat, Austin",
    "teeTime": "12:32 PM",
    "startHole": 10,
    "score": -11,
    "pos": "T41",
    "thru": 8
  },
  {
    "player": "Gomez, Fabian",
    "teeTime": "8:06 AM",
    "startHole": 10,
    "score": -11,
    "pos": "T41",
    "thru": 18
  },
  {
    "player": "Hoey, Rico",
    "teeTime": "8:28 AM",
    "startHole": 10,
    "score": -11,
    "pos": "T41",
    "thru": 5
  },
  {
    "player": "Kang, Jeffrey",
    "teeTime": "8:50 AM",
    "startHole": 10,
    "score": -11,
    "pos": "T41",
    "thru": 14
  },
  {
    "player": "Lower, Justin",
    "teeTime": "8:17 AM",
    "startHole": 1,
    "score": -11,
    "pos": "T41",
    "thru": 15
  },
  {
    "player": "Merritt, Troy",
    "teeTime": "1:27 PM",
    "startHole": 10,
    "score": -11,
    "pos": "T41",
    "thru": 8
  },
  {
    "player": "Pendrith, Taylor",
    "teeTime": "12:54 PM",
    "startHole": 1,
    "score": -11,
    "pos": "T41",
    "thru": 18
  },
  {
    "player": "Rodgers, Patrick",
    "teeTime": "8:06 AM",
    "startHole": 10,
    "score": -11,
    "pos": "T41",
    "thru": 8
  },
  {
    "player": "Silverman, Ben",
    "teeTime": "7:11 AM",
    "startHole": 1,
    "score": -11,
    "pos": "T41",
    "thru": 7
  },
  {
    "player": "Villegas, Camilo",
    "teeTime": "1:16 PM",
    "startHole": 1,
    "score": -11,
    "pos": "T41",
    "thru": 8
  },
  {
    "player": "Hoffman, Charley",
    "teeTime": "7:44 AM",
    "startHole": 1,
    "score": -10,
    "pos": "T53",
    "thru": 12
  },
  {
    "player": "Kim, Tom",
    "teeTime": "7:00 AM",
    "startHole": 10,
    "score": -10,
    "pos": "T53",
    "thru": 18
  },
  {
    "player": "List, Luke",
    "teeTime": "1:16 PM",
    "startHole": 10,
    "score": -10,
    "pos": "T53",
    "thru": 10
  },
  {
    "player": "Smith, Jordan",
    "teeTime": "8:28 AM",
    "startHole": 10,
    "score": -10,
    "pos": "T53",
    "thru": 17
  },
  {
    "player": "Svensson, Adam",
    "teeTime": "12:10 PM",
    "startHole": 1,
    "score": -10,
    "pos": "T53",
    "thru": 18
  },
  {
    "player": "Byrd, Jonathan",
    "teeTime": "7:22 AM",
    "startHole": 1,
    "score": -9,
    "pos": "T58",
    "thru": 18
  },
  {
    "player": "Kim, Chan",
    "teeTime": "2:11 PM",
    "startHole": 10,
    "score": -9,
    "pos": "T58",
    "thru": 10
  },
  {
    "player": "Lebioda, Hank",
    "teeTime": "12:21 PM",
    "startHole": 10,
    "score": -9,
    "pos": "T58",
    "thru": 17
  },
  {
    "player": "Ramey, Chad",
    "teeTime": "8:06 AM",
    "startHole": 10,
    "score": -9,
    "pos": "T58",
    "thru": 18
  },
  {
    "player": "Bae, Yongjun",
    "teeTime": "1:49 PM",
    "startHole": 1,
    "score": -8,
    "pos": "T62",
    "thru": 18
  },
  {
    "player": "Fishburn, Patrick",
    "teeTime": "2:11 PM",
    "startHole": 10,
    "score": -8,
    "pos": "T62",
    "thru": 8
  },
  {
    "player": "Hojgaard, Rasmus",
    "teeTime": "7:22 AM",
    "startHole": 10,
    "score": -8,
    "pos": "T62",
    "thru": 18
  },
  {
    "player": "Olesen, Thorbjorn",
    "teeTime": "1:05 PM",
    "startHole": 1,
    "score": -8,
    "pos": "T62",
    "thru": 18
  },
  {
    "player": "Hughes, Mackenzie",
    "teeTime": "7:11 AM",
    "startHole": 10,
    "score": -7,
    "pos": "66",
    "thru": 18
  },
  {
    "player": "Griffin, Lanto",
    "teeTime": "1:05 PM",
    "startHole": 10,
    "score": -5,
    "pos": "T67",
    "thru": 18
  },
  {
    "player": "VanDerLaan, John",
    "teeTime": "2:22 PM",
    "startHole": 10,
    "score": -5,
    "pos": "T67",
    "thru": 18
  },
  {
    "player": "Blair, Zac",
    "teeTime": "8:06 AM",
    "startHole": 1,
    "score": -4,
    "pos": "69",
    "thru": 18
  },
  {
    "player": "Willett, Danny",
    "teeTime": "1:16 PM",
    "startHole": 1,
    "score": -3,
    "pos": "70",
    "thru": 18
  }
];
