// Generated by scripts/build-ticker.ts on 2026-05-25T21:18:57.910Z
// charles-schwab-challenge-2026 — round 1 tee times + scores. 0 players. DO NOT EDIT BY HAND.

export interface TickerEntry {
  player: string;
  teeTime: string;
  startHole: number;
  score: number | null;
  pos: string;
  thru: number | null;
}

export const tickerRound = 1;
export const tickerData: TickerEntry[] = [];
