import type { MatchupOddsEntry } from '../types';

// Generated by scripts/build-matchups.ts on 2026-06-20T04:01:26.794Z
// Event: us-open-2026, phase: r2, market: round_matchups, round: 3
// 97 matchups (merged best-odds-ever-seen). DO NOT EDIT BY HAND.

export const r3MatchupOddsData: MatchupOddsEntry[] = [
  {
    "p1_player_name": "Blair, Zac",
    "p2_player_name": "McGreevy, Max",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+158",
        "p2": "-104"
      },
      "pointsbet": {
        "p1": "+125",
        "p2": "-120"
      },
      "caesars": {
        "p1": "+110",
        "p2": "-140"
      },
      "draftkings": {
        "p1": "+112",
        "p2": "-140"
      },
      "unibet": {
        "p1": "+112",
        "p2": "-143"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Conners, Corey",
    "odds": {
      "betcris": {
        "p1": "-145",
        "p2": "+115"
      },
      "datagolf": {
        "p1": "-121",
        "p2": "+121"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Keefer, Johnny",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "-113",
        "p2": "+167"
      },
      "pointsbet": {
        "p1": "-135",
        "p2": "+140"
      },
      "betmgm": {
        "p1": "-143",
        "p2": "+115"
      },
      "caesars": {
        "p1": "-165",
        "p2": "+127"
      },
      "draftkings": {
        "p1": "-146",
        "p2": "+116"
      },
      "pinnacle": {
        "p1": "-156",
        "p2": "+127"
      },
      "unibet": {
        "p1": "-152",
        "p2": "+120"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Poston, J.T.",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-120",
        "p2": "+120"
      }
    }
  },
  {
    "p1_player_name": "Bradley, Keegan",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "betonline": {
        "p1": "-118",
        "p2": "-102"
      },
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      }
    }
  },
  {
    "p1_player_name": "Burns, Sam",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "datagolf": {
        "p1": "+103",
        "p2": "-103"
      },
      "draftkings": {
        "p1": "-120",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Burns, Sam",
    "p2_player_name": "Morikawa, Collin",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      }
    }
  },
  {
    "p1_player_name": "Burns, Sam",
    "p2_player_name": "Theegala, Sahith",
    "odds": {
      "bet365": {
        "p1": "-138",
        "p2": "+150"
      },
      "datagolf": {
        "p1": "-110",
        "p2": "+164"
      },
      "pointsbet": {
        "p1": "-125",
        "p2": "+125"
      },
      "caesars": {
        "p1": "-150",
        "p2": "+120"
      },
      "draftkings": {
        "p1": "-156",
        "p2": "+125"
      },
      "pinnacle": {
        "p1": "-169",
        "p2": "+137"
      },
      "unibet": {
        "p1": "-152",
        "p2": "+120"
      }
    }
  },
  {
    "p1_player_name": "Canter, Laurie",
    "p2_player_name": "Kim, Michael",
    "odds": {
      "bet365": {
        "p1": "+137",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+165",
        "p2": "-111"
      },
      "pointsbet": {
        "p1": "+120",
        "p2": "-120"
      },
      "betmgm": {
        "p1": "+105",
        "p2": "-133"
      },
      "caesars": {
        "p1": "+110",
        "p2": "-140"
      },
      "draftkings": {
        "p1": "+108",
        "p2": "-136"
      },
      "unibet": {
        "p1": "+120",
        "p2": "-152"
      }
    }
  },
  {
    "p1_player_name": "Canter, Laurie",
    "p2_player_name": "Shipley, Neal",
    "odds": {
      "betcris": {
        "p1": "-113",
        "p2": "-117"
      },
      "datagolf": {
        "p1": "+107",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Cauley, Bud",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "bet365": {
        "p1": "+100",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "+123",
        "p2": "-123"
      }
    }
  },
  {
    "p1_player_name": "Cauley, Bud",
    "p2_player_name": "Koivun, Jackson",
    "odds": {
      "betcris": {
        "p1": "-123",
        "p2": "-107"
      },
      "datagolf": {
        "p1": "-115",
        "p2": "+115"
      }
    }
  },
  {
    "p1_player_name": "Cauley, Bud",
    "p2_player_name": "Shipley, Neal",
    "odds": {
      "bet365": {
        "p1": "-140",
        "p2": "+160"
      },
      "datagolf": {
        "p1": "-132",
        "p2": "+195"
      },
      "pointsbet": {
        "p1": "-150",
        "p2": "+150"
      },
      "betmgm": {
        "p1": "-200",
        "p2": "+155"
      },
      "caesars": {
        "p1": "-180",
        "p2": "+140"
      },
      "draftkings": {
        "p1": "-192",
        "p2": "+154"
      },
      "unibet": {
        "p1": "-167",
        "p2": "+130"
      }
    }
  },
  {
    "p1_player_name": "Conners, Corey",
    "p2_player_name": "Hisatsune, Ryo",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+103"
      }
    }
  },
  {
    "p1_player_name": "Conners, Corey",
    "p2_player_name": "Poston, J.T.",
    "odds": {
      "betonline": {
        "p1": "-112",
        "p2": "-108"
      },
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      }
    }
  },
  {
    "p1_player_name": "Conners, Corey",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "bet365": {
        "p1": "+125",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+149",
        "p2": "+100"
      },
      "pointsbet": {
        "p1": "+125",
        "p2": "-120"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "-106",
        "p2": "-118"
      },
      "pinnacle": {
        "p1": "+115",
        "p2": "-139"
      },
      "unibet": {
        "p1": "+112",
        "p2": "-143"
      }
    }
  },
  {
    "p1_player_name": "Coody, Pierceson",
    "p2_player_name": "Brennan, Michael",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+109",
        "p2": "-109"
      }
    }
  },
  {
    "p1_player_name": "Dumont De Chassart, Adrien",
    "p2_player_name": "James, Ben",
    "odds": {
      "betcris": {
        "p1": "+105",
        "p2": "-135"
      },
      "datagolf": {
        "p1": "+116",
        "p2": "-116"
      }
    }
  },
  {
    "p1_player_name": "Dumont De Chassart, Adrien",
    "p2_player_name": "Tibbits, Spencer",
    "odds": {
      "bet365": {
        "p1": "-160",
        "p2": "+175"
      },
      "datagolf": {
        "p1": "-213",
        "p2": "+311"
      },
      "unibet": {
        "p1": "-335",
        "p2": "+250"
      }
    }
  },
  {
    "p1_player_name": "Fitzpatrick, Alex",
    "p2_player_name": "Bhatia, Akshay",
    "odds": {
      "betonline": {
        "p1": "-130",
        "p2": "+109"
      },
      "datagolf": {
        "p1": "-115",
        "p2": "+115"
      }
    }
  },
  {
    "p1_player_name": "Fitzpatrick, Matt",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "bet365": {
        "p1": "-125",
        "p2": "+137"
      },
      "datagolf": {
        "p1": "+106",
        "p2": "+141"
      },
      "betcris": {
        "p1": "-140",
        "p2": "+110"
      },
      "betonline": {
        "p1": "-140",
        "p2": "+117"
      },
      "caesars": {
        "p1": "-135",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-148",
        "p2": "+118"
      },
      "pinnacle": {
        "p1": "-143",
        "p2": "+117"
      },
      "unibet": {
        "p1": "-136",
        "p2": "+108"
      }
    }
  },
  {
    "p1_player_name": "Fitzpatrick, Matt",
    "p2_player_name": "Schauffele, Xander",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+106",
        "p2": "-106"
      },
      "draftkings": {
        "p1": "-110",
        "p2": "-120"
      }
    }
  },
  {
    "p1_player_name": "Fleetwood, Tommy",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "bet365": {
        "p1": "+100",
        "p2": "+110"
      },
      "datagolf": {
        "p1": "+114",
        "p2": "+130"
      },
      "pointsbet": {
        "p1": "-120",
        "p2": "+120"
      },
      "betcris": {
        "p1": "-126",
        "p2": "-104"
      },
      "betmgm": {
        "p1": "-120",
        "p2": "-105"
      },
      "betonline": {
        "p1": "-128",
        "p2": "+107"
      },
      "caesars": {
        "p1": "-140",
        "p2": "+110"
      },
      "draftkings": {
        "p1": "-120",
        "p2": "-105"
      },
      "pinnacle": {
        "p1": "-113",
        "p2": "-107"
      },
      "unibet": {
        "p1": "-120",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Fleetwood, Tommy",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "datagolf": {
        "p1": "-112",
        "p2": "+112"
      },
      "draftkings": {
        "p1": "-120",
        "p2": "-110"
      }
    }
  },
  {
    "p1_player_name": "Fox, Ryan",
    "p2_player_name": "Brennan, Michael",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "+115"
      },
      "datagolf": {
        "p1": "+123",
        "p2": "+121"
      },
      "pointsbet": {
        "p1": "+100",
        "p2": "+100"
      },
      "betcris": {
        "p1": "-123",
        "p2": "-107"
      },
      "betmgm": {
        "p1": "-133",
        "p2": "+105"
      },
      "caesars": {
        "p1": "-115",
        "p2": "-115"
      },
      "draftkings": {
        "p1": "-132",
        "p2": "+106"
      },
      "pinnacle": {
        "p1": "-117",
        "p2": "-103"
      },
      "unibet": {
        "p1": "-125",
        "p2": "-103"
      }
    }
  },
  {
    "p1_player_name": "Fox, Ryan",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "betonline": {
        "p1": "+125",
        "p2": "-150"
      },
      "datagolf": {
        "p1": "+141",
        "p2": "-141"
      }
    }
  },
  {
    "p1_player_name": "Gotterup, Chris",
    "p2_player_name": "Bridgeman, Jacob",
    "odds": {
      "betcris": {
        "p1": "-127",
        "p2": "-103"
      },
      "datagolf": {
        "p1": "-124",
        "p2": "+124"
      }
    }
  },
  {
    "p1_player_name": "Gotterup, Chris",
    "p2_player_name": "Lee, Eric",
    "odds": {
      "bet365": {
        "p1": "-220",
        "p2": "+240"
      },
      "datagolf": {
        "p1": "-220",
        "p2": "+326"
      },
      "unibet": {
        "p1": "-335",
        "p2": "+250"
      }
    }
  },
  {
    "p1_player_name": "Greyserman, Max",
    "p2_player_name": "Coody, Pierceson",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+110",
        "p2": "+137"
      },
      "pointsbet": {
        "p1": "-110",
        "p2": "+110"
      },
      "betcris": {
        "p1": "-124",
        "p2": "-106"
      },
      "betmgm": {
        "p1": "+100",
        "p2": "-125"
      },
      "caesars": {
        "p1": "-140",
        "p2": "+110"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-122"
      },
      "pinnacle": {
        "p1": "-115",
        "p2": "-105"
      },
      "unibet": {
        "p1": "-114",
        "p2": "-114"
      }
    }
  },
  {
    "p1_player_name": "Grillo, Emiliano",
    "p2_player_name": "Rodgers, Patrick",
    "odds": {
      "bet365": {
        "p1": "+100",
        "p2": "+110"
      },
      "datagolf": {
        "p1": "+112",
        "p2": "+135"
      },
      "pointsbet": {
        "p1": "-105",
        "p2": "+105"
      },
      "betcris": {
        "p1": "-124",
        "p2": "-106"
      },
      "betmgm": {
        "p1": "-110",
        "p2": "-115"
      },
      "caesars": {
        "p1": "-125",
        "p2": "-105"
      },
      "draftkings": {
        "p1": "-110",
        "p2": "-114"
      },
      "unibet": {
        "p1": "-114",
        "p2": "-114"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "McNealy, Maverick",
    "odds": {
      "betcris": {
        "p1": "+101",
        "p2": "-131"
      },
      "datagolf": {
        "p1": "+122",
        "p2": "-122"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Mitchell, Keith",
    "odds": {
      "betonline": {
        "p1": "-108",
        "p2": "-112"
      },
      "datagolf": {
        "p1": "-107",
        "p2": "+107"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "datagolf": {
        "p1": "+112",
        "p2": "-112"
      },
      "draftkings": {
        "p1": "-104",
        "p2": "-128"
      }
    }
  },
  {
    "p1_player_name": "Harman, Brian",
    "p2_player_name": "Scheffler, Scottie",
    "odds": {
      "bet365": {
        "p1": "+250",
        "p2": "-225"
      },
      "datagolf": {
        "p1": "+265",
        "p2": "-174"
      },
      "pointsbet": {
        "p1": "+225",
        "p2": "-230"
      },
      "caesars": {
        "p1": "+230",
        "p2": "-310"
      },
      "draftkings": {
        "p1": "+260",
        "p2": "-330"
      },
      "pinnacle": {
        "p1": "+215",
        "p2": "-283"
      },
      "unibet": {
        "p1": "+195",
        "p2": "-250"
      }
    }
  },
  {
    "p1_player_name": "Hatton, Tyrrell",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "+115"
      },
      "datagolf": {
        "p1": "+132",
        "p2": "+112"
      },
      "pointsbet": {
        "p1": "-105",
        "p2": "+105"
      },
      "betmgm": {
        "p1": "-120",
        "p2": "-105"
      },
      "caesars": {
        "p1": "-145",
        "p2": "-110"
      },
      "draftkings": {
        "p1": "-124",
        "p2": "-102"
      },
      "pinnacle": {
        "p1": "+101",
        "p2": "-122"
      },
      "unibet": {
        "p1": "-120",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Hatton, Tyrrell",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "betcris": {
        "p1": "+100",
        "p2": "-130"
      },
      "datagolf": {
        "p1": "+127",
        "p2": "-127"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Aberg, Ludvig",
    "odds": {
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      },
      "draftkings": {
        "p1": "-104",
        "p2": "-125"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Spieth, Jordan",
    "odds": {
      "betcris": {
        "p1": "-139",
        "p2": "+109"
      },
      "datagolf": {
        "p1": "-130",
        "p2": "+130"
      }
    }
  },
  {
    "p1_player_name": "Henley, Russell",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "-125"
      },
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-102",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "Hidalgo Portillo, Angel",
    "p2_player_name": "Nicholas, James",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+134",
        "p2": "+109"
      },
      "betcris": {
        "p1": "-108",
        "p2": "-122"
      },
      "unibet": {
        "p1": "-107",
        "p2": "-120"
      }
    }
  },
  {
    "p1_player_name": "Higgs, Harry",
    "p2_player_name": "Mouw, William",
    "odds": {
      "bet365": {
        "p1": "+115",
        "p2": "-135"
      },
      "betonline": {
        "p1": "+126",
        "p2": "-152"
      },
      "datagolf": {
        "p1": "+145",
        "p2": "-145"
      }
    }
  },
  {
    "p1_player_name": "Hisatsune, Ryo",
    "p2_player_name": "Theegala, Sahith",
    "odds": {
      "betonline": {
        "p1": "+105",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+116",
        "p2": "-116"
      }
    }
  },
  {
    "p1_player_name": "Im, Sungjae",
    "p2_player_name": "Greyserman, Max",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+111",
        "p2": "-111"
      }
    }
  },
  {
    "p1_player_name": "Im, Sungjae",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "betcris": {
        "p1": "+119",
        "p2": "-149"
      },
      "datagolf": {
        "p1": "+151",
        "p2": "-151"
      }
    }
  },
  {
    "p1_player_name": "Im, Sungjae",
    "p2_player_name": "Young, Cameron",
    "odds": {
      "bet365": {
        "p1": "+170",
        "p2": "-150"
      },
      "datagolf": {
        "p1": "+201",
        "p2": "-135"
      },
      "pointsbet": {
        "p1": "+175",
        "p2": "-175"
      },
      "betmgm": {
        "p1": "+165",
        "p2": "-208"
      },
      "caesars": {
        "p1": "+175",
        "p2": "-230"
      },
      "draftkings": {
        "p1": "+168",
        "p2": "-210"
      },
      "pinnacle": {
        "p1": "+164",
        "p2": "-206"
      },
      "unibet": {
        "p1": "+145",
        "p2": "-186"
      }
    }
  },
  {
    "p1_player_name": "James, Ben",
    "p2_player_name": "Van Paris, Jackson",
    "odds": {
      "bet365": {
        "p1": "-138",
        "p2": "+150"
      },
      "datagolf": {
        "p1": "-147",
        "p2": "+220"
      },
      "unibet": {
        "p1": "-200",
        "p2": "+155"
      }
    }
  },
  {
    "p1_player_name": "Johnson, Dustin",
    "p2_player_name": "Henley, Russell",
    "odds": {
      "bet365": {
        "p1": "+160",
        "p2": "-140"
      },
      "datagolf": {
        "p1": "+173",
        "p2": "-116"
      },
      "pointsbet": {
        "p1": "+135",
        "p2": "-135"
      },
      "betmgm": {
        "p1": "+130",
        "p2": "-167"
      },
      "caesars": {
        "p1": "+127",
        "p2": "-165"
      },
      "draftkings": {
        "p1": "+132",
        "p2": "-166"
      },
      "pinnacle": {
        "p1": "+142",
        "p2": "-176"
      },
      "unibet": {
        "p1": "+120",
        "p2": "-152"
      }
    }
  },
  {
    "p1_player_name": "Johnson, Dustin",
    "p2_player_name": "Koivun, Jackson",
    "odds": {
      "betonline": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "-115",
        "p2": "+115"
      }
    }
  },
  {
    "p1_player_name": "Johnson, Dustin",
    "p2_player_name": "Niemann, Joaquin",
    "odds": {
      "betcris": {
        "p1": "+111",
        "p2": "-141"
      },
      "datagolf": {
        "p1": "-100",
        "p2": "+100"
      },
      "draftkings": {
        "p1": "-104",
        "p2": "-126"
      }
    }
  },
  {
    "p1_player_name": "Kim, Michael",
    "p2_player_name": "Coody, Pierceson",
    "odds": {
      "betonline": {
        "p1": "-102",
        "p2": "-118"
      },
      "datagolf": {
        "p1": "+104",
        "p2": "-104"
      }
    }
  },
  {
    "p1_player_name": "Kim, Michael",
    "p2_player_name": "Echavarria, Nico",
    "odds": {
      "betcris": {
        "p1": "-134",
        "p2": "+104"
      },
      "datagolf": {
        "p1": "-126",
        "p2": "+126"
      }
    }
  },
  {
    "p1_player_name": "Kim, Tom",
    "p2_player_name": "Stevens, Sam",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "betcris": {
        "p1": "-128",
        "p2": "-102"
      },
      "betonline": {
        "p1": "-118",
        "p2": "-102"
      },
      "datagolf": {
        "p1": "-108",
        "p2": "+108"
      }
    }
  },
  {
    "p1_player_name": "Kohles, Ben",
    "p2_player_name": "Keefer, Johnny",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "betcris": {
        "p1": "-104",
        "p2": "-126"
      },
      "datagolf": {
        "p1": "-100",
        "p2": "+100"
      }
    }
  },
  {
    "p1_player_name": "MacIntyre, Robert",
    "p2_player_name": "Fleming, Marek",
    "odds": {
      "bet365": {
        "p1": "-230",
        "p2": "+260"
      },
      "datagolf": {
        "p1": "-358",
        "p2": "+534"
      },
      "unibet": {
        "p1": "-560",
        "p2": "+410"
      }
    }
  },
  {
    "p1_player_name": "MacIntyre, Robert",
    "p2_player_name": "Gotterup, Chris",
    "odds": {
      "betonline": {
        "p1": "+102",
        "p2": "-122"
      },
      "datagolf": {
        "p1": "+105",
        "p2": "-105"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Bridgeman, Jacob",
    "odds": {
      "betonline": {
        "p1": "-135",
        "p2": "+113"
      },
      "datagolf": {
        "p1": "-118",
        "p2": "+118"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "Echavarria, Nico",
    "odds": {
      "bet365": {
        "p1": "-134",
        "p2": "+150"
      },
      "datagolf": {
        "p1": "-121",
        "p2": "+182"
      },
      "pointsbet": {
        "p1": "-150",
        "p2": "+150"
      },
      "betmgm": {
        "p1": "-189",
        "p2": "+150"
      },
      "caesars": {
        "p1": "-180",
        "p2": "+140"
      },
      "draftkings": {
        "p1": "-190",
        "p2": "+152"
      },
      "unibet": {
        "p1": "-186",
        "p2": "+145"
      }
    }
  },
  {
    "p1_player_name": "Matsuyama, Hideki",
    "p2_player_name": "MacIntyre, Robert",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "betcris": {
        "p1": "-105",
        "p2": "-125"
      },
      "datagolf": {
        "p1": "+102",
        "p2": "-102"
      }
    }
  },
  {
    "p1_player_name": "McGreevy, Max",
    "p2_player_name": "Fitzpatrick, Alex",
    "odds": {
      "betcris": {
        "p1": "+117",
        "p2": "-147"
      },
      "datagolf": {
        "p1": "+148",
        "p2": "-148"
      }
    }
  },
  {
    "p1_player_name": "McGreevy, Max",
    "p2_player_name": "Keefer, Johnny",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-102",
        "p2": "+102"
      }
    }
  },
  {
    "p1_player_name": "McIlroy, Rory",
    "p2_player_name": "McNealy, Maverick",
    "odds": {
      "bet365": {
        "p1": "-150",
        "p2": "+162"
      },
      "datagolf": {
        "p1": "-111",
        "p2": "+166"
      },
      "pointsbet": {
        "p1": "-150",
        "p2": "+150"
      },
      "caesars": {
        "p1": "-180",
        "p2": "+140"
      },
      "draftkings": {
        "p1": "-205",
        "p2": "+164"
      },
      "pinnacle": {
        "p1": "-170",
        "p2": "+138"
      },
      "unibet": {
        "p1": "-167",
        "p2": "+130"
      }
    }
  },
  {
    "p1_player_name": "McIlroy, Rory",
    "p2_player_name": "Scheffler, Scottie",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "-130"
      },
      "betcris": {
        "p1": "+124",
        "p2": "-156"
      },
      "betonline": {
        "p1": "+123",
        "p2": "-148"
      },
      "datagolf": {
        "p1": "+134",
        "p2": "-134"
      },
      "draftkings": {
        "p1": "+112",
        "p2": "-146"
      }
    }
  },
  {
    "p1_player_name": "McNealy, Maverick",
    "p2_player_name": "Fitzpatrick, Alex",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-103",
        "p2": "+103"
      },
      "draftkings": {
        "p1": "-125",
        "p2": "-104"
      }
    }
  },
  {
    "p1_player_name": "Mitchell, Keith",
    "p2_player_name": "Bhatia, Akshay",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "+134",
        "p2": "+110"
      },
      "pointsbet": {
        "p1": "+100",
        "p2": "+100"
      },
      "betcris": {
        "p1": "-115",
        "p2": "-115"
      },
      "caesars": {
        "p1": "-115",
        "p2": "-115"
      },
      "draftkings": {
        "p1": "-112",
        "p2": "-112"
      },
      "pinnacle": {
        "p1": "-108",
        "p2": "-112"
      },
      "unibet": {
        "p1": "-107",
        "p2": "-120"
      }
    }
  },
  {
    "p1_player_name": "Mitchell, Keith",
    "p2_player_name": "Hisatsune, Ryo",
    "odds": {
      "datagolf": {
        "p1": "-105",
        "p2": "+105"
      },
      "draftkings": {
        "p1": "-126",
        "p2": "-104"
      }
    }
  },
  {
    "p1_player_name": "Morikawa, Collin",
    "p2_player_name": "Kim, Tom",
    "odds": {
      "bet365": {
        "p1": "-138",
        "p2": "+150"
      },
      "datagolf": {
        "p1": "-109",
        "p2": "+162"
      },
      "pointsbet": {
        "p1": "-135",
        "p2": "+140"
      },
      "caesars": {
        "p1": "-170",
        "p2": "+130"
      },
      "draftkings": {
        "p1": "-170",
        "p2": "+136"
      },
      "pinnacle": {
        "p1": "-165",
        "p2": "+134"
      },
      "unibet": {
        "p1": "-152",
        "p2": "+120"
      }
    }
  },
  {
    "p1_player_name": "Mouw, William",
    "p2_player_name": "Cowan, Ryder",
    "odds": {
      "bet365": {
        "p1": "-140",
        "p2": "+160"
      },
      "datagolf": {
        "p1": "-120",
        "p2": "+176"
      },
      "unibet": {
        "p1": "-167",
        "p2": "+130"
      }
    }
  },
  {
    "p1_player_name": "Niemann, Joaquin",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "bet365": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+119",
        "p2": "-119"
      }
    }
  },
  {
    "p1_player_name": "Norgaard, Niklas",
    "p2_player_name": "Blair, Zac",
    "odds": {
      "betcris": {
        "p1": "-110",
        "p2": "-120"
      },
      "betonline": {
        "p1": "+107",
        "p2": "-128"
      },
      "datagolf": {
        "p1": "+120",
        "p2": "-120"
      }
    }
  },
  {
    "p1_player_name": "Norgaard, Niklas",
    "p2_player_name": "Fitzpatrick, Alex",
    "odds": {
      "bet365": {
        "p1": "+187",
        "p2": "-170"
      },
      "datagolf": {
        "p1": "+257",
        "p2": "-173"
      },
      "pointsbet": {
        "p1": "+175",
        "p2": "-175"
      },
      "caesars": {
        "p1": "+175",
        "p2": "-230"
      },
      "draftkings": {
        "p1": "+176",
        "p2": "-220"
      },
      "unibet": {
        "p1": "+195",
        "p2": "-250"
      }
    }
  },
  {
    "p1_player_name": "Parry, John",
    "p2_player_name": "Putnam, Andrew",
    "odds": {
      "bet365": {
        "p1": "+120",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+148",
        "p2": "+103"
      },
      "pointsbet": {
        "p1": "+115",
        "p2": "-110"
      },
      "betcris": {
        "p1": "-105",
        "p2": "-125"
      },
      "betmgm": {
        "p1": "+105",
        "p2": "-130"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "+104",
        "p2": "-130"
      },
      "unibet": {
        "p1": "+108",
        "p2": "-136"
      }
    }
  },
  {
    "p1_player_name": "Poston, J.T.",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "bet365": {
        "p1": "+125",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+152",
        "p2": "-102"
      },
      "pointsbet": {
        "p1": "+115",
        "p2": "-115"
      },
      "betcris": {
        "p1": "-103",
        "p2": "-127"
      },
      "betmgm": {
        "p1": "-105",
        "p2": "-120"
      },
      "caesars": {
        "p1": "+105",
        "p2": "-135"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-122"
      },
      "pinnacle": {
        "p1": "+119",
        "p2": "-145"
      },
      "unibet": {
        "p1": "+104",
        "p2": "-132"
      }
    }
  },
  {
    "p1_player_name": "Poston, J.T.",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "datagolf": {
        "p1": "+128",
        "p2": "-128"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-128"
      }
    }
  },
  {
    "p1_player_name": "Putnam, Andrew",
    "p2_player_name": "James, Ben",
    "odds": {
      "betonline": {
        "p1": "-140",
        "p2": "+117"
      },
      "datagolf": {
        "p1": "-117",
        "p2": "+117"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Griffin, Ben",
    "odds": {
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      },
      "draftkings": {
        "p1": "-124",
        "p2": "-106"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Hatton, Tyrrell",
    "odds": {
      "betonline": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "-108",
        "p2": "+108"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Kitayama, Kurt",
    "odds": {
      "bet365": {
        "p1": "-120",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+101",
        "p2": "-101"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Kohles, Ben",
    "odds": {
      "bet365": {
        "p1": "-150",
        "p2": "+170"
      },
      "datagolf": {
        "p1": "-116",
        "p2": "+174"
      },
      "pointsbet": {
        "p1": "-140",
        "p2": "+150"
      },
      "betmgm": {
        "p1": "-189",
        "p2": "+150"
      },
      "caesars": {
        "p1": "-180",
        "p2": "+140"
      },
      "draftkings": {
        "p1": "-186",
        "p2": "+148"
      },
      "unibet": {
        "p1": "-167",
        "p2": "+130"
      }
    }
  },
  {
    "p1_player_name": "Rose, Justin",
    "p2_player_name": "Rai, Aaron",
    "odds": {
      "betcris": {
        "p1": "-126",
        "p2": "-104"
      },
      "datagolf": {
        "p1": "-104",
        "p2": "+104"
      }
    }
  },
  {
    "p1_player_name": "Russell, Miles",
    "p2_player_name": "Koivun, Jackson",
    "odds": {
      "bet365": {
        "p1": "+160",
        "p2": "-143"
      },
      "datagolf": {
        "p1": "+201",
        "p2": "-136"
      },
      "pointsbet": {
        "p1": "+140",
        "p2": "-135"
      },
      "unibet": {
        "p1": "+145",
        "p2": "-186"
      }
    }
  },
  {
    "p1_player_name": "Schauffele, Xander",
    "p2_player_name": "Morikawa, Collin",
    "odds": {
      "betcris": {
        "p1": "-144",
        "p2": "+114"
      },
      "betonline": {
        "p1": "-140",
        "p2": "+117"
      },
      "datagolf": {
        "p1": "-125",
        "p2": "+125"
      }
    }
  },
  {
    "p1_player_name": "Schauffele, Xander",
    "p2_player_name": "Stevens, Sam",
    "odds": {
      "bet365": {
        "p1": "-180",
        "p2": "+200"
      },
      "datagolf": {
        "p1": "-145",
        "p2": "+215"
      },
      "pointsbet": {
        "p1": "-175",
        "p2": "+170"
      },
      "caesars": {
        "p1": "-230",
        "p2": "+175"
      },
      "draftkings": {
        "p1": "-235",
        "p2": "+186"
      },
      "pinnacle": {
        "p1": "-219",
        "p2": "+173"
      },
      "unibet": {
        "p1": "-220",
        "p2": "+170"
      }
    }
  },
  {
    "p1_player_name": "Spieth, Jordan",
    "p2_player_name": "Hatton, Tyrrell",
    "odds": {
      "bet365": {
        "p1": "+100",
        "p2": "-120"
      },
      "datagolf": {
        "p1": "-101",
        "p2": "+101"
      },
      "draftkings": {
        "p1": "-102",
        "p2": "-128"
      }
    }
  },
  {
    "p1_player_name": "Spieth, Jordan",
    "p2_player_name": "Niemann, Joaquin",
    "odds": {
      "bet365": {
        "p1": "+105",
        "p2": "+105"
      },
      "datagolf": {
        "p1": "+108",
        "p2": "+137"
      },
      "pointsbet": {
        "p1": "+100",
        "p2": "+100"
      },
      "betmgm": {
        "p1": "-125",
        "p2": "+100"
      },
      "betonline": {
        "p1": "-108",
        "p2": "-112"
      },
      "caesars": {
        "p1": "-115",
        "p2": "-115"
      },
      "draftkings": {
        "p1": "-122",
        "p2": "-102"
      },
      "pinnacle": {
        "p1": "-109",
        "p2": "-111"
      },
      "unibet": {
        "p1": "-114",
        "p2": "-114"
      }
    }
  },
  {
    "p1_player_name": "Stevens, Sam",
    "p2_player_name": "Mouw, William",
    "odds": {
      "datagolf": {
        "p1": "-126",
        "p2": "+126"
      },
      "draftkings": {
        "p1": "-126",
        "p2": "-104"
      }
    }
  },
  {
    "p1_player_name": "Theegala, Sahith",
    "p2_player_name": "Kim, Tom",
    "odds": {
      "datagolf": {
        "p1": "+104",
        "p2": "-104"
      },
      "draftkings": {
        "p1": "-114",
        "p2": "-115"
      }
    }
  },
  {
    "p1_player_name": "Theegala, Sahith",
    "p2_player_name": "Mouw, William",
    "odds": {
      "betcris": {
        "p1": "-145",
        "p2": "+115"
      },
      "datagolf": {
        "p1": "-130",
        "p2": "+130"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Burns, Sam",
    "odds": {
      "betcris": {
        "p1": "-114",
        "p2": "-116"
      },
      "betonline": {
        "p1": "-105",
        "p2": "-115"
      },
      "datagolf": {
        "p1": "+109",
        "p2": "-109"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Clark, Wyndham",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "-110"
      },
      "datagolf": {
        "p1": "+113",
        "p2": "-113"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Higgs, Harry",
    "odds": {
      "bet365": {
        "p1": "-180",
        "p2": "+200"
      },
      "datagolf": {
        "p1": "-177",
        "p2": "+263"
      },
      "pointsbet": {
        "p1": "-220",
        "p2": "+210"
      },
      "caesars": {
        "p1": "-240",
        "p2": "+180"
      },
      "draftkings": {
        "p1": "-310",
        "p2": "+245"
      },
      "pinnacle": {
        "p1": "-282",
        "p2": "+214"
      },
      "unibet": {
        "p1": "-250",
        "p2": "+195"
      }
    }
  },
  {
    "p1_player_name": "Thomas, Justin",
    "p2_player_name": "Morikawa, Collin",
    "odds": {
      "datagolf": {
        "p1": "+111",
        "p2": "-111"
      },
      "draftkings": {
        "p1": "-112",
        "p2": "-118"
      }
    }
  },
  {
    "p1_player_name": "Uihlein, Peter",
    "p2_player_name": "Surratt, Caleb",
    "odds": {
      "bet365": {
        "p1": "+110",
        "p2": "+100"
      },
      "datagolf": {
        "p1": "+156",
        "p2": "-107"
      },
      "pointsbet": {
        "p1": "+110",
        "p2": "-110"
      },
      "betmgm": {
        "p1": "+110",
        "p2": "-135"
      },
      "caesars": {
        "p1": "-110",
        "p2": "-145"
      },
      "draftkings": {
        "p1": "+108",
        "p2": "-136"
      },
      "unibet": {
        "p1": "+120",
        "p2": "-152"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Bhatia, Akshay",
    "odds": {
      "datagolf": {
        "p1": "+108",
        "p2": "-108"
      },
      "draftkings": {
        "p1": "-118",
        "p2": "-112"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Hisatsune, Ryo",
    "odds": {
      "bet365": {
        "p1": "-110",
        "p2": "+120"
      },
      "datagolf": {
        "p1": "+116",
        "p2": "+130"
      },
      "pointsbet": {
        "p1": "-105",
        "p2": "+105"
      },
      "betcris": {
        "p1": "-108",
        "p2": "-122"
      },
      "caesars": {
        "p1": "-125",
        "p2": "-105"
      },
      "draftkings": {
        "p1": "-128",
        "p2": "+102"
      },
      "pinnacle": {
        "p1": "-117",
        "p2": "-103"
      },
      "unibet": {
        "p1": "-120",
        "p2": "-107"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "Koivun, Jackson",
    "odds": {
      "bet365": {
        "p1": "-115",
        "p2": "-105"
      },
      "datagolf": {
        "p1": "-114",
        "p2": "+114"
      }
    }
  },
  {
    "p1_player_name": "Woodland, Gary",
    "p2_player_name": "McNealy, Maverick",
    "odds": {
      "betonline": {
        "p1": "+121",
        "p2": "-145"
      },
      "datagolf": {
        "p1": "+129",
        "p2": "-129"
      }
    }
  },
  {
    "p1_player_name": "Wu, Dylan",
    "p2_player_name": "Bridgeman, Jacob",
    "odds": {
      "bet365": {
        "p1": "+170",
        "p2": "-150"
      },
      "datagolf": {
        "p1": "+202",
        "p2": "-134"
      },
      "pointsbet": {
        "p1": "+160",
        "p2": "-160"
      },
      "betmgm": {
        "p1": "+155",
        "p2": "-200"
      },
      "caesars": {
        "p1": "+160",
        "p2": "-200"
      },
      "draftkings": {
        "p1": "+158",
        "p2": "-198"
      },
      "unibet": {
        "p1": "+145",
        "p2": "-186"
      }
    }
  }
];
